In [ ]:
print("DHL AI Project is ready!")

In [3]:
import pandas as pd

In [4]:
print(pd.__version__)

3.0.5

In [ ]:
local_df = pd.read_excel("../data/Inc_resolved by MAIT.xlsx")

In [ ]:
local_df.shape

In [ ]:
local_df.head()

In [ ]:
local_df.columns

In [ ]:
local_df["Opened"].dtype

In [ ]:
local_df["Opened"].min()

In [ ]:
local_df["Opened"].max()

In [ ]:
local_2025 = local_df[local_df["Opened"] >= "2025-01-01"]

In [ ]:
local_2025.shape

In [ ]:
print(local_2025["Opened"].min())
print(local_2025["Opened"].max())

In [ ]:
escalated_df = pd.read_excel("../data/Inc_registred by MAIT.xlsx")

In [ ]:
escalated_df.shape

In [ ]:
escalated_df["Opened"].dtype

In [ ]:
escalated_df["Opened"].min()
escalated_df["Opened"].max()

In [ ]:
escalated_df["Opened"].min()

In [ ]:
escalated_df["Opened"].max()

In [ ]:
escalated_2025 = escalated_df[
    escalated_df["Opened"] >= "2025-01-01"
]

In [ ]:
escalated_2025.shape

In [ ]:
print(escalated_2025["Opened"].min())
print(escalated_2025["Opened"].max())

In [ ]:
local_2025["Incident Status"].value_counts()

In [ ]:
escalated_2025["Incident Status"].value_counts()

In [ ]:
local_others = local_2025[
    local_2025["Incident Status"] != "Closed"
]

local_others[[
    "Number",
    "Incident Status",
    "Short Description",
    "Solution"
]]

In [ ]:
escalated_others = escalated_2025[
    escalated_2025["Incident Status"] != "Closed"
]

escalated_others[[
    "Number",
    "Incident Status",
    "Short Description",
    "Solution"
]]

In [ ]:
local_2025["Solution"].isna().sum()

In [ ]:
local_2025["Solution"].value_counts().head(20)

In [ ]:
escalated_2025["Solution"].isna().sum()

In [ ]:
escalated_2025["Solution"].value_counts().head(20)

In [ ]:
local_2025["Solution"].nunique()

In [ ]:
escalated_2025["Solution"].nunique()

In [ ]:
local_solutions_normalized = (
    local_2025["Solution"]
    .astype(str)
    .str.strip()
    .str.lower()
)

In [ ]:
local_solutions_normalized = (
    local_2025["Solution"]
    .astype(str)
    .str.strip()
    .str.lower()
    .str.replace(r"[.!?]+$", "", regex=True)
    .str.replace(r"\s+", " ", regex=True)
)

In [ ]:
local_solutions_normalized.nunique()

In [ ]:
local_solutions_normalized.value_counts().head(15)

In [ ]:
generic_solutions = [
    "resolved",
    "solved",
    "done",
    "necessary done",
    "fixed",
    "closed",
    "granted",
    "issue fixed"
]

In [ ]:
local_solutions_normalized.isin(generic_solutions).sum()

In [ ]:
local_2025.loc[
    ~local_solutions_normalized.isin(generic_solutions),
    ["Short Description", "Solution"]
].head(20)

In [ ]:
local_2025["Description"].isna().sum()

In [ ]:
local_2025["Short Description"].isna().sum()

In [ ]:
escalated_2025["Description"].isna().sum()

In [ ]:
escalated_2025["Short Description"].isna().sum()

In [ ]:
local_2025["Assigned Group"].value_counts()

In [ ]:
escalated_2025["Assigned Group"].value_counts()

In [ ]:
local_2025["Short Description"].head(30).to_list()

In [ ]:
escalated_2025["Short Description"].head(30).to_list()

In [ ]:
local_2025["Description"].str.len().describe()

In [ ]:
escalated_2025["Description"].str.len().describe()

In [ ]:
from langdetect import detect

def detect_language(text):
    try:
        return detect(str(text))
    except:
        return "unknown"

In [ ]:
for text in local_2025["Short Description"].head(20):
    print(detect_language(text), "→", text)

In [ ]:
local_2025["language"] = local_2025["Short Description"].apply(detect_language)

In [ ]:
local_2025["language"].value_counts()

In [ ]:
escalated_2025["language"] = escalated_2025["Short Description"].apply(detect_language)

In [ ]:
escalated_2025["language"].value_counts()

In [ ]:
local_2025.drop(columns=["language"], inplace=True)
escalated_2025.drop(columns=["language"], inplace=True)

In [ ]:
from sentence_transformers import SentenceTransformer

In [ ]:
model = SentenceTransformer("paraphrase-multilingual-MiniLM-L12-v2")

In [ ]:
from sentence_transformers import SentenceTransformer

model = SentenceTransformer("paraphrase-multilingual-MiniLM-L12-v2")

print("Modèle chargé avec succès !")

In [ ]:
import sys
print(sys.executable)

In [ ]:
import sys
print(sys.executable)

In [ ]:
print("TEST")

In [1]:
import sys
print(sys.executable)

C:\Users\LENOVO\PycharmProjects\DHL_AI_Incident_Assistant\.venv\Scripts\python.exe

In [1]:
import sys
print(sys.executable)

C:\Users\LENOVO\PycharmProjects\DHL_AI_Incident_Assistant\.venv311\Scripts\python.exe

In [2]:
from sentence_transformers import SentenceTransformer

print("Sentence Transformers fonctionne !")

C:\Users\LENOVO\PycharmProjects\DHL_AI_Incident_Assistant\.venv311\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

Sentence Transformers fonctionne !

In [3]:
model = SentenceTransformer("paraphrase-multilingual-MiniLM-L12-v2")
print("Modèle chargé !")

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
C:\Users\LENOVO\PycharmProjects\DHL_AI_Incident_Assistant\.venv311\Lib\site-packages\huggingface_hub\file_download.py:141: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\LENOVO\.cache\huggingface\hub\models--sentence-transformers--paraphrase-multilingual-MiniLM-L12-v2. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)
Loading weights: 100%|██████████| 199/199 [00:00<00:00, 3065.35it/s]

Modèle chargé !

In [4]:
texts = [
    "MA - EXP - Probleme d'impression",
    "Issue printing Delivery Sheet from GCA"
]

embeddings = model.encode(texts)

print(embeddings.shape)

(2, 384)

In [5]:
from sklearn.metrics.pairwise import cosine_similarity

similarity = cosine_similarity(
    [embeddings[0]],
    [embeddings[1]]
)

print(similarity)

[[0.5493631]]

In [6]:
local_2025["text_for_embedding"] = (
    local_2025["Short Description"].fillna("").astype(str)
    + " "
    + local_2025["Description"].fillna("").astype(str)
)

NameError: name 'local_2025' is not defined

In [7]:
print(df.shape)

NameError: name 'df' is not defined

In [1]:
import pandas as pd

local_df = pd.read_excel("data/inc_resolved_by MAIT.xlsx")

print(local_df.shape)
print(local_df.columns.tolist())

ModuleNotFoundError: No module named 'pandas'

In [2]:
import pandas as pd

print(pd.__version__)

3.0.5

In [3]:
print(pd.__version__)

3.0.5

In [4]:
import pandas as pd

local_df = pd.read_excel("data/inc_resolved_by MAIT.xlsx")

print(local_df.shape)
print(local_df.columns.tolist())

FileNotFoundError: [Errno 2] No such file or directory: 'data/inc_resolved_by MAIT.xlsx'

In [1]:
import pandas as pd

local_df = pd.read_excel("../data/Inc_resolved by MAIT.xlsx")

print(local_df.shape)
print(local_df.columns.tolist())

C:\Users\LENOVO\PycharmProjects\DHL_AI_Incident_Assistant\.venv311\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

(1813, 11)
['Number', 'Opened', 'Target Resolution Time (GMT)', 'Informed at', 'Incident Status', 'Caller', 'Assigned Group', 'Assignee', 'Short Description', 'Description', 'Solution']

In [2]:
print(local_df["Opened"].dtype)
print(local_df["Opened"].min())
print(local_df["Opened"].max())

datetime64[us]
2024-07-12 18:55:19
2026-08-13 10:43:33

In [3]:
local_2025 = local_df[
    local_df["Opened"].dt.year >= 2025
].copy()

print(local_2025.shape)

(1745, 11)

In [4]:
print("Short Description vides :", local_2025["Short Description"].isna().sum())
print("Description vides      :", local_2025["Description"].isna().sum())
print("Solution vides         :", local_2025["Solution"].isna().sum())

Short Description vides : 0
Description vides      : 0
Solution vides         : 0

In [5]:
local_2025["text_for_embedding"] = (
    local_2025["Short Description"].astype(str)
    + " "
    + local_2025["Description"].astype(str)
)

In [6]:
print(local_2025["text_for_embedding"].head(3).to_string())

2    MA EXP Application e-HCM OASYS not Working via...
3    Update ELMs / IP Whitelisting and URL Update D...
5    Print issue in GCA7 app Dears,\n\nWe recently ...

In [7]:
print("Nombre de textes :", len(local_2025["text_for_embedding"]))
print("Textes vides :", (local_2025["text_for_embedding"].str.strip() == "").sum())

Nombre de textes : 1745
Textes vides : 0

In [8]:
from sentence_transformers import SentenceTransformer

model = SentenceTransformer("paraphrase-multilingual-MiniLM-L12-v2")

print("Modèle chargé avec succès !")

C:\Users\LENOVO\PycharmProjects\DHL_AI_Incident_Assistant\.venv311\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
Loading weights: 100%|██████████| 199/199 [00:00<00:00, 928.76it/s]

Modèle chargé avec succès !

In [9]:
embeddings = model.encode(
    local_2025["text_for_embedding"].tolist(),
    show_progress_bar=True
)

print(embeddings.shape)

Batches: 100%|██████████| 55/55 [01:47<00:00,  1.95s/it]

(1745, 384)

In [10]:
import numpy as np

np.save("../data/local_2025_embeddings.npy", embeddings)

print("Embeddings sauvegardés !")

Embeddings sauvegardés !

In [11]:
local_2025.to_pickle("../data/local_2025.pkl")

print("Tickets sauvegardés !")

Tickets sauvegardés !

In [13]:
new_ticket = "MA - EXP - problème d'impression dans GCA"

In [14]:
new_embedding = model.encode([new_ticket])

print(new_embedding.shape)

(1, 384)

In [15]:
from sklearn.metrics.pairwise import cosine_similarity

similarities = cosine_similarity(
    new_embedding,
    embeddings
)[0]

print(similarities.shape)

(1745,)

In [16]:
top_indices = similarities.argsort()[-5:][::-1]

print(top_indices)

[ 962  948    2 1425 1047]

In [17]:
results = local_2025.iloc[top_indices][
    ["Number", "Short Description", "Solution"]
].copy()

results["Similarity"] = similarities[top_indices]

print(results.to_string(index=False))

     Number       Short Description                     Solution  Similarity
INC66808943   Probleme d'impression                        Fixed    0.688697
INC67011539          Printing issue                       solved    0.683536
INC66441487 Print issue in GCA7 app TN Provider is working on it    0.682678
INC64352664           Printer Issue                     Resolved    0.672607
INC69346363           Printer Issue                 Issue solved    0.663776

In [18]:
results = local_2025.iloc[top_indices][
    ["Number", "Short Description", "Description", "Solution"]
].copy()

results["Similarity"] = similarities[top_indices]

print(results.to_string(index=False))

     Number       Short Description                                                                                                                                                                                                                                                                                                     Description                     Solution  Similarity
INC66808943   Probleme d'impression                                                                                                                                                                                                                                                                                           Probleme d'impression                        Fixed    0.688697
INC67011539          Printing issue                                                                                                                                                                                                                                                                                                  Printing issue                       solved    0.683536
INC66441487 Print issue in GCA7 app Dears,\n\nWe recently added these two printers, but printing does not work!\n\nTNSNDGCA01 : 192.168.251.200    Nated  199.40.179.155\nTNSNDGCA02 : 192.168.251.201    Nated  199.40.179.156\n\nCountry = TN  <>  Location = TUN-SND\n\nCould you please check and advise ?\n\n\n\n\n\nThanks in advance,\nNabil TN Provider is working on it    0.682678
INC64352664           Printer Issue                                                                                                                                                                                                                                    Salam, \n\nProbleme d'impression sur l'imprimantes Transit.\n\nCordialement.                     Resolved    0.672607
INC69346363           Printer Issue                                                                                                                                                                                                                                                                                                   Printer Issue                 Issue solved    0.663776

In [19]:
solution_counts = (
    local_2025["Solution"]
    .astype(str)
    .str.strip()
    .str.lower()
    .value_counts()
)

print(solution_counts.head(30))

Solution
resolved                                                                                              851
solved                                                                                                156
necessary done.                                                                                        59
done                                                                                                   51
access granted                                                                                         46
fixed                                                                                                  38
done.                                                                                                  38
resolved.                                                                                              36
closed                                                                                                 25
resolved,                                                                                               7
granted                                                                                                 7
issue fixed                                                                                             5
customer status is now active. a temporary password has been sent to the customer's email address.      5
regional ticket opened                                                                                  5
duplicate                                                                                               4
enable notifications and sound                                                                          4
data provided                                                                                           4
installed                                                                                               4
please ask performance to provide you with the necessary access.                                        3
resolved  inc63245892                                                                                   2
bonjour, \n\nune demande a été faite inc62438408\n\ncordialement.                                       2
duplicated                                                                                              2
hello anas,\n\nnecessary done.                                                                          2
fixed1                                                                                                  2
change done                                                                                             2
the necessary changes are made.                                                                         2
necessaey done.                                                                                         2
necessary changes are made.                                                                             2
no response from user                                                                                   2
inc69065461                                                                                             2
Name: count, dtype: int64

In [20]:
generic_solutions = {
    "resolved",
    "resolved.",
    "resolved,",
    "solved",
    "done",
    "done.",
    "fixed",
    "closed",
    "granted",
    "issue fixed",
    "issue solved"
}

print("Nombre de solutions génériques :", len(generic_solutions))

Nombre de solutions génériques : 11

In [21]:
solution_normalized = (
    local_2025["Solution"]
    .astype(str)
    .str.strip()
    .str.lower()
)

generic_mask = solution_normalized.isin(generic_solutions)

print("Tickets avec solution générique :", generic_mask.sum())
print("Tickets avec solution informative :", (~generic_mask).sum())

Tickets avec solution générique : 1215
Tickets avec solution informative : 530

In [22]:
informative_solutions = (
    local_2025.loc[~generic_mask, "Solution"]
    .astype(str)
    .str.strip()
    .value_counts()
)

print(informative_solutions.head(30))

Solution
Necessary done.                                                                                               50
Access granted                                                                                                43
Necessary Done.                                                                                                9
Customer status is now active. A temporary password has been sent to the customer's email address.             5
duplicate                                                                                                      4
enable notifications and sound                                                                                 4
Data provided                                                                                                  4
Please Ask performance to provide you with the necessary access.                                               3
installed                                                                                                      3
regional ticket opened                                                                                         3
Bonjour, \n\nUne demande a été faite INC62438408\n\nCordialement.                                              2
Hello Anas,\n\nNecessary done.                                                                                 2
Fixed1                                                                                                         2
Necessaey done.                                                                                                2
Necessary changes are made.                                                                                    2
INC69065461                                                                                                    2
Access granted.                                                                                                2
Hello,\n\nNecessary done.                                                                                      2
Resolved ,                                                                                                     2
Regional ticket opened                                                                                         2
Problem solved                                                                                                 2
Resolved, Un ticket a été créé. Dès que l'accès vous sera accordé, vous recevrez un e-mail de confirmation     2
Resolved,A request has been submitted. Once it is processed, you will receive a notification by email.         2
access granted                                                                                                 2
A new ticket has been raised                                                                                   2
Cancelled by NOC                                                                                               1
TN Provider is working on it                                                                                   1
Resolved, Comme mentionner merci de remplir le fichier excel corrrectement.                                    1
Resolved  INC63245892                                                                                          1
Closed\nl'accès à SPAK est géré par l'équipe CS BL                                                             1
Name: count, dtype: int64

In [74]:
def is_informative_solution(solution):
    solution = str(solution).strip().lower()

    generic_phrases = {
        "resolved",
        "resolved.",
        "resolved,",
        "solved",
        "done",
        "done.",
        "fixed",
        "fixed1",
        "closed",
        "granted",
        "issue fixed",
        "issue solved",
        "problem solved",
        "necessary done.",
        "necessary done",
        "necessary done.",
        "necessaey done.",
        "duplicate",
        "duplicated"
    }

    return solution not in generic_phrases


local_2025["informative_solution"] = (
    local_2025["Solution"]
    .apply(is_informative_solution)
)

print(
    local_2025["informative_solution"].value_counts()
)

informative_solution
False    1287
True      458
Name: count, dtype: int64

In [24]:
top_indices_10 = similarities.argsort()[-10:][::-1]

results_10 = local_2025.iloc[top_indices_10][
    ["Number", "Short Description", "Solution", "informative_solution"]
].copy()

results_10["Similarity"] = similarities[top_indices_10]

print(results_10.to_string(index=False))

     Number                                                                                           Short Description                     Solution  informative_solution  Similarity
INC66808943                                                                                       Probleme d'impression                        Fixed                 False    0.688697
INC67011539                                                                                              Printing issue                       solved                 False    0.683536
INC66441487                                                                                     Print issue in GCA7 app TN Provider is working on it                  True    0.682678
INC64352664                                                                                               Printer Issue                     Resolved                 False    0.672607
INC69346363                                                                                               Printer Issue                 Issue solved                 False    0.663776
INC69977541 MA - EXP - Delivery sheets are taking a long time to print from GCA, taking some times more than 5 minutes.             Duplicate ticket                  True    0.658370
INC70677235                                                                                 MA - EXP - printer abandant                     Resolved                 False    0.657787
INC69711341                                                                                                     Printer                    Resolved                  False    0.657712
INC70501491                 MA - EXP - probléme d'impression de l'imprimante de Mme.asmae l'inspecteur de la douane TNG                     resolved                 False    0.656133
INC65933037                                                                                     Problème imprimante MAG                     Resolved                 False    0.652443

In [82]:
results_10["recommendation_score"] = (
    results_10["Similarity"]
    + results_10["informative_solution"].astype(float) * 0.05
)

results_10 = results_10.sort_values(
    "recommendation_score",
    ascending=False
)

print(
    results_10[
        [
            "Number",
            "Short Description",
            "Solution",
            "Similarity",
            "informative_solution",
            "recommendation_score"
        ]
    ].to_string(index=False)
)

     Number                                                                                           Short Description                     Solution  Similarity  informative_solution  recommendation_score
INC66441487                                                                                     Print issue in GCA7 app TN Provider is working on it    0.682678                  True              0.732678
INC69977541 MA - EXP - Delivery sheets are taking a long time to print from GCA, taking some times more than 5 minutes.             Duplicate ticket    0.658370                  True              0.708370
INC66808943                                                                                       Probleme d'impression                        Fixed    0.688697                 False              0.688697
INC67011539                                                                                              Printing issue                       solved    0.683536                 False              0.683536
INC64352664                                                                                               Printer Issue                     Resolved    0.672607                 False              0.672607
INC69346363                                                                                               Printer Issue                 Issue solved    0.663776                 False              0.663776
INC70677235                                                                                 MA - EXP - printer abandant                     Resolved    0.657787                 False              0.657787
INC69711341                                                                                                     Printer                    Resolved     0.657712                 False              0.657712
INC70501491                 MA - EXP - probléme d'impression de l'imprimante de Mme.asmae l'inspecteur de la douane TNG                     resolved    0.656133                 False              0.656133
INC65933037                                                                                     Problème imprimante MAG                     Resolved    0.652443                 False              0.652443

In [78]:
non_recommendable_solutions = {
    "duplicate",
    "duplicated",
    "no response from user",
    "regional ticket opened",
    "a new ticket has been raised",
    "data provided",
    "inc69065461"
}

print(
    "Nombre de réponses non recommandables :",
    len(non_recommendable_solutions)
)

Nombre de réponses non recommandables : 7

In [79]:
def is_recommendable_solution(solution):
    solution = str(solution).strip().lower()

    if solution in generic_solutions:
        return False

    if solution in non_recommendable_solutions:
        return False

    return True

In [80]:
local_2025["recommendable_solution"] = (
    local_2025["Solution"]
    .apply(is_recommendable_solution)
)

print(
    local_2025["recommendable_solution"].value_counts()
)

recommendable_solution
False    1236
True      509
Name: count, dtype: int64

In [83]:
results_10["recommendable_solution"] = (
    results_10["Number"]
    .map(
        local_2025.set_index("Number")["recommendable_solution"]
    )
)

results_10["recommendation_score"] = (
    results_10["Similarity"]
    + results_10["recommendable_solution"].astype(float) * 0.05
)

results_10 = results_10.sort_values(
    "recommendation_score",
    ascending=False
)

print(
    results_10[
        [
            "Number",
            "Short Description",
            "Solution",
            "Similarity",
            "recommendable_solution",
            "recommendation_score"
        ]
    ].to_string(index=False)
)

     Number                                                                                           Short Description                     Solution  Similarity  recommendable_solution  recommendation_score
INC66441487                                                                                     Print issue in GCA7 app TN Provider is working on it    0.682678                    True              0.732678
INC69977541 MA - EXP - Delivery sheets are taking a long time to print from GCA, taking some times more than 5 minutes.             Duplicate ticket    0.658370                    True              0.708370
INC66808943                                                                                       Probleme d'impression                        Fixed    0.688697                   False              0.688697
INC67011539                                                                                              Printing issue                       solved    0.683536                   False              0.683536
INC64352664                                                                                               Printer Issue                     Resolved    0.672607                   False              0.672607
INC69346363                                                                                               Printer Issue                 Issue solved    0.663776                   False              0.663776
INC70677235                                                                                 MA - EXP - printer abandant                     Resolved    0.657787                   False              0.657787
INC69711341                                                                                                     Printer                    Resolved     0.657712                   False              0.657712
INC70501491                 MA - EXP - probléme d'impression de l'imprimante de Mme.asmae l'inspecteur de la douane TNG                     resolved    0.656133                   False              0.656133
INC65933037                                                                                     Problème imprimante MAG                     Resolved    0.652443                   False              0.652443

In [84]:
local_2025["recommendable_solution"] = (
    local_2025["Solution"]
    .apply(is_recommendable_solution)
)

print(
    local_2025.loc[
        local_2025["Number"].isin(top_indices_10),
        ["Number", "Solution", "recommendable_solution"]
    ].to_string(index=False)
)

Empty DataFrame
Columns: [Number, Solution, recommendable_solution]
Index: []

In [85]:
top_tickets = local_2025.iloc[top_indices_10].copy()

top_tickets["recommendable_solution"] = (
    top_tickets["Solution"]
    .apply(is_recommendable_solution)
)

print(
    top_tickets[
        ["Number", "Short Description", "Solution", "recommendable_solution"]
    ].to_string(index=False)
)

     Number                                                                                           Short Description                     Solution  recommendable_solution
INC66808943                                                                                       Probleme d'impression                        Fixed                   False
INC67011539                                                                                              Printing issue                       solved                   False
INC66441487                                                                                     Print issue in GCA7 app TN Provider is working on it                    True
INC64352664                                                                                               Printer Issue                     Resolved                   False
INC69346363                                                                                               Printer Issue                 Issue solved                   False
INC69977541 MA - EXP - Delivery sheets are taking a long time to print from GCA, taking some times more than 5 minutes.             Duplicate ticket                    True
INC70677235                                                                                 MA - EXP - printer abandant                     Resolved                   False
INC69711341                                                                                                     Printer                    Resolved                    False
INC70501491                 MA - EXP - probléme d'impression de l'imprimante de Mme.asmae l'inspecteur de la douane TNG                     resolved                   False
INC65933037                                                                                     Problème imprimante MAG                     Resolved                   False

In [86]:
generic_solutions = {
    "resolved",
    "resolved.",
    "resolved,",
    "solved",
    "done",
    "done.",
    "fixed",
    "fixed1",
    "closed",
    "granted",
    "issue fixed",
    "issue solved",
    "problem solved",
    "necessary done.",
    "necessary done",
    "necessaey done.",
}

non_recommendable_solutions = {
    "duplicate",
    "duplicated",
    "no response from user",
    "regional ticket opened",
    "a new ticket has been raised",
    "data provided",
    "inc69065461"
}


def is_recommendable_solution(solution):
    solution = str(solution).strip().lower()

    if solution in generic_solutions:
        return False

    if solution in non_recommendable_solutions:
        return False

    return True

In [87]:
print(is_recommendable_solution("Duplicate ticket"))
print(is_recommendable_solution("Fixed"))
print(is_recommendable_solution("TN Provider is working on it"))

True
False
True

In [88]:
top_tickets["recommendable_solution"] = (
    top_tickets["Solution"]
    .apply(is_recommendable_solution)
)

print(
    top_tickets[
        ["Number", "Short Description", "Solution", "recommendable_solution"]
    ].to_string(index=False)
)

     Number                                                                                           Short Description                     Solution  recommendable_solution
INC66808943                                                                                       Probleme d'impression                        Fixed                   False
INC67011539                                                                                              Printing issue                       solved                   False
INC66441487                                                                                     Print issue in GCA7 app TN Provider is working on it                    True
INC64352664                                                                                               Printer Issue                     Resolved                   False
INC69346363                                                                                               Printer Issue                 Issue solved                   False
INC69977541 MA - EXP - Delivery sheets are taking a long time to print from GCA, taking some times more than 5 minutes.             Duplicate ticket                    True
INC70677235                                                                                 MA - EXP - printer abandant                     Resolved                   False
INC69711341                                                                                                     Printer                    Resolved                    False
INC70501491                 MA - EXP - probléme d'impression de l'imprimante de Mme.asmae l'inspecteur de la douane TNG                     resolved                   False
INC65933037                                                                                     Problème imprimante MAG                     Resolved                   False

In [89]:
def is_recommendable_solution(solution):
    solution = str(solution).strip().lower()

    # Solutions génériques
    generic_keywords = [
        "resolved",
        "solved",
        "done",
        "fixed",
        "closed",
        "granted",
        "necessary done",
        "issue fixed",
        "issue solved",
        "problem solved"
    ]

    # Réponses administratives / non techniques
    non_recommendable_keywords = [
        "duplicate",
        "duplicated",
        "no response from user",
        "regional ticket opened",
        "new ticket has been raised",
        "data provided"
    ]

    # Si un mot-clé générique est présent
    for keyword in generic_keywords:
        if solution == keyword or solution.startswith(keyword):
            return False

    # Si une réponse administrative est présente
    for keyword in non_recommendable_keywords:
        if keyword in solution:
            return False

    return True

In [90]:
print(is_recommendable_solution("Duplicate ticket"))
print(is_recommendable_solution("Fixed"))
print(is_recommendable_solution("TN Provider is working on it"))
print(is_recommendable_solution("Resolved, ticket created"))

False
False
True
False

In [91]:
top_tickets["recommendable_solution"] = (
    top_tickets["Solution"]
    .apply(is_recommendable_solution)
)

print(
    top_tickets[
        ["Number", "Short Description", "Solution", "recommendable_solution"]
    ].to_string(index=False)
)

     Number                                                                                           Short Description                     Solution  recommendable_solution
INC66808943                                                                                       Probleme d'impression                        Fixed                   False
INC67011539                                                                                              Printing issue                       solved                   False
INC66441487                                                                                     Print issue in GCA7 app TN Provider is working on it                    True
INC64352664                                                                                               Printer Issue                     Resolved                   False
INC69346363                                                                                               Printer Issue                 Issue solved                   False
INC69977541 MA - EXP - Delivery sheets are taking a long time to print from GCA, taking some times more than 5 minutes.             Duplicate ticket                   False
INC70677235                                                                                 MA - EXP - printer abandant                     Resolved                   False
INC69711341                                                                                                     Printer                    Resolved                    False
INC70501491                 MA - EXP - probléme d'impression de l'imprimante de Mme.asmae l'inspecteur de la douane TNG                     resolved                   False
INC65933037                                                                                     Problème imprimante MAG                     Resolved                   False

In [92]:
def recommend_solution(new_ticket, top_k=10):

    # 1. Transformer le nouveau ticket en embedding
    new_embedding = model.encode([new_ticket])

    # 2. Calculer la similarité avec tous les tickets historiques
    similarities = cosine_similarity(
        new_embedding,
        embeddings
    )[0]

    # 3. Prendre les top_k tickets les plus similaires
    top_indices = similarities.argsort()[-top_k:][::-1]

    # 4. Récupérer les tickets
    candidates = local_2025.iloc[top_indices].copy()

    # 5. Ajouter la similarité
    candidates["Similarity"] = similarities[top_indices]

    # 6. Vérifier si la solution est recommandable
    candidates["recommendable_solution"] = (
        candidates["Solution"]
        .apply(is_recommendable_solution)
    )

    # 7. Garder uniquement les solutions recommandables
    recommended = candidates[
        candidates["recommendable_solution"]
    ].copy()

    # 8. Si aucune solution exploitable n'est trouvée
    if recommended.empty:
        return None, candidates

    # 9. Prendre le ticket avec la meilleure similarité
    best = recommended.sort_values(
        "Similarity",
        ascending=False
    ).iloc[0]

    return best, candidates

In [93]:
new_ticket = "MA - EXP - problème d'impression dans GCA"

best, candidates = recommend_solution(new_ticket)

print("Ticket historique :", best["Number"])
print("Description       :", best["Short Description"])
print("Solution           :", best["Solution"])
print("Similarité         :", round(best["Similarity"], 4))

Ticket historique : INC66441487
Description       : Print issue in GCA7 app
Solution           : TN Provider is working on it
Similarité         : 0.6827

In [94]:
def recommend_solutions(new_ticket, top_k=10, n_recommendations=3):

    # Embedding du nouveau ticket
    new_embedding = model.encode([new_ticket])

    # Similarité avec les tickets historiques
    similarities = cosine_similarity(
        new_embedding,
        embeddings
    )[0]

    # Top K candidats
    top_indices = similarities.argsort()[-top_k:][::-1]

    candidates = local_2025.iloc[top_indices].copy()

    # Ajouter le score de similarité
    candidates["Similarity"] = similarities[top_indices]

    # Identifier les solutions recommandables
    candidates["recommendable_solution"] = (
        candidates["Solution"]
        .apply(is_recommendable_solution)
    )

    # Garder uniquement les solutions exploitables
    recommended = candidates[
        candidates["recommendable_solution"]
    ].copy()

    # Trier par similarité
    recommended = recommended.sort_values(
        "Similarity",
        ascending=False
    )

    # Retourner les N meilleures
    return recommended.head(n_recommendations)

In [95]:
def recommend_solutions(new_ticket, top_k=10, n_recommendations=3):

    # Embedding du nouveau ticket
    new_embedding = model.encode([new_ticket])

    # Similarité avec les tickets historiques
    similarities = cosine_similarity(
        new_embedding,
        embeddings
    )[0]

    # Top K candidats
    top_indices = similarities.argsort()[-top_k:][::-1]

    candidates = local_2025.iloc[top_indices].copy()

    # Ajouter le score de similarité
    candidates["Similarity"] = similarities[top_indices]

    # Identifier les solutions recommandables
    candidates["recommendable_solution"] = (
        candidates["Solution"]
        .apply(is_recommendable_solution)
    )

    # Garder uniquement les solutions exploitables
    recommended = candidates[
        candidates["recommendable_solution"]
    ].copy()

    # Trier par similarité
    recommended = recommended.sort_values(
        "Similarity",
        ascending=False
    )

    # Retourner les N meilleures
    return recommended.head(n_recommendations)

In [96]:
new_ticket = "MA - EXP - problème d'impression dans GCA"

recommendations = recommend_solutions(new_ticket)

print(
    recommendations[
        [
            "Number",
            "Short Description",
            "Solution",
            "Similarity"
        ]
    ].to_string(index=False)
)

     Number       Short Description                     Solution  Similarity
INC66441487 Print issue in GCA7 app TN Provider is working on it    0.682678

In [97]:
recommendations = recommend_solutions(
    new_ticket,
    top_k=50,
    n_recommendations=3
)

print(
    recommendations[
        [
            "Number",
            "Short Description",
            "Solution",
            "Similarity"
        ]
    ].to_string(index=False)
)

     Number                                      Short Description                                                                                                                                                                                 Solution  Similarity
INC66441487                                Print issue in GCA7 app                                                                                                                                                             TN Provider is working on it    0.682678
INC67202503 MA - EXP - GOPS printer not connecting with GCA server                                                                                                                                         Need to close the ticket to avoid any TRT impact    0.649372
INC64575885                          MA - EXP - Imprimante empanne Bonjour, \n\nJe vous informe qu'une demande de changement d'imprimantes seras faites le plus tot possible pour changer la machine une fois pour tout , merci pour votre comprehension.\n    0.589952

In [98]:
recommendations = recommend_solutions(
    new_ticket,
    top_k=50,
    n_recommendations=10
)

print(
    recommendations[
        [
            "Number",
            "Short Description",
            "Solution",
            "Similarity"
        ]
    ].to_string(index=False)
)

     Number                                      Short Description                                                                                                                                                                                 Solution  Similarity
INC66441487                                Print issue in GCA7 app                                                                                                                                                             TN Provider is working on it    0.682678
INC67202503 MA - EXP - GOPS printer not connecting with GCA server                                                                                                                                         Need to close the ticket to avoid any TRT impact    0.649372
INC64575885                          MA - EXP - Imprimante empanne Bonjour, \n\nJe vous informe qu'une demande de changement d'imprimantes seras faites le plus tot possible pour changer la machine une fois pour tout , merci pour votre comprehension.\n    0.589952

In [99]:

local_2025["solution_text"] = (
    local_2025["Solution"]
    .fillna("")
    .astype(str)
    .str.strip()
)

print("Nombre de solutions :", len(local_2025))
print("Solutions vides :", (local_2025["solution_text"] == "").sum())

print(
    local_2025[["Number", "Solution", "solution_text"]]
    .head()
)

Nombre de solutions : 1745
Solutions vides : 0
        Number                      Solution                 solution_text
2  INC67542407                        Closed                        Closed
3  INC63115290              Cancelled by NOC              Cancelled by NOC
5  INC66441487  TN Provider is working on it  TN Provider is working on it
6  INC64928937                      resolved                      resolved
7  INC64305092                      Resolved                      Resolved

In [100]:

solution_embeddings = model.encode(
    local_2025["solution_text"].tolist(),
    show_progress_bar=True
)

print(solution_embeddings.shape)

Batches: 100%|██████████| 55/55 [00:17<00:00,  3.14it/s]

(1745, 384)

In [101]:

new_embedding = model.encode([new_ticket])

solution_similarities = cosine_similarity(
    new_embedding,
    solution_embeddings
)[0]

print(solution_similarities.shape)

(1745,)

In [102]:

ticket_similarities = cosine_similarity(
    new_embedding,
    embeddings
)[0]

combined_score = (
        0.70 * ticket_similarities
        + 0.30 * solution_similarities
)

print(combined_score.shape)

(1745,)

In [103]:

top_indices = combined_score.argsort()[-10:][::-1]

final_candidates = local_2025.iloc[top_indices].copy()

final_candidates["Ticket_Similarity"] = (
    ticket_similarities[top_indices]
)

final_candidates["Solution_Similarity"] = (
    solution_similarities[top_indices]
)

final_candidates["Combined_Score"] = (
    combined_score[top_indices]
)

print(
    final_candidates[
        [
            "Number",
            "Short Description",
            "Solution",
            "Ticket_Similarity",
            "Solution_Similarity",
            "Combined_Score"
        ]
    ].to_string(index=False)
)

     Number                                                                                           Short Description                                                                                                                                                                                 Solution  Ticket_Similarity  Solution_Similarity  Combined_Score
INC64575885                                                                               MA - EXP - Imprimante empanne Bonjour, \n\nJe vous informe qu'une demande de changement d'imprimantes seras faites le plus tot possible pour changer la machine une fois pour tout , merci pour votre comprehension.\n           0.589952             0.411796        0.536505
INC65340881                                                              MA - EXP - Panne de l'imprimante RICOH OPS 201                                                                                                                                  Resolved , l'imprimantes seras changer des que possible           0.572221             0.423145        0.527498
INC64635432                                                                   MA - EXP - The printer is out of service.                                                                                                                                                                        Fixed by supplier           0.645548             0.245047        0.525398
INC69346363                                                                                               Printer Issue                                                                                                                                                                             Issue solved           0.663776             0.181198        0.519003
INC66441487                                                                                     Print issue in GCA7 app                                                                                                                                                             TN Provider is working on it           0.682678             0.136891        0.518942
INC66808943                                                                                       Probleme d'impression                                                                                                                                                                                    Fixed           0.688697             0.096818        0.511133
INC67011539                                                                                              Printing issue                                                                                                                                                                                   solved           0.683536             0.076125        0.501313
INC65033264                                      MA - EXP - DELAY TO PRINT THE DELIVERY SHEET FROM GCA TO RICOH PRINTER                                                                                                                                                                  Printer will be changed           0.496539             0.498460        0.497115
INC64352664                                                                                               Printer Issue                                                                                                                                                                                 Resolved           0.672607             0.079726        0.494743
INC69977541 MA - EXP - Delivery sheets are taking a long time to print from GCA, taking some times more than 5 minutes.                                                                                                                                                                         Duplicate ticket           0.658370             0.112178        0.494512

In [104]:

def get_solution_recommendations(new_ticket, top_k=50, n_recommendations=5):
    # Embedding du nouveau ticket
    new_embedding = model.encode([new_ticket])

    # Similarité avec tous les tickets
    similarities = cosine_similarity(
        new_embedding,
        embeddings
    )[0]

    # Top K tickets similaires
    top_indices = similarities.argsort()[-top_k:][::-1]

    candidates = local_2025.iloc[top_indices].copy()

    candidates["Similarity"] = similarities[top_indices]

    # Filtrer les solutions non recommandables
    candidates["recommendable_solution"] = (
        candidates["Solution"]
        .apply(is_recommendable_solution)
    )

    candidates = candidates[
        candidates["recommendable_solution"]
    ].copy()

    # Trier par similarité du ticket
    candidates = candidates.sort_values(
        "Similarity",
        ascending=False
    )

    return candidates.head(n_recommendations)

In [106]:

recommendations = get_solution_recommendations(
    new_ticket,
    top_k=50,
    n_recommendations=5
)

print(
    recommendations[
        [
            "Number",
            "Short Description",
            "Solution",
            "Similarity"
        ]
    ].to_string(index=False)
)

     Number                                      Short Description                                                                                                                                                                                 Solution  Similarity
INC66441487                                Print issue in GCA7 app                                                                                                                                                             TN Provider is working on it    0.682678
INC67202503 MA - EXP - GOPS printer not connecting with GCA server                                                                                                                                         Need to close the ticket to avoid any TRT impact    0.649372
INC64575885                          MA - EXP - Imprimante empanne Bonjour, \n\nJe vous informe qu'une demande de changement d'imprimantes seras faites le plus tot possible pour changer la machine une fois pour tout , merci pour votre comprehension.\n    0.589952

In [107]:

def classify_solution(solution):
    solution = str(solution).strip().lower()

    generic_keywords = [
        "resolved",
        "solved",
        "done",
        "fixed",
        "closed",
        "granted",
        "necessary done",
        "issue fixed",
        "issue solved",
        "problem solved"
    ]

    administrative_keywords = [
        "duplicate",
        "duplicated",
        "close the ticket",
        "ticket to avoid",
        "no response from user",
        "regional ticket opened",
        "new ticket has been raised",
        "a new ticket has been raised",
        "data provided"
    ]

    for keyword in generic_keywords:
        if solution == keyword or solution.startswith(keyword):
            return "GENERIC"

    for keyword in administrative_keywords:
        if keyword in solution:
            return "ADMINISTRATIVE"

    return "ACTIONABLE"

In [108]:

test_solutions = [
    "Resolved",
    "Fixed",
    "Duplicate ticket",
    "Need to close the ticket to avoid any TRT impact",
    "TN Provider is working on it",
    "Printer will be changed",
    "Fixed by supplier"
]

for solution in test_solutions:
    print(solution, "→", classify_solution(solution))

Resolved → GENERIC
Fixed → GENERIC
Duplicate ticket → ADMINISTRATIVE
Need to close the ticket to avoid any TRT impact → ADMINISTRATIVE
TN Provider is working on it → ACTIONABLE
Printer will be changed → ACTIONABLE
Fixed by supplier → GENERIC

In [109]:

def classify_solution(solution):
    solution = str(solution).strip().lower()

    generic_solutions = {
        "resolved",
        "resolved.",
        "resolved,",
        "solved",
        "solved.",
        "done",
        "done.",
        "fixed",
        "fixed.",
        "closed",
        "granted",
        "necessary done",
        "necessary done.",
        "necessaey done.",
        "issue fixed",
        "issue solved",
        "problem solved"
    }

    administrative_keywords = [
        "duplicate",
        "duplicated",
        "close the ticket",
        "ticket to avoid",
        "no response from user",
        "regional ticket opened",
        "new ticket has been raised",
        "a new ticket has been raised",
        "data provided"
    ]

    # 1. Solution exactement générique
    if solution in generic_solutions:
        return "GENERIC"

    # 2. Solution administrative
    for keyword in administrative_keywords:
        if keyword in solution:
            return "ADMINISTRATIVE"

    # 3. Tout le reste est considéré comme actionnable
    return "ACTIONABLE"

In [110]:

for solution in test_solutions:
    print(solution, "→", classify_solution(solution))

Resolved → GENERIC
Fixed → GENERIC
Duplicate ticket → ADMINISTRATIVE
Need to close the ticket to avoid any TRT impact → ADMINISTRATIVE
TN Provider is working on it → ACTIONABLE
Printer will be changed → ACTIONABLE
Fixed by supplier → ACTIONABLE

In [111]:
local_2025["solution_type"] = (
    local_2025["Solution"]
    .apply(classify_solution)
)

print(local_2025["solution_type"].value_counts())

solution_type
GENERIC           1279
ACTIONABLE         440
ADMINISTRATIVE      26
Name: count, dtype: int64

In [112]:

def classify_solution(solution):
    solution = str(solution).strip().lower()

    # Réponses administratives
    administrative_keywords = [
        "duplicate",
        "duplicated",
        "close the ticket",
        "ticket to avoid",
        "no response from user",
        "regional ticket opened",
        "new ticket has been raised",
        "a new ticket has been raised",
        "data provided"
    ]

    # Vérifier d'abord les réponses administratives
    for keyword in administrative_keywords:
        if keyword in solution:
            return "ADMINISTRATIVE"

    # Solutions réellement génériques
    generic_solutions = {
        "resolved",
        "resolved.",
        "resolved,",
        "solved",
        "solved.",
        "done",
        "done.",
        "fixed",
        "fixed.",
        "closed",
        "granted",
        "necessary done",
        "necessary done.",
        "necessaey done.",
        "issue fixed",
        "issue solved",
        "problem solved"
    }

    # Seulement les correspondances exactes
    if solution in generic_solutions:
        return "GENERIC"

    # Tout le reste
    return "ACTIONABLE"

In [113]:

test_solutions = [
    "Resolved",
    "Fixed",
    "Duplicate ticket",
    "Need to close the ticket to avoid any TRT impact",
    "TN Provider is working on it",
    "Printer will be changed",
    "Fixed by supplier"
]

for solution in test_solutions:
    print(solution, "→", classify_solution(solution))

Resolved → GENERIC
Fixed → GENERIC
Duplicate ticket → ADMINISTRATIVE
Need to close the ticket to avoid any TRT impact → ADMINISTRATIVE
TN Provider is working on it → ACTIONABLE
Printer will be changed → ACTIONABLE
Fixed by supplier → ACTIONABLE

In [114]:

local_2025["solution_type"] = (
    local_2025["Solution"]
    .apply(classify_solution)
)

print(local_2025["solution_type"].value_counts())

solution_type
GENERIC           1279
ACTIONABLE         440
ADMINISTRATIVE      26
Name: count, dtype: int64

In [116]:

def get_solution_recommendations(new_ticket, top_k=50, n_recommendations=5):
    # 1. Embedding du nouveau ticket
    new_embedding = model.encode([new_ticket])

    # 2. Similarité avec tous les tickets historiques
    similarities = cosine_similarity(
        new_embedding,
        embeddings
    )[0]

    # 3. Prendre les TOP K tickets les plus similaires
    top_indices = similarities.argsort()[-top_k:][::-1]

    # 4. Récupérer les tickets
    candidates = local_2025.iloc[top_indices].copy()

    # 5. Ajouter la similarité
    candidates["Similarity"] = similarities[top_indices]

    # 6. Garder uniquement les solutions ACTIONABLE
    candidates = candidates[
        candidates["solution_type"] == "ACTIONABLE"
        ].copy()

    # 7. Trier par similarité
    candidates = candidates.sort_values(
        "Similarity",
        ascending=False
    )

    # 8. Retourner les meilleures recommandations
    return candidates.head(n_recommendations)

In [117]:

new_ticket = "MA - EXP - problème d'impression dans GCA"

recommendations = get_solution_recommendations(
    new_ticket,
    top_k=50,
    n_recommendations=5
)

print(
    recommendations[
        [
            "Number",
            "Short Description",
            "Solution",
            "Similarity",
            "solution_type"
        ]
    ].to_string(index=False)
)

     Number                              Short Description                                                                                                                                                                                 Solution  Similarity solution_type
INC66441487                        Print issue in GCA7 app                                                                                                                                                             TN Provider is working on it    0.682678    ACTIONABLE
INC64635432      MA - EXP - The printer is out of service.                                                                                                                                                                        Fixed by supplier    0.645548    ACTIONABLE
INC64575885                  MA - EXP - Imprimante empanne Bonjour, \n\nJe vous informe qu'une demande de changement d'imprimantes seras faites le plus tot possible pour changer la machine une fois pour tout , merci pour votre comprehension.\n    0.589952    ACTIONABLE
INC71371384            MA - EXP - IMPRESSION ILLISABLE xos                                                                                                                                      resolved demande a été envoyer hier au prestataire     0.576565    ACTIONABLE
INC65340881 MA - EXP - Panne de l'imprimante RICOH OPS 201                                                                                                                                  Resolved , l'imprimantes seras changer des que possible    0.572221    ACTIONABLE

In [118]:

def solution_quality(solution_type):
    if solution_type == "ACTIONABLE":
        return 1
    return 0


local_2025["solution_quality"] = (
    local_2025["solution_type"]
    .apply(solution_quality)
)

print(
    local_2025[
        ["Solution", "solution_type", "solution_quality"]
    ].head(20).to_string(index=False)
)

                                                                             Solution solution_type  solution_quality
                                                                               Closed       GENERIC                 0
                                                                     Cancelled by NOC    ACTIONABLE                 1
                                                         TN Provider is working on it    ACTIONABLE                 1
                                                                             resolved       GENERIC                 0
                                                                             Resolved       GENERIC                 0
                                                                             Resolved       GENERIC                 0
                                                                             Resolved       GENERIC                 0
          Resolved, Comme mentionner merci de remplir le fichier excel corrrectement.    ACTIONABLE                 1
                                                                             Resolved       GENERIC                 0
                                                                Resolved  INC63245892    ACTIONABLE                 1
                                                                             Resolved       GENERIC                 0
                                   Closed\nl'accès à SPAK est géré par l'équipe CS BL    ACTIONABLE                 1
Je vous informe qu'un technicien se rendra à l'agence dans les plus brefs délais.\n\n    ACTIONABLE                 1
                                                                             Resolved       GENERIC                 0
                  Resolved, merci de contacter l'equipe RH pour la creation du copmte    ACTIONABLE                 1
                                                                             Resolved       GENERIC                 0
          la demande a été approuvé.\nil aura son accès dans 72h.\nMerci de patienter    ACTIONABLE                 1
                                                                             Resolved       GENERIC                 0
                                                                               solved       GENERIC                 0
                                           Resolved, merci de me contacter 0663570102    ACTIONABLE                 1

In [119]:

local_2025["solution_type"] = (
    local_2025["Solution"]
    .apply(classify_solution)
)

local_2025["solution_quality"] = (
    local_2025["solution_type"]
    .apply(solution_quality)
)

print(local_2025["solution_type"].value_counts())

solution_type
GENERIC           1279
ACTIONABLE         440
ADMINISTRATIVE      26
Name: count, dtype: int64

In [120]:

examples = [
    "Cancelled by NOC",
    "Resolved",
    "Fixed",
    "Resolved INC63245892",
    "TN Provider is working on it",
    "Fixed by supplier",
    "Printer will be changed",
    "Resolved, merci de contacter l'equipe RH pour la creation du copmte"
]

for x in examples:
    print(x, "→", classify_solution(x))

Cancelled by NOC → ACTIONABLE
Resolved → GENERIC
Fixed → GENERIC
Resolved INC63245892 → ACTIONABLE
TN Provider is working on it → ACTIONABLE
Fixed by supplier → ACTIONABLE
Printer will be changed → ACTIONABLE
Resolved, merci de contacter l'equipe RH pour la creation du copmte → ACTIONABLE

In [121]:

def classify_solution(solution):
    solution = str(solution).strip().lower()

    # 1. Solutions administratives
    administrative_keywords = [
        "duplicate",
        "duplicated",
        "close the ticket",
        "ticket to avoid",
        "no response from user",
        "regional ticket opened",
        "new ticket has been raised",
        "a new ticket has been raised",
        "data provided",
        "cancelled",
        "cancelled by"
    ]

    for keyword in administrative_keywords:
        if keyword in solution:
            return "ADMINISTRATIVE"

    # 2. Solutions génériques exactes
    generic_solutions = {
        "resolved",
        "resolved.",
        "resolved,",
        "solved",
        "solved.",
        "done",
        "done.",
        "fixed",
        "fixed.",
        "closed",
        "closed.",
        "granted",
        "access granted",
        "access granted.",
        "necessary done",
        "necessary done.",
        "necessaey done.",
        "issue fixed",
        "issue solved",
        "problem solved"
    }

    if solution in generic_solutions:
        return "GENERIC"

    # 3. "Resolved" ou "Fixed" + référence de ticket
    if solution.startswith("resolved inc"):
        return "GENERIC"

    if solution.startswith("fixed inc"):
        return "GENERIC"

    # 4. Le reste
    return "ACTIONABLE"

In [122]:

for x in examples:
    print(x, "→", classify_solution(x))

Cancelled by NOC → ADMINISTRATIVE
Resolved → GENERIC
Fixed → GENERIC
Resolved INC63245892 → GENERIC
TN Provider is working on it → ACTIONABLE
Fixed by supplier → ACTIONABLE
Printer will be changed → ACTIONABLE
Resolved, merci de contacter l'equipe RH pour la creation du copmte → ACTIONABLE

In [123]:

local_2025["solution_type"] = (
    local_2025["Solution"]
    .apply(classify_solution)
)

local_2025["solution_quality"] = (
    local_2025["solution_type"]
    .apply(solution_quality)
)

print(local_2025["solution_type"].value_counts())

solution_type
GENERIC           1329
ACTIONABLE         388
ADMINISTRATIVE      28
Name: count, dtype: int64

In [124]:

print(
    local_2025[
        local_2025["solution_type"] == "ACTIONABLE"
        ][
        ["Number", "Short Description", "Solution"]
    ].head(20).to_string(index=False)
)

     Number                                                                                                                                                                                                                                               Short Description                                                                                                                                                 Solution
INC66441487                                                                                                                                                                                                                                         Print issue in GCA7 app                                                                                                                             TN Provider is working on it
INC68351930                                                                                                                                                                                                  MA - EXP - Demande d'acces  a NMIV pour l'agent  YASSINE AYMAZ                                                                              Resolved, Comme mentionner merci de remplir le fichier excel corrrectement.
INC63226953                                                                                                                                                                             MA - EXP - Demande d'acces a l'application NMIV pour l'agent : ABDELAZIZ EL IDRISSI                                                                                                                                    Resolved  INC63245892
INC71430606                                                                                                                                                                                                                       MA - EXP - Demande d'accer  a  SPARK LITE                                                                                                       Closed\nl'accès à SPAK est géré par l'équipe CS BL
INC62437717                                                                                                                                                                                                                          MA - EXP - bruit d'impression des docs                                                                    Je vous informe qu'un technicien se rendra à l'agence dans les plus brefs délais.\n\n
INC69843002                                                                                                                                                   MA - EXP - Demande d'acces aux applications OUT LOOK , OCNT , ECIS  en faveur du nouvel agent AHMED EL KHYATI                                                                                      Resolved, merci de contacter l'equipe RH pour la creation du copmte
INC66318677                                                                                                                                                            MA - EXP - Request for access to application Global Workflow Solution ( CAA ) for agent IMAD SLAOUNI                                                                              la demande a été approuvé.\nil aura son accès dans 72h.\nMerci de patienter
INC66934839                                                                                                                                                                                                         MA - EXP - les codes a barre du Labels export illisible                                                                                                               Resolved, merci de me contacter 0663570102
INC62438331                                                                                                                                                                                          MA - EXP - Demande d'acces a l'application PMT ( PJS Management Tool )                                                                                      Bonjour, \n\nUne demande a été faite INC62438408\n\nCordialement.\n
INC63226909                                                                                                                                                                                  MA - EXP - Demande d'acces a l'application NMIV  pour l'agent  :  IMAD SLAOUNI                                                                                                                                    resolved  INC63245892
INC71063760                                                                                                                                                                                                                             MA - EXP - besoin de webcam externe                                                                                                  Merci de voir avec votre manager pour faire la demande
INC63793741                                                                                                                                                                                 Issue executing Excel files (.xlsm) containing Macro & VBA in multiple desktops                                                                                                                                        New ticket opened
INC69214837                                                                                                                                                                                                                                  MA - EXP - DEMANDE D'ACCES DCE                                                                                                                                       DCE access granted
INC69214975                                                                                                                                                                                                                                MA - EXP - DEMANDE D'ACCES SPARK                                                                                                               Merci de demander l'acées a Hajar ousmouh
INC67200704                                                                                                                                                             MA - EXP - Bonjour, merci d'inclure NADA MAHDI nada.mahdi@dhl.com dans l' alias sales.maroc@dhl.com                                                                                                       Necessary done , \nchanges will be in PROD in 24h.
INC68181836                                                                                                                                                                                                                                       MA - EXP - MYDHL+ ESECURE                                                                                                                           Hello Anas,\n\nNecessary done.
INC71432868 EXP-MA: Bonjour,  Nous rencontrons des interruptions très fréquentes de la connexion Internet de l'agence depuis deux jours. Cette instabilité impacte les activités de l'ensemble des collaborateurs et perturbe le bon fonctionnement de nos opérations.  Nou                                                                                                               resolved, c'est un probleme d'electricité
INC67274222                                                                                                                                                                                                                MA - EXP - I HVE TO CONNECVT TO NEW MOBILE PHONE                                                                                                                 Resolved , merci de contacter 0663570102
INC64366158                                                                                                                                                                                                                    MA - EXP - Demande de pochettes pour scanner ce genre de demandes doivent être approuvé en premier par OPS manager et par la suite faire objet d'une demande via Basware\nMerci pour ta compréhension
INC64367724                                                                                                                                                                                                             MA - EXP - Demande de chargeur voiture pour scanner                                                                             The order should approved by the OPS manager and then submitted via Baseware

In [125]:

test_df = local_2025[
    local_2025["solution_type"] == "ACTIONABLE"
    ].sample(
    n=20,
    random_state=42
)

print("Nombre de tickets de test :", len(test_df))

print(
    test_df[
        ["Number", "Short Description", "Solution"]
    ].head(10).to_string(index=False)
)

Nombre de tickets de test : 20
     Number                                                        Short Description                                                                                                                                                                                                Solution
INC62683534                                                        MA - EXP - no bip                                                                                                                                                                          enable notifications and sound
INC67525729                                   MA - EXP - I RAN OUT OF PRINTING TONER                                                                                                                                                                       Le toner vous sera livrer demain.
INC67728547                                   TN - EXP - Modify MyDHL Administrators                                                                                                                                                             The Necessary changes are made successfuly.
INC71371384                                      MA - EXP - IMPRESSION ILLISABLE xos                                                                                                                                                     resolved demande a été envoyer hier au prestataire
INC68352009                                   MA - EXP - Demande d'accès au lien PMT                                                                                                                                                                   Access granted. pls check and confirm
INC67319161                                                           MA - EXP - DEC Hello Tarik,\n\nCustomer contacted today.\nThe DEC integration has already been completed, and a clarification meeting is scheduled for next Monday to start using the tool correctly.\n\nBest regards,
INC68950998 MA - EXP - SESSION CLOSED FOR EL MEHDI ROUROU ( elmehdi.rourou@dhl.com).                                                                                                                                                                          I will check and let you know.
INC69041800                                  MA - EXP - probléme de démarage outlook                                                                                                          Hello Badr,\n\nWe will configure a new profile on your outlook .\nAt the EOD.\n\nBest regards.
INC68158728                                   MA - EXP - Demande de deux câbles HDMI                                                                                                                                                                                                   Done,
INC68453863                MA - EXP - RF WAREHOUSE OUT SERVICE DUE TO DAMAGED SCREEN                                                                                             Your request to change the scanner was send to our head office. the remplacement will fellow the process.\n

In [126]:

def solution_match(recommended_solution, real_solution):
    """
    Vérifie si deux solutions sont suffisamment similaires.
    """
    recommended_solution = str(recommended_solution).strip().lower()
    real_solution = str(real_solution).strip().lower()

    # Correspondance exacte
    if recommended_solution == real_solution:
        return True

    # Une solution contient l'autre
    if (
            recommended_solution in real_solution
            or real_solution in recommended_solution
    ):
        return True

    return False

In [127]:

def evaluate_recommendations(test_df):
    results = []

    for _, row in test_df.iterrows():

        ticket = row["Short Description"]
        real_solution = row["Solution"]

        recommendations = get_solution_recommendations(
            ticket,
            top_k=50,
            n_recommendations=5
        )

        recommended_solutions = (
            recommendations["Solution"]
            .tolist()
        )

        top1 = False
        top3 = False
        top5 = False

        if len(recommended_solutions) >= 1:
            top1 = solution_match(
                recommended_solutions[0],
                real_solution
            )

        if len(recommended_solutions) >= 3:
            top3 = any(
                solution_match(
                    solution,
                    real_solution
                )
                for solution in recommended_solutions[:3]
            )

        if len(recommended_solutions) >= 5:
            top5 = any(
                solution_match(
                    solution,
                    real_solution
                )
                for solution in recommended_solutions[:5]
            )

        results.append({
            "Number": row["Number"],
            "Real_Solution": real_solution,
            "Top1": top1,
            "Top3": top3,
            "Top5": top5
        })

    return pd.DataFrame(results)

In [128]:

evaluation_results = evaluate_recommendations(test_df)

print(evaluation_results.to_string(index=False))

     Number                                                                                                                                                                                                              Real_Solution  Top1  Top3  Top5
INC62683534                                                                                                                                                                                             enable notifications and sound  True  True  True
INC67525729                                                                                                                                                                                          Le toner vous sera livrer demain.  True  True  True
INC67728547                                                                                                                                                                                The Necessary changes are made successfuly. False  True  True
INC71371384                                                                                                                                                                        resolved demande a été envoyer hier au prestataire   True  True  True
INC68352009                                                                                                                                                                                      Access granted. pls check and confirm  True  True  True
INC67319161                    Hello Tarik,\n\nCustomer contacted today.\nThe DEC integration has already been completed, and a clarification meeting is scheduled for next Monday to start using the tool correctly.\n\nBest regards, False  True  True
INC68950998                                                                                                                                                                                             I will check and let you know.  True  True  True
INC69041800                                                                                                                             Hello Badr,\n\nWe will configure a new profile on your outlook .\nAt the EOD.\n\nBest regards.  True  True  True
INC68158728                                                                                                                                                                                                                      Done,  True  True  True
INC68453863                                                                                                                Your request to change the scanner was send to our head office. the remplacement will fellow the process.\n  True  True  True
INC69191418                                                                                                                                                                                                  Requested to the provider  True  True  True
INC70412225                                                                                                                                                                                                                      close  True  True  True
INC67787876 Hello Maryam,\n\nAs explained several times, sometimes there are blocking files in the log. So, you just need to unplug the cables and restart the PC and the scanner, and everything will work properly.\n\nBest regards.  True  True  True
INC64533656                                                                                                                                                                                                 request has been submitted  True  True  True
INC69684458                                                                                                                                                                                               Done for TUN TRC 2 and TRC 3  True  True  True
INC69257946                                                                                                                                                                               Link to access GSA application send by email  True  True  True
INC68181836                                                                                                                                                                                             Hello Anas,\n\nNecessary done. False  True  True
INC62438121                                                                                                                                                        Bonjour, \n\nUne demande a été faite INC62438408\n\nCordialement.\n  True  True  True
INC70196867                                                                                                                                                                                                             Done; plz test False  True  True
INC66441487                                                                                                                                                                                               TN Provider is working on it  True  True  True

In [129]:

print("Top-1 :", round(evaluation_results["Top1"].mean() * 100, 2), "%")
print("Top-3 :", round(evaluation_results["Top3"].mean() * 100, 2), "%")
print("Top-5 :", round(evaluation_results["Top5"].mean() * 100, 2), "%")

Top-1 : 80.0 %
Top-3 : 100.0 %
Top-5 : 100.0 %

In [130]:

recommendations = get_solution_recommendations(
    new_ticket,
    top_k=50,
    n_recommendations=5
)

print(
    recommendations[
        [
            "Number",
            "Short Description",
            "Solution",
            "Similarity",
            "solution_type"
        ]
    ].to_string(index=False)
)

     Number                              Short Description                                                                                                                                                                                 Solution  Similarity solution_type
INC66441487                        Print issue in GCA7 app                                                                                                                                                             TN Provider is working on it    0.682678    ACTIONABLE
INC64635432      MA - EXP - The printer is out of service.                                                                                                                                                                        Fixed by supplier    0.645548    ACTIONABLE
INC64575885                  MA - EXP - Imprimante empanne Bonjour, \n\nJe vous informe qu'une demande de changement d'imprimantes seras faites le plus tot possible pour changer la machine une fois pour tout , merci pour votre comprehension.\n    0.589952    ACTIONABLE
INC71371384            MA - EXP - IMPRESSION ILLISABLE xos                                                                                                                                      resolved demande a été envoyer hier au prestataire     0.576565    ACTIONABLE
INC65340881 MA - EXP - Panne de l'imprimante RICOH OPS 201                                                                                                                                  Resolved , l'imprimantes seras changer des que possible    0.572221    ACTIONABLE

In [131]:

from sklearn.metrics.pairwise import cosine_similarity


def solution_similarity(solution1, solution2):
    emb1 = model.encode(
        [str(solution1)],
        normalize_embeddings=True
    )

    emb2 = model.encode(
        [str(solution2)],
        normalize_embeddings=True
    )

    return float(
        cosine_similarity(emb1, emb2)[0][0]
    )

In [132]:

print(
    solution_similarity(
        "Printer will be changed",
        "The printer will be replaced"
    )
)

0.8642702102661133

In [5]:
escalated_df = pd.read_excel("../data/Inc_escalated.xlsx")

print(escalated_df.shape)
print(escalated_df.columns.tolist())

FileNotFoundError: [Errno 2] No such file or directory: '../data/Inc_escalated.xlsx'

In [6]:
escalated_df = pd.read_excel("../data/Inc_registered by MAIT.xlsx")

print(escalated_df.shape)
print(escalated_df.columns.tolist())

FileNotFoundError: [Errno 2] No such file or directory: '../data/Inc_registered by MAIT.xlsx'

In [7]:
import pandas as pd

escalated_df = pd.read_excel("../data/Inc_registered by MAIT.xlsx")

print(escalated_df.shape)
print(escalated_df.columns.tolist())

FileNotFoundError: [Errno 2] No such file or directory: '../data/Inc_registered by MAIT.xlsx'

In [8]:
import os

print("Répertoire de travail :")
print(os.getcwd())

print("\nContenu du répertoire :")
print(os.listdir())

Répertoire de travail :
C:\Users\LENOVO\PycharmProjects\DHL_AI_Incident_Assistant\notebooks

Contenu du répertoire :
['01_data_preparation.ipynb']

In [12]:
from pathlib import Path

current_dir = Path.cwd()
data_dir = current_dir.parent / "data"

print("Répertoire actuel :")
print(current_dir)

print("\nDossier data attendu :")
print(data_dir)

print("\nLe dossier data existe :", data_dir.exists())

print("\nFichiers visibles dans data :")
if data_dir.exists():
    for file in data_dir.iterdir():
        print(repr(file.name))

Répertoire actuel :
C:\Users\LENOVO\PycharmProjects\DHL_AI_Incident_Assistant\notebooks

Dossier data attendu :
C:\Users\LENOVO\PycharmProjects\DHL_AI_Incident_Assistant\data

Le dossier data existe : True

Fichiers visibles dans data :
'Inc_registred by MAIT.xlsx'
'Inc_resolved by MAIT.xlsx'
'local_2025.pkl'
'local_2025_embeddings.npy'

In [10]:
import pandas as pd

escalated_df = pd.read_excel("../data/Inc_registred by MAIT.xlsx")

print(escalated_df.shape)
print(escalated_df.columns.tolist())

(430, 11)
['Number', 'Opened', 'Target Resolution Time (GMT)', 'Informed at', 'Incident Status', 'Caller', 'Assigned Group', 'Assignee', 'Short Description', 'Description', 'Solution']

In [11]:
# Vérification des tickets enregistrés / escaladés

print("Nombre de tickets :", len(escalated_df))
print()

print("Valeurs manquantes :")
print(escalated_df[
          ["Short Description", "Description", "Solution"]
      ].isna().sum())

print()
print("Solutions vides :")
print(
    (escalated_df["Solution"].fillna("").astype(str).str.strip() == "").sum()
)

print()
print("Nombre de solutions différentes :")
print(escalated_df["Solution"].nunique())

print()
print("Top des solutions :")
print(
    escalated_df["Solution"]
    .fillna("")
    .astype(str)
    .str.strip()
    .value_counts()
    .head(30)
)

Nombre de tickets : 430

Valeurs manquantes :
Short Description    0
Description          0
Solution             2
dtype: int64

Solutions vides :
2

Nombre de solutions différentes :
373

Top des solutions :
Solution
Dear colleague, because the required information needed to resolve your INC ticket was not provided by you, this ticket was set to status 'Resolved' by the Rule of 3 Automation in accordance with the Incident Management Process. However, if your issue persists, please contact your home Service Desk. Thank you.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  45
We have granted the Debrief access.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       3
completed                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 3

In [ ]:
print("Nombre de tickets :", len(escalated_df))

print("\nSolutions vides :")
print(
    escalated_df["Solution"]
    .isna()
    .sum()
)

print("\nDescriptions vides :")
print(
    escalated_df["Description"]
    .isna()
    .sum()
)

print("\nShort Description vides :")
print(
    escalated_df["Short Description"]
    .isna()
    .sum()
)

print("\nTypes de données :")
print(escalated_df.dtypes)

In [13]:
print(
    escalated_df[
        ["Number", "Short Description", "Solution"]
    ].head(20).to_string(index=False)
)

     Number                                                                                                               Short Description                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                Solution
INC63691050                                                                                                        URGENT : Issue MA ACCS !                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         ACCS server had been rebooted to switch from standby to active mode. \n\nConfirmed with caller and health checks has been successfully completed from our side.
INC65908914                                          Outlook Returns Undeliverable fatal error message when sending to some external emails                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 https://mxtoolbox.com/SuperTool.aspx?action=mx%3ai3e.ma&run=toolpage#\n\nConnecting to 52.117.100.166\n\nSendSMTPCommand: Timeout waiting for response after 15 seconds.\n\n- LookupServer [smtp:52.117.100.166] 17216ms\n\nName error; The domain 52.117.100.166 cannot be found.\nhttps://network-tools.webwiz.net/mail-server-test.htm\n\nReceiver's eMail server is down, please call your receiver to investigate.

In [14]:
print("Shape :", escalated_df.shape)

print("\nColonnes :")
print(escalated_df.columns.tolist())

print("\nPremières lignes :")
print(
    escalated_df[
        ["Number", "Short Description", "Description", "Solution"]
    ].head().to_string(index=False)
)

Shape : (430, 11)

Colonnes :
['Number', 'Opened', 'Target Resolution Time (GMT)', 'Informed at', 'Incident Status', 'Caller', 'Assigned Group', 'Assignee', 'Short Description', 'Description', 'Solution']

Premières lignes :
     Number                                                                      Short Description                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       Description                                                                                                                                                                                                                                                                                                                                                                                                                Solution
INC63691050                                                               URGENT : Issue MA ACCS !                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     Dear AVAYA support team,\n\nNeed your urgent support please to fix issue connecting to MACASACCS !\nmacasaccs.prg-dc.dhl.com not reached !!!\nAll MA call center phones are disconnected!\n\nThx for urgent help,\nAbdelilah.                                                                                                                                                                                                                                                         ACCS server had been rebooted to switch from standby to active mode. \n\nConfirmed with caller and health checks has been successfully completed from our side.
INC65908914 Outlook Returns Undeliverable fatal error message when sending to some external emails Hello,\n\nPlease note that we already opened a ticket INC65785263 about this issue, but closed because DHL.com admin unable to investigate further since issue is caused by the receiving server end !\nThe issue is impacting multiple receivers like :\nyoussef.oumzil@i3e.ma\ni.sbia@encom.ma\nsociete@maridior.ma\na.chabane@groupetadlaoui.ma\nchakib.elkanoun@sew-eurodrive.ma\nand others  ...\n\nWe need your help please to track the failed emails and see exactly the last end server blocking the email !\nthe issue is critical as it's touching communication with many of our customers!\nThx for your support\n\n-------------------------------------------------------------------------\nSome users are sending messages to external recipients but the following message returned without delivering the mail !\n\nAttaching an email example sent  to the external address <youssef.oumzil@i3e.ma> , but a fatal error is returned :\n-------------------------------------------------------------------------\n   ----- The following addresses had permanent fatal errors ----- <youssef.oumzil@i3e.ma>\n    (reason: 550 Host unknown)\n\n   ----- Transcript of session follows -----\n550 5.0.0 Host unknown\n-------------------------------------------------------------------------\n\nFYI the recipient <youssef.oumzil@i3e.ma> is receiving emails sent as test  from gmail!\n\nCould you please help to solve this issue !\n\nRgds,\nAbdelilah. https://mxtoolbox.com/SuperTool.aspx?action=mx%3ai3e.ma&run=toolpage#\n\nConnecting to 52.117.100.166\n\nSendSMTPCommand: Timeout waiting for response after 15 seconds.\n\n- LookupServer [smtp:52.117.100.166] 17216ms\n\nName error; The domain 52.117.100.166 cannot be found.\nhttps://network-tools.webwiz.net/mail-server-test.htm\n\nReceiver's eMail server is down, please call your receiver to investigate.
INC70092858                             QY0938 - 13/05/2026 - Data not transmitted from DCC to DCE                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   Hello DCE support team,\n\nURGENT - Please help to transmit data to DCE\nQY0938 - 13/05/2026 - Data exists in DCC but not transmitted to DCE\nAWBs Example :\n1017516124\n1041129865\n1104866711\n\nThe full list of non transmitted AWBs is attached in this ticket.\nplease note urgency!\n\nThx,\nAbdelilah.                                                                                                                                                                                                                                                                                                                                              Due to existing config in DCC for move script. Support will fix the issue.
INC67491363           Issue - ACS LTAs Data not transmitted from TGV to ACMEDI - QY938 CDG/CMN-301                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            Hello,\n\nCould you please check urgently !\nIssue - ACS LTAs Data not transmitted from TGV to ACMEDI - QY938 CDG/CMN-301\nScreenshots attached for more details.\n\nThx,\nAbdelilah.                                                                                                                                                                                                                                                                                                                                                                                        Regional error.\n\nSolved by user
INC62188298                                                   Need DCVS workstations configuration                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    Dear DCVS support team,\n\nNeed DCVS workstations configuration (Printer & Scale IP/Port)\nDCVS workstations :\nRBARBACOY01\nRBARBACOY02\n\nThx,\nAbdelilah.\n                                         in UMEX is configured:\n\nWorkstation RBARBACOY01\nRBARBACOY01_Spider 23.82.70.234:10002\nRBARBACOY01_Zebra 23.82.70.234:10006\n\nWorkstation RBARBACOY02\nRBARBACOY02_Spider 23.82.70.234:10003\nRBARBACOY02_printer 23.82.70.237:9100\n\nThere was a local issue, the cables were not plugged properly.\n\nAbdelilah solved the issue and confirmed we can close this ticket.

In [15]:
# Texte utilisé pour rechercher des tickets similaires

escalated_df["text_for_embedding"] = (
    escalated_df["Short Description"].fillna("").astype(str)
    + " "
    + escalated_df["Description"].fillna("").astype(str)
)

print("Nombre de tickets :", len(escalated_df))
print(
    "Textes vides :",
    (
        escalated_df["text_for_embedding"].str.strip() == ""
    ).sum()
)

print(
    escalated_df[
        ["Number", "text_for_embedding"]
    ].head(3).to_string(index=False)
)

Nombre de tickets : 430
Textes vides : 0
     Number                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       text_for_embedding
INC63691050                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   URGENT : Issue MA ACCS ! Dear AVAYA support team,\n\nNeed your urgent support please to fix issue connecting to MACASACCS !\nmacasaccs.prg-dc.dhl.com not reached !!!\nAll MA call center phones are disconnected!\n\nThx for urgent help,\nAbdelilah.
INC65908914 Outlook Returns Undeliverable fatal error message when sending to some external emails Hello,\n\nPlease note that we already opened a ticket INC65785263 about this issue, but closed because DHL.com admin unable to investigate further since issue is caused by the receiving server end !\nThe issue is impacting multiple receivers like :\nyoussef.oumzil@i3e.ma\ni.sbia@encom.ma\nsociete@maridior.ma\na.chabane@groupetadlaoui.ma\nchakib.elkanoun@sew-eurodrive.ma\nand others  ...\n\nWe need your help please to track the failed emails and see exactly the last end server blocking the email !\nthe issue is critical as it's touching communication with many of our customers!\nThx for your support\n\n-------------------------------------------------------------------------\nSome users are sending messages to external recipients but the following message returned without delivering the mail !\n\nAttaching an email example sent  to the external address <youssef.oumzil@i3e.ma> , but a fatal error is returned :\n-------------------------------------------------------------------------\n   ----- The following addresses had permanent fatal errors ----- <youssef.oumzil@i3e.ma>\n    (reason: 550 Host unknown)\n\n   ----- Transcript of session follows -----\n550 5.0.0 Host unknown\n-------------------------------------------------------------------------\n\nFYI the recipient <youssef.oumzil@i3e.ma> is receiving emails sent as test  from gmail!\n\nCould you please help to solve this issue !\n\nRgds,\nAbdelilah.
INC70092858                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               QY0938 - 13/05/2026 - Data not transmitted from DCC to DCE Hello DCE support team,\n\nURGENT - Please help to transmit data to DCE\nQY0938 - 13/05/2026 - Data exists in DCC but not transmitted to DCE\nAWBs Example :\n1017516124\n1041129865\n1104866711\n\nThe full list of non transmitted AWBs is attached in this ticket.\nplease note urgency!\n\nThx,\nAbdelilah.

In [16]:
# Embeddings des tickets escaladés

escalated_embeddings = model.encode(
    escalated_df["text_for_embedding"].tolist(),
    show_progress_bar=True
)

print("Shape des embeddings :", escalated_embeddings.shape)

NameError: name 'model' is not defined

In [17]:
from sentence_transformers import SentenceTransformer

model = SentenceTransformer("paraphrase-multilingual-MiniLM-L12-v2")

print("Modèle chargé avec succès !")

C:\Users\LENOVO\PycharmProjects\DHL_AI_Incident_Assistant\.venv311\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
Loading weights: 100%|██████████| 199/199 [00:00<00:00, 1615.95it/s]

Modèle chargé avec succès !

In [18]:
escalated_embeddings = model.encode(
    escalated_df["text_for_embedding"].tolist(),
    show_progress_bar=True
)

print("Shape des embeddings :", escalated_embeddings.shape)

Batches: 100%|██████████| 14/14 [00:17<00:00,  1.25s/it]

Shape des embeddings : (430, 384)

In [19]:
escalated_df["solution_type"] = (
    escalated_df["Solution"]
    .apply(classify_solution)
)

escalated_df["solution_quality"] = (
    escalated_df["solution_type"]
    .apply(solution_quality)
)

print(escalated_df["solution_type"].value_counts())

NameError: name 'classify_solution' is not defined

In [20]:
def classify_solution(solution):
    solution = str(solution).strip().lower()

    # 1. Solutions administratives
    administrative_keywords = [
        "duplicate",
        "duplicated",
        "close the ticket",
        "ticket to avoid",
        "no response from user",
        "regional ticket opened",
        "new ticket has been raised",
        "a new ticket has been raised",
        "data provided",
        "cancelled",
        "cancelled by"
    ]

    for keyword in administrative_keywords:
        if keyword in solution:
            return "ADMINISTRATIVE"

    # 2. Solutions génériques
    generic_solutions = {
        "resolved",
        "resolved.",
        "resolved,",
        "solved",
        "solved.",
        "done",
        "done.",
        "fixed",
        "fixed.",
        "closed",
        "closed.",
        "granted",
        "access granted",
        "access granted.",
        "necessary done",
        "necessary done.",
        "necessaey done.",
        "issue fixed",
        "issue solved",
        "problem solved"
    }

    if solution in generic_solutions:
        return "GENERIC"

    # 3. Résolu + référence à un autre ticket
    if solution.startswith("resolved inc"):
        return "GENERIC"

    if solution.startswith("fixed inc"):
        return "GENERIC"

    # 4. Le reste = solution actionnable
    return "ACTIONABLE"

In [21]:
def solution_quality(solution_type):
    if solution_type == "ACTIONABLE":
        return 1
    return 0

In [22]:
escalated_df["solution_type"] = (
    escalated_df["Solution"]
    .apply(classify_solution)
)

escalated_df["solution_quality"] = (
    escalated_df["solution_type"]
    .apply(solution_quality)
)

print(escalated_df["solution_type"].value_counts())

solution_type
ACTIONABLE        417
ADMINISTRATIVE      8
GENERIC             5
Name: count, dtype: int64

In [23]:
actionable_escalated = escalated_df[
    escalated_df["solution_type"] == "ACTIONABLE"
]

print("Nombre de solutions ACTIONABLE :", len(actionable_escalated))

print(
    actionable_escalated[
        ["Number", "Short Description", "Solution"]
    ].head(30).to_string(index=False)
)

Nombre de solutions ACTIONABLE : 417
     Number                                                                                                               Short Description                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                Solution
INC63691050                                                                                                        URGENT : Issue MA ACCS !                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         ACCS server had been rebooted to switch from standby to active mode. \n\nConfirmed with caller and health checks has been successfully completed from our side.
INC65908914                                          Outlook Returns Undeliverable fatal error message when sending to some external emails                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 https://mxtoolbox.com/SuperTool.aspx?action=mx%3ai3e.ma&run=toolpage#\n\nConnecting to 52.117.100.166\n\nSendSMTPCommand: Timeout waiting for response after 15 seconds.\n\n- LookupServer [smtp:52.117.100.166] 17216ms\n\nName error; The domain 52.117.100.166 cannot be found.\nhttps://network-tools.webwiz.net/mail-server-test.htm\n\nReceiver's eMail server is down, please call your receiver to investigate.

In [24]:
# Préparer les deux sources

resolved_knowledge = local_2025.copy()
escalated_knowledge = escalated_df.copy()

# Identifier la source
resolved_knowledge["source"] = "RESOLVED"
escalated_knowledge["source"] = "ESCALATED"

# Colonnes communes
knowledge_df = pd.concat(
    [
        resolved_knowledge,
        escalated_knowledge
    ],
    ignore_index=True
)

print("Nombre total de tickets :", len(knowledge_df))
print()
print(knowledge_df["source"].value_counts())
print()
print(knowledge_df["solution_type"].value_counts())

NameError: name 'local_2025' is not defined

In [25]:
import pandas as pd

local_2025 = pd.read_excel("../data/Inc_resolved by MAIT.xlsx")

print("Nombre de tickets :", len(local_2025))
print(local_2025.columns.tolist())

C:\Users\LENOVO\PycharmProjects\DHL_AI_Incident_Assistant\.venv311\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

Nombre de tickets : 1813
['Number', 'Opened', 'Target Resolution Time (GMT)', 'Informed at', 'Incident Status', 'Caller', 'Assigned Group', 'Assignee', 'Short Description', 'Description', 'Solution']

In [26]:
local_2025["solution_type"] = (
    local_2025["Solution"]
    .apply(classify_solution)
)

print(local_2025["solution_type"].value_counts())

solution_type
GENERIC           1388
ACTIONABLE         397
ADMINISTRATIVE      28
Name: count, dtype: int64

In [27]:
print("Tickets résolus :", len(local_2025))
print("Tickets escaladés :", len(escalated_df))

print("\nRésolus :")
print(local_2025["solution_type"].value_counts())

print("\nEscaladés :")
print(escalated_df["solution_type"].value_counts())

Tickets résolus : 1813
Tickets escaladés : 430

Résolus :
solution_type
GENERIC           1388
ACTIONABLE         397
ADMINISTRATIVE      28
Name: count, dtype: int64

Escaladés :
solution_type
ACTIONABLE        417
ADMINISTRATIVE      8
GENERIC             5
Name: count, dtype: int64

In [28]:
# Préparer les tickets résolus
resolved_knowledge = local_2025.copy()
resolved_knowledge["source"] = "RESOLVED"

# Préparer les tickets escaladés
escalated_knowledge = escalated_df.copy()
escalated_knowledge["source"] = "ESCALATED"

# Fusionner les deux sources
knowledge_df = pd.concat(
    [
        resolved_knowledge,
        escalated_knowledge
    ],
    ignore_index=True
)

print("Nombre total de tickets :", len(knowledge_df))

print("\nRépartition par source :")
print(knowledge_df["source"].value_counts())

print("\nRépartition par type de solution :")
print(knowledge_df["solution_type"].value_counts())

Nombre total de tickets : 2243

Répartition par source :
source
RESOLVED     1813
ESCALATED     430
Name: count, dtype: int64

Répartition par type de solution :
solution_type
GENERIC           1393
ACTIONABLE         814
ADMINISTRATIVE      36
Name: count, dtype: int64

In [29]:
print(
    knowledge_df[
        ["Number", "Short Description", "Solution", "solution_type", "source"]
    ].head(10).to_string(index=False)
)

print("\nColonnes disponibles :")
print(knowledge_df.columns.tolist())

     Number                                                                                                      Short Description                                 Solution  solution_type   source
INC61070901                     Free space on data disk F: is below threshold 10.00%. Current free space is 2.90%. CZCHOWSPC001056                       Database log fixed     ACTIONABLE RESOLVED
INC62031525 TN SPS files transmitted to DCSFTP server but no SD record visible in Sherloc and shipments can't be processed in DCVS Files transmitted, and SD record visible     ACTIONABLE RESOLVED
INC67542407                                                                  MA EXP Application e-HCM OASYS not Working via Citrix                                   Closed        GENERIC RESOLVED
INC63115290                                                                           Update ELMs / IP Whitelisting and URL Update                         Cancelled by NOC ADMINISTRATIVE RESOLVED
INC61393750                                                              MA EXP TUNSHIP Rrovide PID range for TN local application                                 Resolved        GENERIC RESOLVED
INC66441487                                                                                                Print issue in GCA7 app             TN Provider is working on it     ACTIONABLE RESOLVED
INC64928937                                                                                                          DCE BAD ISSUE                                 resolved        GENERIC RESOLVED
INC64305092                                                                                MA YYYYY Casablanca DCVS printing issue                                 Resolved        GENERIC RESOLVED
INC61219128                                                                       MA - EXP - Probleme d'mpression et scan des docs                                 Resolved        GENERIC RESOLVED
INC64864098     MA - EXP - le montant de la NDD ne figure pas sur le D. Sheets  , de même pour la facture  au moment  d'impression                                 Resolved        GENERIC RESOLVED

Colonnes disponibles :
['Number', 'Opened', 'Target Resolution Time (GMT)', 'Informed at', 'Incident Status', 'Caller', 'Assigned Group', 'Assignee', 'Short Description', 'Description', 'Solution', 'solution_type', 'source', 'text_for_embedding', 'solution_quality']

In [30]:
def solution_quality(solution_type):
    if solution_type == "ACTIONABLE":
        return 1
    return 0


knowledge_df["solution_quality"] = (
    knowledge_df["solution_type"]
    .apply(solution_quality)
)

print(
    knowledge_df["solution_quality"].value_counts()
)

solution_quality
0    1429
1     814
Name: count, dtype: int64

In [31]:
knowledge_df["text_for_embedding"] = (
    knowledge_df["Short Description"].fillna("").astype(str)
    + " "
    + knowledge_df["Description"].fillna("").astype(str)
)

print("Nombre de textes :", len(knowledge_df))
print(
    "Textes vides :",
    (knowledge_df["text_for_embedding"].str.strip() == "").sum()
)

Nombre de textes : 2243
Textes vides : 0

In [ ]:
from sentence_transformers import SentenceTransformer

model = SentenceTransformer(
    "paraphrase-multilingual-MiniLM-L12-v2"
)

print("Modèle chargé avec succès !")

C:\Users\LENOVO\PycharmProjects\DHL_AI_Incident_Assistant\.venv311\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [1]:
import sys
print(sys.executable)

C:\Users\LENOVO\PycharmProjects\DHL_AI_Incident_Assistant\.venv311\Scripts\python.exe

In [2]:
import sentence_transformers
print(sentence_transformers.__version__)

C:\Users\LENOVO\PycharmProjects\DHL_AI_Incident_Assistant\.venv311\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

5.7.0

In [3]:
from sentence_transformers import SentenceTransformer

model = SentenceTransformer(
    "paraphrase-multilingual-MiniLM-L12-v2"
)

print("Modèle chargé avec succès !")

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
Loading weights: 100%|██████████| 199/199 [00:00<00:00, 2429.75it/s]

Modèle chargé avec succès !

In [4]:
# Embeddings de tous les tickets
embeddings = model.encode(
    knowledge_base["text_for_embedding"].tolist(),
    show_progress_bar=True
)

print("Shape des embeddings :", embeddings.shape)

NameError: name 'knowledge_base' is not defined

In [5]:
import pandas as pd

resolved_df = pd.read_excel("../data/Inc_resolved by MAIT.xlsx")
escalated_df = pd.read_excel("../data/Inc_registred by MAIT.xlsx")

print("Tickets résolus :", len(resolved_df))
print("Tickets escaladés :", len(escalated_df))

C:\Users\LENOVO\PycharmProjects\DHL_AI_Incident_Assistant\.venv311\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

Tickets résolus : 1813
Tickets escaladés : 430

In [6]:
# Copier les deux sources
resolved_knowledge = resolved_df.copy()
escalated_knowledge = escalated_df.copy()

# Identifier la source
resolved_knowledge["source"] = "RESOLVED"
escalated_knowledge["source"] = "ESCALATED"

# Fusionner
knowledge_base = pd.concat(
    [resolved_knowledge, escalated_knowledge],
    ignore_index=True
)

print("Nombre total de tickets :", len(knowledge_base))
print(knowledge_base["source"].value_counts())

Nombre total de tickets : 2243
source
RESOLVED     1813
ESCALATED     430
Name: count, dtype: int64

In [7]:
knowledge_base["text_for_embedding"] = (
    knowledge_base["Short Description"].fillna("").astype(str)
    + " "
    + knowledge_base["Description"].fillna("").astype(str)
)

print("Nombre de textes :", len(knowledge_base))
print(
    "Textes vides :",
    (knowledge_base["text_for_embedding"].str.strip() == "").sum()
)

Nombre de textes : 2243
Textes vides : 0

In [8]:
embeddings = model.encode(
    knowledge_base["text_for_embedding"].tolist(),
    show_progress_bar=True
)

print("Shape des embeddings :", embeddings.shape)

Batches: 100%|██████████| 71/71 [01:25<00:00,  1.21s/it]

Shape des embeddings : (2243, 384)

In [9]:
def classify_solution(solution):
    solution = str(solution).strip().lower()

    # 1. Solutions administratives
    administrative_keywords = [
        "duplicate",
        "duplicated",
        "close the ticket",
        "ticket to avoid",
        "no response from user",
        "regional ticket opened",
        "new ticket has been raised",
        "a new ticket has been raised",
        "data provided",
        "cancelled",
        "cancelled by"
    ]

    for keyword in administrative_keywords:
        if keyword in solution:
            return "ADMINISTRATIVE"

    # 2. Solutions génériques exactes
    generic_solutions = {
        "resolved",
        "resolved.",
        "resolved,",
        "solved",
        "solved.",
        "done",
        "done.",
        "fixed",
        "fixed.",
        "closed",
        "closed.",
        "granted",
        "access granted",
        "access granted.",
        "necessary done",
        "necessary done.",
        "necessaey done.",
        "issue fixed",
        "issue solved",
        "problem solved"
    }

    if solution in generic_solutions:
        return "GENERIC"

    # 3. Références à un autre ticket
    if solution.startswith("resolved inc"):
        return "GENERIC"

    if solution.startswith("fixed inc"):
        return "GENERIC"

    # 4. Le reste est considéré comme actionnable
    return "ACTIONABLE"

In [10]:
knowledge_base["solution_type"] = (
    knowledge_base["Solution"]
    .apply(classify_solution)
)

print(knowledge_base["solution_type"].value_counts())

solution_type
GENERIC           1393
ACTIONABLE         814
ADMINISTRATIVE      36
Name: count, dtype: int64

In [11]:
from sklearn.metrics.pairwise import cosine_similarity

def find_similar_tickets(new_ticket, top_k=20):
    # Embedding du nouveau ticket
    new_embedding = model.encode(
        [new_ticket],
        normalize_embeddings=True
    )

    # Similarité avec les 2243 tickets
    similarities = cosine_similarity(
        new_embedding,
        embeddings
    )[0]

    # Indices des meilleurs tickets
    top_indices = similarities.argsort()[-top_k:][::-1]

    # Récupérer les tickets
    candidates = knowledge_base.iloc[top_indices].copy()

    # Ajouter la similarité
    candidates["Similarity"] = similarities[top_indices]

    return candidates

In [12]:
new_ticket = "MA - EXP - problème d'impression dans GCA"

similar_tickets = find_similar_tickets(
    new_ticket,
    top_k=20
)

print(
    similar_tickets[
        [
            "Number",
            "Short Description",
            "Solution",
            "solution_type",
            "source",
            "Similarity"
        ]
    ].to_string(index=False)
)

     Number                                                                                           Short Description                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                Solution  solution_type    source  Similarity
INC66310792                                          Issue printing Delivery Sheet from GCA - (GCA Printer :  maagapr1)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      Printer has been fixed.\nResolved.     ACTIONABLE ESCALATED    0.778098
INC65363499                                                       Issue printing from GCA after printer model changed !                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    Printer setup has been updated and it is working now.\n\nResolved.\n     ACTIONABLE ESCALATED    0.719929

In [13]:
source_solution_distribution = pd.crosstab(
    knowledge_base["source"],
    knowledge_base["solution_type"],
    normalize="index"
) * 100

print(
    source_solution_distribution.round(2)
)

solution_type  ACTIONABLE  ADMINISTRATIVE  GENERIC
source
ESCALATED           96.98            1.86     1.16
RESOLVED            21.90            1.54    76.56

In [14]:
knowledge_base["solution_text"] = (
    knowledge_base["Solution"]
    .fillna("")
    .astype(str)
    .str.strip()
)

print("Nombre de solutions :", len(knowledge_base))
print(
    "Solutions vides :",
    (knowledge_base["solution_text"] == "").sum()
)

Nombre de solutions : 2243
Solutions vides : 2

In [15]:
solution_embeddings = model.encode(
    knowledge_base["solution_text"].tolist(),
    show_progress_bar=True,
    normalize_embeddings=True
)

print(
    "Shape des solution embeddings :",
    solution_embeddings.shape
)

Batches: 100%|██████████| 71/71 [00:17<00:00,  4.16it/s]

Shape des solution embeddings : (2243, 384)

In [16]:
from sklearn.metrics.pairwise import cosine_similarity
import numpy as np

# Exemple : prendre le premier ticket comme requête
query_embedding = embeddings[0].reshape(1, -1)

# Calcul de la similarité avec tous les tickets
similarities = cosine_similarity(query_embedding, embeddings)[0]

# Récupérer les 10 tickets les plus similaires
top_k = 10
top_indices = np.argsort(similarities)[::-1][:top_k]

similar_tickets = knowledge_base.iloc[top_indices].copy()
similar_tickets["Similarity"] = similarities[top_indices]

similar_tickets[
    ["Number", "Short Description", "Solution", "solution_type", "source", "Similarity"]
]

,Number,Short Description,Solution,solution_type,source,Similarity
0,INC61070901,Free space on data disk F: is below threshold ...,Database log fixed,ACTIONABLE,RESOLVED,1.000000
1884,INC67124646,"Slowness in MA SDWAN sites : EMTO-MA-EXP-001, ...",BT Time of Resolution : 2025-12-03T11:05:30Z\n...,ACTIONABLE,ESCALATED,0.337485
1373,INC71264352,FSC Access,Access granted,GENERIC,RESOLVED,0.334666
1394,INC71264394,FSC Access,Access granted,GENERIC,RESOLVED,0.334665
1840,INC66068398,Slowness issue in MA SDWAN sites,BT Time of Resolution : 2025-10-08T06:36:53Z\n...,ACTIONABLE,ESCALATED,0.330027
2101,INC66282228,Issue DP File,"Kindly, refer attached email for reference. Th...",ACTIONABLE,ESCALATED,0.316770
1372,INC67769604,Problème connexion réseau au niveau du PC,solved,GENERIC,RESOLVED,0.312383
1878,INC70506156,CCaaS : DIA utilization statistics from Zscale...,Graphs have been attached as requested for sit...,ACTIONABLE,ESCALATED,0.310183
1856,INC66525504,Slowness issue in MA SDWAN site : EMTO-MA-EXP-002,BT Time of Resolution : 2025-11-03T11:27:53Z\n...,ACTIONABLE,ESCALATED,0.306893
1,INC62031525,TN SPS files transmitted to DCSFTP server but ...,"Files transmitted, and SD record visible",ACTIONABLE,RESOLVED,0.305213

In [17]:
import numpy as np

def search_similar_tickets(query, top_k=5):
    # Embedding du nouveau ticket
    query_embedding = model.encode(
        [query],
        normalize_embeddings=True
    )[0]

    # Similarité cosinus
    similarities = embeddings @ query_embedding

    # Indices des meilleurs résultats
    top_indices = np.argsort(similarities)[::-1][:top_k]

    # Résultats
    results = knowledge_base.iloc[top_indices].copy()
    results["Similarity"] = similarities[top_indices]

    return results[
        [
            "Number",
            "Short Description",
            "Solution",
            "solution_type",
            "source",
            "Similarity"
        ]
    ]

In [18]:
query = """
GCA printer is not printing delivery sheets.
The printer is connected but documents remain pending.
"""

results = search_similar_tickets(query, top_k=5)

results

,Number,Short Description,Solution,solution_type,source,Similarity
1092,INC69346363,Printer Issue,Issue solved,GENERIC,RESOLVED,3.516378
57,INC69711341,Printer,Resolved,GENERIC,RESOLVED,3.495738
984,INC67011539,Printing issue,solved,GENERIC,RESOLVED,3.135195
1484,INC64352664,Printer Issue,Resolved,GENERIC,RESOLVED,2.652020
1209,INC68589028,Add printer to laptop,Done.,GENERIC,RESOLVED,2.581551

In [19]:
def search_similar_tickets(query, top_k=5):

    # Embedding du nouveau ticket
    query_embedding = model.encode(
        [query],
        normalize_embeddings=True
    )[0]

    # Normalisation des embeddings de la base
    normalized_embeddings = embeddings / np.linalg.norm(
        embeddings,
        axis=1,
        keepdims=True
    )

    # Similarité cosinus
    similarities = normalized_embeddings @ query_embedding

    # Meilleurs résultats
    top_indices = np.argsort(similarities)[::-1][:top_k]

    results = knowledge_base.iloc[top_indices].copy()
    results["Similarity"] = similarities[top_indices]

    return results[
        [
            "Number",
            "Short Description",
            "Solution",
            "solution_type",
            "source",
            "Similarity"
        ]
    ]

In [20]:
query = """
GCA printer is not printing delivery sheets.
The printer is connected but documents remain pending.
"""

results = search_similar_tickets(query, top_k=5)

results

,Number,Short Description,Solution,solution_type,source,Similarity
1841,INC66310792,Issue printing Delivery Sheet from GCA - (GCA ...,Printer has been fixed.\nResolved.,ACTIONABLE,ESCALATED,0.780635
1838,INC65363499,Issue printing from GCA after printer model ch...,Printer setup has been updated and it is worki...,ACTIONABLE,ESCALATED,0.703355
2021,INC64341450,GCA 7 (Delivery sheet) printing delay issue,Printer drivers were updated and issue resolved.,ACTIONABLE,ESCALATED,0.695646
1972,INC65033159,GCA 7 (Delivery sheet) printing delay issue,Mentioned printers were recreated on both serv...,ACTIONABLE,ESCALATED,0.689413
113,INC67202503,MA - EXP - GOPS printer not connecting with GC...,Need to close the ticket to avoid any TRT impact,ADMINISTRATIVE,RESOLVED,0.669412

In [21]:
print("Ticket embeddings :", embeddings.shape)
print("Solution embeddings :", solution_embeddings.shape)

print(
    "Norme moyenne tickets :",
    np.linalg.norm(embeddings, axis=1).mean()
)

print(
    "Norme moyenne solutions :",
    np.linalg.norm(solution_embeddings, axis=1).mean()
)

Ticket embeddings : (2243, 384)
Solution embeddings : (2243, 384)
Norme moyenne tickets : 3.4802551
Norme moyenne solutions : 1.0

In [22]:
def recommend_solution(query, top_k=5):

    results = search_similar_tickets(query, top_k=top_k)

    # Priorité aux solutions actionnables
    actionable = results[
        results["solution_type"] == "ACTIONABLE"
    ]

    # S'il existe des solutions actionnables,
    # on les privilégie
    if len(actionable) > 0:
        best_result = actionable.iloc[0]
    else:
        best_result = results.iloc[0]

    return best_result

In [23]:
query = """
GCA printer is not printing delivery sheets.
The printer is connected but documents remain pending.
"""

recommendation = recommend_solution(query)

recommendation

Number                                                     INC66310792
Short Description    Issue printing Delivery Sheet from GCA - (GCA ...
Solution                            Printer has been fixed.\nResolved.
solution_type                                               ACTIONABLE
source                                                       ESCALATED
Similarity                                                    0.780635
Name: 1841, dtype: object

In [24]:
query = """
GCA printer is not printing delivery sheets.
The printer is connected but documents remain pending.
"""

results = search_similar_tickets(query, top_k=10)

results[
    [
        "Number",
        "Short Description",
        "Solution",
        "solution_type",
        "source",
        "Similarity"
    ]
]

,Number,Short Description,Solution,solution_type,source,Similarity
1841,INC66310792,Issue printing Delivery Sheet from GCA - (GCA ...,Printer has been fixed.\nResolved.,ACTIONABLE,ESCALATED,0.780635
1838,INC65363499,Issue printing from GCA after printer model ch...,Printer setup has been updated and it is worki...,ACTIONABLE,ESCALATED,0.703355
2021,INC64341450,GCA 7 (Delivery sheet) printing delay issue,Printer drivers were updated and issue resolved.,ACTIONABLE,ESCALATED,0.695646
1972,INC65033159,GCA 7 (Delivery sheet) printing delay issue,Mentioned printers were recreated on both serv...,ACTIONABLE,ESCALATED,0.689413
113,INC67202503,MA - EXP - GOPS printer not connecting with GC...,Need to close the ticket to avoid any TRT impact,ADMINISTRATIVE,RESOLVED,0.669412
57,INC69711341,Printer,Resolved,GENERIC,RESOLVED,0.646228
5,INC66441487,Print issue in GCA7 app,TN Provider is working on it,ACTIONABLE,RESOLVED,0.644517
1092,INC69346363,Printer Issue,Issue solved,GENERIC,RESOLVED,0.636835
1827,INC65410555,Request to change printer model for GCA printe...,As per the request printer driver updated \n\n...,ACTIONABLE,ESCALATED,0.629183
1981,INC61302569,Add printers on GCA7 app,"Completed, printers installed on demanded serv...",ACTIONABLE,ESCALATED,0.625473

In [26]:
import numpy as np
import pandas as pd

def search_similar_tickets(query, top_k=10):
    # Embedding de la nouvelle requête
    query_embedding = model.encode(
        [query],
        normalize_embeddings=True
    )[0]

    # Normalisation des embeddings des tickets
    ticket_embeddings_norm = embeddings / np.linalg.norm(
        embeddings, axis=1, keepdims=True
    )

    # Similarité cosinus
    similarities = np.dot(
        ticket_embeddings_norm,
        query_embedding
    )

    # Top K
    top_indices = np.argsort(similarities)[::-1][:top_k]

    results = knowledge_base.iloc[top_indices].copy()
    results["Similarity"] = similarities[top_indices]

    return results[
        [
            "Number",
            "Short Description",
            "Solution",
            "solution_type",
            "source",
            "Similarity"
        ]
    ]

In [27]:
query = """
Issue printing Delivery Sheet from GCA.
The printer is not working and Delivery Sheets cannot be printed.
"""

results = search_similar_tickets(query, top_k=10)

results

,Number,Short Description,Solution,solution_type,source,Similarity
1841,INC66310792,Issue printing Delivery Sheet from GCA - (GCA ...,Printer has been fixed.\nResolved.,ACTIONABLE,ESCALATED,0.890748
1838,INC65363499,Issue printing from GCA after printer model ch...,Printer setup has been updated and it is worki...,ACTIONABLE,ESCALATED,0.692957
1972,INC65033159,GCA 7 (Delivery sheet) printing delay issue,Mentioned printers were recreated on both serv...,ACTIONABLE,ESCALATED,0.687656
2021,INC64341450,GCA 7 (Delivery sheet) printing delay issue,Printer drivers were updated and issue resolved.,ACTIONABLE,ESCALATED,0.684899
984,INC67011539,Printing issue,solved,GENERIC,RESOLVED,0.678870
5,INC66441487,Print issue in GCA7 app,TN Provider is working on it,ACTIONABLE,RESOLVED,0.677961
1092,INC69346363,Printer Issue,Issue solved,GENERIC,RESOLVED,0.654330
57,INC69711341,Printer,Resolved,GENERIC,RESOLVED,0.634445
998,INC66808943,Probleme d'impression,Fixed,GENERIC,RESOLVED,0.624424
1484,INC64352664,Printer Issue,Resolved,GENERIC,RESOLVED,0.614002

In [28]:
import numpy as np
import pandas as pd

def search_similar_tickets(query, top_k=5):
    """
    Recherche les tickets les plus similaires à une nouvelle demande.
    """

    # Embedding de la nouvelle demande
    query_embedding = model.encode(
        [query],
        normalize_embeddings=True
    )[0]

    # Normalisation des embeddings des tickets
    ticket_embeddings_norm = embeddings / np.linalg.norm(
        embeddings,
        axis=1,
        keepdims=True
    )

    # Similarité cosinus
    similarities = np.dot(
        ticket_embeddings_norm,
        query_embedding
    )

    # Indices des meilleurs résultats
    top_indices = np.argsort(similarities)[::-1][:top_k]

    # Résultats
    results = knowledge_base.iloc[top_indices].copy()
    results["Similarity"] = similarities[top_indices]

    return results[
        [
            "Number",
            "Short Description",
            "Solution",
            "solution_type",
            "source",
            "Similarity"
        ]
    ]

In [29]:
query = "GCA printer is not working and delivery sheets cannot be printed"

results = search_similar_tickets(query, top_k=5)

results

,Number,Short Description,Solution,solution_type,source,Similarity
1841,INC66310792,Issue printing Delivery Sheet from GCA - (GCA ...,Printer has been fixed.\nResolved.,ACTIONABLE,ESCALATED,0.847182
1838,INC65363499,Issue printing from GCA after printer model ch...,Printer setup has been updated and it is worki...,ACTIONABLE,ESCALATED,0.726280
5,INC66441487,Print issue in GCA7 app,TN Provider is working on it,ACTIONABLE,RESOLVED,0.714221
2021,INC64341450,GCA 7 (Delivery sheet) printing delay issue,Printer drivers were updated and issue resolved.,ACTIONABLE,ESCALATED,0.680299
1092,INC69346363,Printer Issue,Issue solved,GENERIC,RESOLVED,0.673956

In [30]:
def search_best_solutions(query, top_k=5):
    """
    Recherche les meilleures solutions pour une nouvelle demande.
    Priorise les tickets escaladés et les solutions ACTIONABLE.
    """

    # Embedding de la requête
    query_embedding = model.encode(
        [query],
        normalize_embeddings=True
    )[0]

    # Normalisation des embeddings
    ticket_embeddings_norm = embeddings / np.linalg.norm(
        embeddings,
        axis=1,
        keepdims=True
    )

    # Similarité cosinus
    similarities = np.dot(
        ticket_embeddings_norm,
        query_embedding
    )

    # Copie de la base
    results = knowledge_base.copy()

    results["Similarity"] = similarities

    # Score final
    results["Final_Score"] = results["Similarity"]

    # Bonus pour les tickets escaladés
    results.loc[
        results["source"] == "ESCALATED",
        "Final_Score"
    ] += 0.05

    # Bonus supplémentaire pour les solutions actionnables
    results.loc[
        results["solution_type"] == "ACTIONABLE",
        "Final_Score"
    ] += 0.03

    # Classement
    results = results.sort_values(
        "Final_Score",
        ascending=False
    )

    return results[
        [
            "Number",
            "Short Description",
            "Solution",
            "solution_type",
            "source",
            "Similarity",
            "Final_Score"
        ]
    ].head(top_k)

In [31]:
query = "GCA printer is not working and delivery sheets cannot be printed"

best_results = search_best_solutions(
    query,
    top_k=5
)

best_results

,Number,Short Description,Solution,solution_type,source,Similarity,Final_Score
1841,INC66310792,Issue printing Delivery Sheet from GCA - (GCA ...,Printer has been fixed.\nResolved.,ACTIONABLE,ESCALATED,0.847182,0.927182
1838,INC65363499,Issue printing from GCA after printer model ch...,Printer setup has been updated and it is worki...,ACTIONABLE,ESCALATED,0.726280,0.806280
2021,INC64341450,GCA 7 (Delivery sheet) printing delay issue,Printer drivers were updated and issue resolved.,ACTIONABLE,ESCALATED,0.680299,0.760299
1972,INC65033159,GCA 7 (Delivery sheet) printing delay issue,Mentioned printers were recreated on both serv...,ACTIONABLE,ESCALATED,0.669492,0.749492
5,INC66441487,Print issue in GCA7 app,TN Provider is working on it,ACTIONABLE,RESOLVED,0.714221,0.744221

In [32]:
def build_llm_context(results):
    """
    Transforme les résultats de recherche en contexte
    exploitable par le LLM.
    """

    context_parts = []

    for i, row in results.iterrows():

        context_parts.append(
            f"""
Ticket : {row['Number']}
Problème : {row['Short Description']}
Type de solution : {row['solution_type']}
Source : {row['source']}
Similarité : {row['Similarity']:.3f}

Solution :
{row['Solution']}
"""
        )

    return "\n".join(context_parts)

In [33]:
context = build_llm_context(best_results)

print(context)

Ticket : INC66310792
Problème : Issue printing Delivery Sheet from GCA - (GCA Printer :  maagapr1)
Type de solution : ACTIONABLE
Source : ESCALATED
Similarité : 0.847

Solution :
Printer has been fixed.
Resolved.


Ticket : INC65363499
Problème : Issue printing from GCA after printer model changed !
Type de solution : ACTIONABLE
Source : ESCALATED
Similarité : 0.726

Solution :
Printer setup has been updated and it is working now.

Resolved.



Ticket : INC64341450
Problème : GCA 7 (Delivery sheet) printing delay issue
Type de solution : ACTIONABLE
Source : ESCALATED
Similarité : 0.680

Solution :
Printer drivers were updated and issue resolved.


Ticket : INC65033159
Problème : GCA 7 (Delivery sheet) printing delay issue
Type de solution : ACTIONABLE
Source : ESCALATED
Similarité : 0.669

Solution :
Mentioned printers were recreated on both servers as requested.

device for matngpr3: beh:/1/0/60/socket://23.82.14.5:9100
device for matngpr4: beh:/1/0/60/socket://23.82.14.6:9100
matngpr3 accepting requests since Mon 04 Aug 2025 02:03:25 PM GMT
matngpr4 accepting requests since Mon 04 Aug 2025 02:03:32 PM GMT
printer matngpr3 is idle.  enabled since Mon 04 Aug 2025 02:03:25 PM GMT
printer matngpr4 is idle.  enabled since Mon 04 Aug 2025 02:03:32 PM GMT


Ticket : INC66441487
Problème : Print issue in GCA7 app
Type de solution : ACTIONABLE
Source : RESOLVED
Similarité : 0.714

Solution :
TN Provider is working on it

In [34]:
import numpy as np

def search_similar_tickets(
    query,
    model,
    knowledge_base,
    ticket_embeddings,
    top_k=5
):
    """
    Recherche les tickets historiquement les plus similaires
    à un nouveau problème.
    """

    # Embedding du nouveau problème
    query_embedding = model.encode(
        [query],
        normalize_embeddings=True
    )[0]

    # Normalisation des embeddings historiques
    normalized_embeddings = ticket_embeddings / np.linalg.norm(
        ticket_embeddings,
        axis=1,
        keepdims=True
    )

    # Similarité cosinus
    similarities = normalized_embeddings @ query_embedding

    # Indices des meilleurs résultats
    top_indices = np.argsort(similarities)[::-1][:top_k]

    # Résultats
    results = knowledge_base.iloc[top_indices].copy()

    results["Similarity"] = similarities[top_indices]

    return results

In [35]:
query = "GCA printer is not printing delivery sheets"

results = search_similar_tickets(
    query,
    model,
    knowledge_base,
    embeddings,
    top_k=5
)

results[
    [
        "Number",
        "Short Description",
        "Solution",
        "solution_type",
        "source",
        "Similarity"
    ]
]

,Number,Short Description,Solution,solution_type,source,Similarity
1841,INC66310792,Issue printing Delivery Sheet from GCA - (GCA ...,Printer has been fixed.\nResolved.,ACTIONABLE,ESCALATED,0.816159
1838,INC65363499,Issue printing from GCA after printer model ch...,Printer setup has been updated and it is worki...,ACTIONABLE,ESCALATED,0.708862
5,INC66441487,Print issue in GCA7 app,TN Provider is working on it,ACTIONABLE,RESOLVED,0.679873
57,INC69711341,Printer,Resolved,GENERIC,RESOLVED,0.677027
1092,INC69346363,Printer Issue,Issue solved,GENERIC,RESOLVED,0.661711

In [36]:
import os
import numpy as np
import pandas as pd

# Dossier de sortie
output_dir = r"C:\Users\LENOVO\PycharmProjects\DHL_AI_Incident_Assistant\data"

# Sauvegarder la base de connaissances
knowledge_base.to_pickle(
    os.path.join(output_dir, "knowledge_base.pkl")
)

# Sauvegarder les embeddings
np.save(
    os.path.join(output_dir, "ticket_embeddings.npy"),
    embeddings
)

np.save(
    os.path.join(output_dir, "solution_embeddings.npy"),
    solution_embeddings
)

print("Base de connaissances sauvegardée.")
print("Ticket embeddings sauvegardés :", embeddings.shape)
print("Solution embeddings sauvegardés :", solution_embeddings.shape)

Base de connaissances sauvegardée.
Ticket embeddings sauvegardés : (2243, 384)
Solution embeddings sauvegardés : (2243, 384)

In [4]:
# ==============================
# FINAL PIPELINE - DHL AI INCIDENT ASSISTANT
# ==============================import pandas as pd

resolved_df = pd.read_excel(
    "../data/Inc_resolved by MAIT.xlsx"
)

escalated_df = pd.read_excel(
    "../data/Inc_registred by MAIT.xlsx"
)

print("Resolved :", resolved_df.shape)
print("Escalated:", escalated_df.shape)

NameError: name 'pd' is not defined

In [ ]:
# ==============================
# FINAL PIPELINE - DHL AI INCIDENT ASSISTANT
# ==============================

In [1]:
print("===== ETAT ACTUEL DU PROJET =====")

print("\nVariables principales :")

for variable in [
    "resolved_df",
    "escalated_df",
    "knowledge_base",
    "model",
    "embeddings",
    "solution_embeddings"
]:
    print(
        variable,
        "→",
        "EXISTE" if variable in globals() else "ABSENTE"
    )

===== ETAT ACTUEL DU PROJET =====

Variables principales :
resolved_df → ABSENTE
escalated_df → ABSENTE
knowledge_base → ABSENTE
model → ABSENTE
embeddings → ABSENTE
solution_embeddings → ABSENTE

In [39]:
print("===== KNOWLEDGE BASE =====")

print("\nShape :")
print(knowledge_base.shape)

print("\nSources :")
print(knowledge_base["source"].value_counts())

print("\nTypes de solutions :")
print(knowledge_base["solution_type"].value_counts())

print("\nColonnes importantes :")
print(
    knowledge_base[
        [
            "Number",
            "Short Description",
            "Description",
            "Solution",
            "source",
            "solution_type"
        ]
    ].head(10).to_string(index=False)
)

===== KNOWLEDGE BASE =====

Shape :
(2243, 15)

Sources :
source
RESOLVED     1813
ESCALATED     430
Name: count, dtype: int64

Types de solutions :
solution_type
GENERIC           1393
ACTIONABLE         814
ADMINISTRATIVE      36
Name: count, dtype: int64

Colonnes importantes :
     Number                                                                                                      Short Description                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              Description                                 Solution   source  solution_type
INC61070901                     Free space on data disk F: is below threshold 10.00%. Current free space is 2.90%. CZCHOWSPC001056                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            Please check INC61063104 Free space on data disk F: is below threshold 10.00%. Current free space is 2.90%. CZCHOWSPC001056\nDetected on node: czchowspc001056.prg-dc.dhl.com                       Database log fixed RESOLVED     ACTIONABLE
INC62031525 TN SPS files transmitted to DCSFTP server but no SD record visible in Sherloc and shipments can't be processed in DCVS                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      Hi,\n\nCould you please urgently assign to DCS support team!\nTN SPS files transmitted to DCSFTP server (dcsftp.dhl.com) but no SD record visible in Sherloc and shipments can't be processed in DCVS !\nExample of HAWBs :\n6882154156\n6882154823\n6882154075\n\nThx,\nAbdelilah. Files transmitted, and SD record visible RESOLVED     ACTIONABLE
INC67542407                                                                  MA EXP Application e-HCM OASYS not Working via Citrix                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     Hi,\n\nPlease note that we are experiencing an issue while accessing the HR application through the Citrix platform.\n\nWhen we launch the application, the Citrix window loads successfully; however, after the Citrix session finishes loading, nothing happens and the application does not open or respond with no error message displayed.\n\nCould please help to fix this issue.\n\nThanks in advance,\nNabil                                   Closed RESOLVED        GENERIC
INC63115290                                                                           Update ELMs / IP Whitelisting and URL Update Dears,\nPlease assign to ELM/ELR support team,\n\nDear ELM/ELR Team,\n\nPlease note that "UMEX" is undergoing a tech-refresh activity and "OCNT" will need to re-point to the new UMEX URL : umex.dhl.com.\n\nCould you please ensure the following UMEX IP addresses are whitelisted in the the following ELM's list :\n\nUmex-ap.dhl.com, IP: 199.40.67.92\n\nUmex-eu.dhl.com, IP: 165.72.13.117\n\n----------------------------------------------------------\nRequest ID                     <>  3rd Party Name\n----------------------------------------------------------\n160805-XVP-2767   <>  Chronopost Rabat Morocco\n170209-XVP-2744   <>  Chronopost Maroc\n240312-XVP-6400   <>  Chronopost Morocco\n160610-XVP-9555   <>  Chronopost Morocco\n240312-XVP-6387   <>  Chronopost Morocco\n240423-MIS-9635   <>  Rapid-Poste EMS Tunisia\n240423-MIS-9628   <>  Rapid-Poste EMS Tunis Tunisia\n160210-XVP-3052   < > Rapid-Poste EMS Tunis Tunisia\n151221-XVP-0871   <>  AACC- SINDBAD Group\n231225-XVP-9602   <>  AACC- SINDBAD Group\n190430-XVP-2030   <>  MTI Express\n\n\nThanks in advance,\nNabil\n                         Cancelled by NOC RESOLVED ADMINISTRATIVE
INC61393750                                                              MA EXP TUNSHIP Rrovide PID range for TN local application                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   Dears,\nCould you pls provide a PID range (number = 100000) that we can use it for our local application\nCountry : TN\n\nRgds,\nNabil                                 Resolved RESOLVED        GENERIC
INC66441487                                                                                                Print issue in GCA7 app                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          Dears,\n\nWe recently added these two printers, but printing does not work!\n\nTNSNDGCA01 : 192.168.251.200    Nated  199.40.179.155\nTNSNDGCA02 : 192.168.251.201    Nated  199.40.179.156\n\nCountry = TN  <>  Location = TUN-SND\n\nCould you please check and advise ?\n\n\n\n\n\nThanks in advance,\nNabil             TN Provider is working on it RESOLVED     ACTIONABLE
INC64928937                                                                                                          DCE BAD ISSUE                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              Dear Team , \n\nPlease note that the BAD does not download from the DCE application. Thank you for your support.\n\nThanks.                                 resolved RESOLVED        GENERIC
INC64305092                                                                                MA YYYYY Casablanca DCVS printing issue                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ID:                \nUID:             yghoumar\nNAME:         Yassir GHOUMARY\nEM@IL:       yassir.ghoumary@dhl.com\n\nDESCRIPTION:\nDear Team, \n\nPlease note that we are experiencing an issue with label printing in the DCVS application.\n\nThanks.                                 Resolved RESOLVED        GENERIC
INC61219128                                                                       MA - EXP - Probleme d'mpression et scan des docs                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            Printer name: RICOH Aficio MP 4055SP\nBrand: \nModel: RICOH MP 4055SP\nPrinter Name & Model: RICOH Aficio MP 4055SP\nAsset ID: C83148134\nAddress: \n7415 Emerald Dunes Dr., Suite 600, Orlando, USA\n\nMore Information:\nProbleme d'mpression et scan des docs\n\nContact preference: phone                                 Resolved RESOLVED        GENERIC
INC64864098     MA - EXP - le montant de la NDD ne figure pas sur le D. Sheets  , de même pour la facture  au moment  d'impression                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 Printer name: RICOH Aficio MP 4055SP\nBrand: \nModel: RICOH MP 4055SP\nPrinter Name & Model: RICOH Aficio MP 4055SP\nAsset ID: C83148134\nAddress: \n7415 Emerald Dunes Dr., Suite 600, Orlando, USA\n\nMore Information:\n\n\nContact preference: phone                                 Resolved RESOLVED        GENERIC

In [40]:
print("===== CONTRÔLE DES EMBEDDINGS =====")

print("Knowledge base :", knowledge_base.shape)
print("Ticket embeddings :", embeddings.shape)
print("Solution embeddings :", solution_embeddings.shape)

print("\nNombre de tickets :", len(knowledge_base))
print("Nombre ticket embeddings :", len(embeddings))
print("Nombre solution embeddings :", len(solution_embeddings))

assert len(knowledge_base) == len(embeddings), \
    "ERREUR : nombre de tickets différent du nombre d'embeddings"

assert len(knowledge_base) == len(solution_embeddings), \
    "ERREUR : nombre de tickets différent du nombre d'embeddings solutions"

print("\n✅ Tous les contrôles sont OK.")

===== CONTRÔLE DES EMBEDDINGS =====
Knowledge base : (2243, 15)
Ticket embeddings : (2243, 384)
Solution embeddings : (2243, 384)

Nombre de tickets : 2243
Nombre ticket embeddings : 2243
Nombre solution embeddings : 2243

✅ Tous les contrôles sont OK.

In [42]:
query = """
GCA printer is not printing delivery sheets.
The printer is not working and documents cannot be printed.
"""

results = search_similar_tickets(
    query,
    top_k=10
)

print(
    results.to_string(index=False)
)

     Number                                                  Short Description                                                                                                                                                                                                                                                                                                                                                                                                                                                                          Solution solution_type    source  Similarity
INC66310792 Issue printing Delivery Sheet from GCA - (GCA Printer :  maagapr1)                                                                                                                                                                                                                                                                                                                                                                                                                                                Printer has been fixed.\nResolved.    ACTIONABLE ESCALATED    0.818942
INC65363499              Issue printing from GCA after printer model changed !                                                                                                                                                                                                                                                                                                                                                                                                              Printer setup has been updated and it is working now.\n\nResolved.\n    ACTIONABLE ESCALATED    0.707933
INC69346363                                                      Printer Issue                                                                                                                                                                                                                                                                                                                                                                                                                                                                      Issue solved       GENERIC  RESOLVED    0.689669
INC69711341                                                            Printer                                                                                                                                                                                                                                                                                                                                                                                                                                                                         Resolved        GENERIC  RESOLVED    0.687268
INC66441487                                            Print issue in GCA7 app                                                                                                                                                                                                                                                                                                                                                                                                                                                      TN Provider is working on it    ACTIONABLE  RESOLVED    0.685985
INC67011539                                                     Printing issue                                                                                                                                                                                                                                                                                                                                                                                                                                                                            solved       GENERIC  RESOLVED    0.663551
INC64341450                        GCA 7 (Delivery sheet) printing delay issue                                                                                                                                                                                                                                                                                                                                                                                                                                  Printer drivers were updated and issue resolved.    ACTIONABLE ESCALATED    0.650638
INC65033159                        GCA 7 (Delivery sheet) printing delay issue Mentioned printers were recreated on both servers as requested.\n\ndevice for matngpr3: beh:/1/0/60/socket://23.82.14.5:9100\ndevice for matngpr4: beh:/1/0/60/socket://23.82.14.6:9100\nmatngpr3 accepting requests since Mon 04 Aug 2025 02:03:25 PM GMT\nmatngpr4 accepting requests since Mon 04 Aug 2025 02:03:32 PM GMT\nprinter matngpr3 is idle.  enabled since Mon 04 Aug 2025 02:03:25 PM GMT\nprinter matngpr4 is idle.  enabled since Mon 04 Aug 2025 02:03:32 PM GMT    ACTIONABLE ESCALATED    0.648158
INC66808943                                              Probleme d'impression                                                                                                                                                                                                                                                                                                                                                                                                                                                                             Fixed       GENERIC  RESOLVED    0.639389
INC64352664                                                      Printer Issue                                                                                                                                                                                                                                                                                                                                                                                                                                                                          Resolved       GENERIC  RESOLVED    0.634533

In [43]:
def rank_solution_candidates(
    query,
    top_k=50,
    n_recommendations=5
):
    """
    Recherche les tickets similaires puis privilégie
    les solutions ACTIONABLE.
    """

    # 1. Recherche sémantique
    candidates = search_similar_tickets(
        query,
        top_k=top_k
    ).copy()

    # 2. Garder uniquement les solutions exploitables
    candidates = candidates[
        candidates["solution_type"] == "ACTIONABLE"
    ].copy()

    # 3. Trier par similarité
    candidates = candidates.sort_values(
        "Similarity",
        ascending=False
    )

    # 4. Retourner les meilleures recommandations
    return candidates.head(n_recommendations)

In [44]:
query = """
GCA printer is not printing delivery sheets.
The printer is not working and documents cannot be printed.
"""

recommendations = rank_solution_candidates(
    query,
    top_k=50,
    n_recommendations=5
)

print(
    recommendations[
        [
            "Number",
            "Short Description",
            "Solution",
            "solution_type",
            "source",
            "Similarity"
        ]
    ].to_string(index=False)
)

     Number                                                  Short Description                                                                                                                                                                                                                                                                                                                                                                                                                                                                          Solution solution_type    source  Similarity
INC66310792 Issue printing Delivery Sheet from GCA - (GCA Printer :  maagapr1)                                                                                                                                                                                                                                                                                                                                                                                                                                                Printer has been fixed.\nResolved.    ACTIONABLE ESCALATED    0.818942
INC65363499              Issue printing from GCA after printer model changed !                                                                                                                                                                                                                                                                                                                                                                                                              Printer setup has been updated and it is working now.\n\nResolved.\n    ACTIONABLE ESCALATED    0.707933
INC66441487                                            Print issue in GCA7 app                                                                                                                                                                                                                                                                                                                                                                                                                                                      TN Provider is working on it    ACTIONABLE  RESOLVED    0.685985
INC64341450                        GCA 7 (Delivery sheet) printing delay issue                                                                                                                                                                                                                                                                                                                                                                                                                                  Printer drivers were updated and issue resolved.    ACTIONABLE ESCALATED    0.650638
INC65033159                        GCA 7 (Delivery sheet) printing delay issue Mentioned printers were recreated on both servers as requested.\n\ndevice for matngpr3: beh:/1/0/60/socket://23.82.14.5:9100\ndevice for matngpr4: beh:/1/0/60/socket://23.82.14.6:9100\nmatngpr3 accepting requests since Mon 04 Aug 2025 02:03:25 PM GMT\nmatngpr4 accepting requests since Mon 04 Aug 2025 02:03:32 PM GMT\nprinter matngpr3 is idle.  enabled since Mon 04 Aug 2025 02:03:25 PM GMT\nprinter matngpr4 is idle.  enabled since Mon 04 Aug 2025 02:03:32 PM GMT    ACTIONABLE ESCALATED    0.648158

In [45]:
from sklearn.metrics.pairwise import cosine_similarity
import numpy as np


def solution_similarity(solution1, solution2):
    """
    Calcule la similarité sémantique entre deux solutions.
    """

    emb1 = model.encode(
        [str(solution1)],
        normalize_embeddings=True
    )

    emb2 = model.encode(
        [str(solution2)],
        normalize_embeddings=True
    )

    return float(
        cosine_similarity(
            emb1,
            emb2
        )[0][0]
    )

In [46]:
test_pairs = [
    (
        "Printer drivers were updated and issue resolved.",
        "Printer setup has been updated and it is working now."
    ),
    (
        "Printer drivers were updated and issue resolved.",
        "TN Provider is working on it"
    ),
    (
        "Printer has been fixed.",
        "Printer setup has been updated and it is working now."
    )
]

for solution1, solution2 in test_pairs:

    score = solution_similarity(
        solution1,
        solution2
    )

    print(
        f"\nSolution 1 : {solution1}"
    )

    print(
        f"Solution 2 : {solution2}"
    )

    print(
        f"Similarity : {score:.4f}"
    )

Solution 1 : Printer drivers were updated and issue resolved.
Solution 2 : Printer setup has been updated and it is working now.
Similarity : 0.7540

Solution 1 : Printer drivers were updated and issue resolved.
Solution 2 : TN Provider is working on it
Similarity : 0.2093

Solution 1 : Printer has been fixed.
Solution 2 : Printer setup has been updated and it is working now.
Similarity : 0.7854

In [47]:
def find_similar_solutions(
    solution,
    top_k=5,
    min_similarity=0.70
):
    """
    Trouve les solutions historiques sémantiquement
    proches d'une solution donnée.
    """

    # Embedding de la solution recherchée
    query_embedding = model.encode(
        [str(solution)],
        normalize_embeddings=True
    )[0]

    # Les solution_embeddings sont déjà normalisés
    similarities = solution_embeddings @ query_embedding

    # Trier par similarité
    top_indices = np.argsort(
        similarities
    )[::-1]

    # Construire les résultats
    results = knowledge_base.iloc[top_indices].copy()

    results["Solution_Similarity"] = (
        similarities[top_indices]
    )

    # Retirer la solution elle-même si elle apparaît
    results = results[
        results["Solution"].astype(str).str.strip().str.lower()
        != str(solution).strip().lower()
    ]

    # Seuil
    results = results[
        results["Solution_Similarity"] >= min_similarity
    ]

    return results[
        [
            "Number",
            "Short Description",
            "Solution",
            "solution_type",
            "source",
            "Solution_Similarity"
        ]
    ].head(top_k)

In [48]:
solution = (
    "Printer drivers were updated and issue resolved."
)

similar_solutions = find_similar_solutions(
    solution,
    top_k=10,
    min_similarity=0.70
)

print(
    similar_solutions.to_string(index=False)
)

     Number                                                  Short Description                                                             Solution solution_type    source  Solution_Similarity
INC65363499              Issue printing from GCA after printer model changed ! Printer setup has been updated and it is working now.\n\nResolved.\n    ACTIONABLE ESCALATED             0.823637
INC66310792 Issue printing Delivery Sheet from GCA - (GCA Printer :  maagapr1)                                   Printer has been fixed.\nResolved.    ACTIONABLE ESCALATED             0.822696
INC62342227                                     Change GCA7 Printer IP address                              Printer IP has been updated.\nResolved.    ACTIONABLE ESCALATED             0.789902

In [50]:
query = "GCA printer is not working and delivery sheets cannot be printed"

results = search_similar_tickets(query, top_k=5)

results

,Number,Short Description,Solution,solution_type,source,Similarity
1841,INC66310792,Issue printing Delivery Sheet from GCA - (GCA ...,Printer has been fixed.\nResolved.,ACTIONABLE,ESCALATED,0.847182
1838,INC65363499,Issue printing from GCA after printer model ch...,Printer setup has been updated and it is worki...,ACTIONABLE,ESCALATED,0.726280
5,INC66441487,Print issue in GCA7 app,TN Provider is working on it,ACTIONABLE,RESOLVED,0.714221
2021,INC64341450,GCA 7 (Delivery sheet) printing delay issue,Printer drivers were updated and issue resolved.,ACTIONABLE,ESCALATED,0.680299
1092,INC69346363,Printer Issue,Issue solved,GENERIC,RESOLVED,0.673956

In [51]:
import numpy as np

np.save("../data/ticket_embeddings.npy", embeddings)
np.save("../data/solution_embeddings.npy", solution_embeddings)

print("Embeddings sauvegardés avec succès !")

Embeddings sauvegardés avec succès !

In [52]:
# ==============================
# RECHERCHE SEMANTIQUE DES TICKETS
# ==============================

import numpy as np


def search_similar_tickets(query, top_k=10):
    """
    Recherche les tickets historiques les plus similaires
    à une nouvelle demande grâce aux embeddings.
    """

    # Embedding de la nouvelle requête
    query_embedding = model.encode(
        [str(query)],
        normalize_embeddings=True
    )[0]

    # Normalisation des embeddings historiques
    ticket_embeddings_norm = (
        embeddings
        / np.linalg.norm(
            embeddings,
            axis=1,
            keepdims=True
        )
    )

    # Similarité cosinus
    similarities = (
        ticket_embeddings_norm @ query_embedding
    )

    # Indices des tickets les plus similaires
    top_indices = np.argsort(
        similarities
    )[::-1][:top_k]

    # Résultats
    results = knowledge_base.iloc[top_indices].copy()

    results["Similarity"] = similarities[top_indices]

    return results[
        [
            "Number",
            "Short Description",
            "Solution",
            "solution_type",
            "source",
            "Similarity"
        ]
    ]

In [53]:
query = """
GCA printer is not working and delivery sheets cannot be printed.
"""

results = search_similar_tickets(
    query,
    top_k=10
)

print(
    results.to_string(index=False)
)

     Number                                                                           Short Description                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                Solution solution_type    source  Similarity
INC66310792                          Issue printing Delivery Sheet from GCA - (GCA Printer :  maagapr1)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      Printer has been fixed.\nResolved.    ACTIONABLE ESCALATED    0.780634
INC65363499                                       Issue printing from GCA after printer model changed !                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    Printer setup has been updated and it is working now.\n\nResolved.\n    ACTIONABLE ESCALATED    0.663335

In [54]:
# ==============================
# RANKING DES SOLUTIONS
# ==============================

def rank_solution_candidates(
    query,
    top_k_tickets=50,
    n_recommendations=5
):
    """
    Recherche les tickets les plus similaires puis
    retourne les meilleures solutions ACTIONABLE.

    Le classement principal est basé sur la similarité
    sémantique entre le nouveau ticket et les tickets historiques.
    """

    # 1. Recherche sémantique
    candidates = search_similar_tickets(
        query,
        top_k=top_k_tickets
    ).copy()

    # 2. Garder uniquement les solutions exploitables
    actionable = candidates[
        candidates["solution_type"] == "ACTIONABLE"
    ].copy()

    # 3. Trier par similarité sémantique
    actionable = actionable.sort_values(
        "Similarity",
        ascending=False
    )

    # 4. Garder les meilleures recommandations
    recommendations = actionable.head(
        n_recommendations
    ).copy()

    return recommendations[
        [
            "Number",
            "Short Description",
            "Solution",
            "source",
            "solution_type",
            "Similarity"
        ]
    ]

In [55]:
# ==============================
# TEST DU RANKING
# ==============================

query = """
GCA printer is not working and delivery sheets cannot be printed.
"""

recommendations = rank_solution_candidates(
    query,
    top_k_tickets=50,
    n_recommendations=5
)

print(
    recommendations.to_string(index=False)
)

     Number                                                  Short Description                                                                                                                                                                                                                                                                                                                                                                                                                                                                          Solution    source solution_type  Similarity
INC66310792 Issue printing Delivery Sheet from GCA - (GCA Printer :  maagapr1)                                                                                                                                                                                                                                                                                                                                                                                                                                                Printer has been fixed.\nResolved. ESCALATED    ACTIONABLE    0.780634
INC65363499              Issue printing from GCA after printer model changed !                                                                                                                                                                                                                                                                                                                                                                                                              Printer setup has been updated and it is working now.\n\nResolved.\n ESCALATED    ACTIONABLE    0.663335
INC66441487                                            Print issue in GCA7 app                                                                                                                                                                                                                                                                                                                                                                                                                                                      TN Provider is working on it  RESOLVED    ACTIONABLE    0.645664
INC64341450                        GCA 7 (Delivery sheet) printing delay issue                                                                                                                                                                                                                                                                                                                                                                                                                                  Printer drivers were updated and issue resolved. ESCALATED    ACTIONABLE    0.626882
INC65033159                        GCA 7 (Delivery sheet) printing delay issue Mentioned printers were recreated on both servers as requested.\n\ndevice for matngpr3: beh:/1/0/60/socket://23.82.14.5:9100\ndevice for matngpr4: beh:/1/0/60/socket://23.82.14.6:9100\nmatngpr3 accepting requests since Mon 04 Aug 2025 02:03:25 PM GMT\nmatngpr4 accepting requests since Mon 04 Aug 2025 02:03:32 PM GMT\nprinter matngpr3 is idle.  enabled since Mon 04 Aug 2025 02:03:25 PM GMT\nprinter matngpr4 is idle.  enabled since Mon 04 Aug 2025 02:03:32 PM GMT ESCALATED    ACTIONABLE    0.623463

In [56]:
# ==============================
# REGROUPEMENT DES SOLUTIONS
# ==============================

from sklearn.metrics.pairwise import cosine_similarity
import numpy as np
import pandas as pd


def get_solution_candidates(
    query,
    top_k_tickets=20
):
    """
    1. Recherche les tickets les plus similaires au nouveau ticket.
    2. Récupère leurs solutions.
    """

    # Embedding du nouveau ticket
    query_embedding = model.encode(
        [query],
        normalize_embeddings=True
    )[0]

    # Normaliser les embeddings des tickets
    ticket_embeddings_norm = (
        embeddings /
        np.linalg.norm(
            embeddings,
            axis=1,
            keepdims=True
        )
    )

    # Similarité ticket ↔ nouveau ticket
    similarities = (
        ticket_embeddings_norm @ query_embedding
    )

    # Top tickets
    top_indices = np.argsort(
        similarities
    )[::-1][:top_k_tickets]

    candidates = knowledge_base.iloc[
        top_indices
    ].copy()

    candidates["Ticket_Similarity"] = (
        similarities[top_indices]
    )

    # Garder uniquement les solutions exploitables
    candidates = candidates[
        candidates["solution_type"] == "ACTIONABLE"
    ].copy()

    return candidates

In [57]:
query = """
GCA printer is not working and delivery sheets cannot be printed.
"""

solution_candidates = get_solution_candidates(
    query,
    top_k_tickets=20
)

print(
    solution_candidates[
        [
            "Number",
            "Short Description",
            "Solution",
            "Ticket_Similarity",
            "source",
            "solution_type"
        ]
    ].to_string(index=False)
)

     Number                                                                           Short Description                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                Solution  Ticket_Similarity    source solution_type
INC66310792                          Issue printing Delivery Sheet from GCA - (GCA Printer :  maagapr1)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      Printer has been fixed.\nResolved.           0.780634 ESCALATED    ACTIONABLE
INC65363499                                       Issue printing from GCA after printer model changed !                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    Printer setup has been updated and it is working now.\n\nResolved.\n           0.663335 ESCALATED    ACTIONABLE

In [58]:
# ==========================================
# MOTEUR DE RECOMMANDATION DE SOLUTION
# ==========================================

def recommend_solutions(
    query,
    top_k_tickets=20,
    top_k_solutions=5
):
    """
    Recherche les incidents historiques les plus proches
    et retourne les solutions ACTIONABLE les plus pertinentes.
    """

    # --------------------------------------
    # 1. Embedding du nouveau ticket
    # --------------------------------------

    query_embedding = model.encode(
        [query],
        normalize_embeddings=True
    )[0]

    # --------------------------------------
    # 2. Normalisation des embeddings tickets
    # --------------------------------------

    ticket_embeddings_norm = (
        embeddings /
        np.linalg.norm(
            embeddings,
            axis=1,
            keepdims=True
        )
    )

    # --------------------------------------
    # 3. Similarité nouveau ticket /
    #    tickets historiques
    # --------------------------------------

    ticket_similarities = (
        ticket_embeddings_norm @ query_embedding
    )

    # --------------------------------------
    # 4. Récupération des tickets similaires
    # --------------------------------------

    top_indices = np.argsort(
        ticket_similarities
    )[::-1][:top_k_tickets]

    candidates = knowledge_base.iloc[
        top_indices
    ].copy()

    candidates["Ticket_Similarity"] = (
        ticket_similarities[top_indices]
    )

    # --------------------------------------
    # 5. Garder les solutions exploitables
    # --------------------------------------

    actionable = candidates[
        candidates["solution_type"] == "ACTIONABLE"
    ].copy()

    # --------------------------------------
    # 6. Embedding de la solution du ticket
    #    par rapport à la solution des candidats
    # --------------------------------------

    solution_similarities = []

    for idx in actionable.index:

        solution_embedding = solution_embeddings[idx]

        similarity = np.dot(
            solution_embedding,
            query_embedding
        )

        solution_similarities.append(
            similarity
        )

    actionable["Solution_Similarity"] = (
        solution_similarities
    )

    # --------------------------------------
    # 7. Affichage des meilleures solutions
    # --------------------------------------

    actionable = actionable.sort_values(
        "Ticket_Similarity",
        ascending=False
    )

    return actionable[
        [
            "Number",
            "Short Description",
            "Solution",
            "Ticket_Similarity",
            "Solution_Similarity",
            "source",
            "solution_type"
        ]
    ].head(top_k_solutions)

In [59]:
# ==========================================
# TEST DU MOTEUR DE RECOMMANDATION
# ==========================================

query = """
GCA printer is not working and delivery sheets cannot be printed.
"""

recommendations = recommend_solutions(
    query,
    top_k_tickets=20,
    top_k_solutions=5
)

print(
    recommendations.to_string(index=False)
)

     Number                                                  Short Description                                                                                                                                                                                                                                                                                                                                                                                                                                                                          Solution  Ticket_Similarity  Solution_Similarity    source solution_type
INC66310792 Issue printing Delivery Sheet from GCA - (GCA Printer :  maagapr1)                                                                                                                                                                                                                                                                                                                                                                                                                                                Printer has been fixed.\nResolved.           0.780634             0.380906 ESCALATED    ACTIONABLE
INC65363499              Issue printing from GCA after printer model changed !                                                                                                                                                                                                                                                                                                                                                                                                              Printer setup has been updated and it is working now.\n\nResolved.\n           0.663335             0.486837 ESCALATED    ACTIONABLE
INC66441487                                            Print issue in GCA7 app                                                                                                                                                                                                                                                                                                                                                                                                                                                      TN Provider is working on it           0.645664             0.072959  RESOLVED    ACTIONABLE
INC64341450                        GCA 7 (Delivery sheet) printing delay issue                                                                                                                                                                                                                                                                                                                                                                                                                                  Printer drivers were updated and issue resolved.           0.626882             0.404076 ESCALATED    ACTIONABLE
INC65033159                        GCA 7 (Delivery sheet) printing delay issue Mentioned printers were recreated on both servers as requested.\n\ndevice for matngpr3: beh:/1/0/60/socket://23.82.14.5:9100\ndevice for matngpr4: beh:/1/0/60/socket://23.82.14.6:9100\nmatngpr3 accepting requests since Mon 04 Aug 2025 02:03:25 PM GMT\nmatngpr4 accepting requests since Mon 04 Aug 2025 02:03:32 PM GMT\nprinter matngpr3 is idle.  enabled since Mon 04 Aug 2025 02:03:25 PM GMT\nprinter matngpr4 is idle.  enabled since Mon 04 Aug 2025 02:03:32 PM GMT           0.623463             0.417884 ESCALATED    ACTIONABLE

In [60]:
# ==========================================
# ANALYSE DES CANDIDATS DE RECOMMANDATION
# ==========================================

query = """
GCA printer is not working and delivery sheets cannot be printed.
"""

# Récupérer les 20 tickets les plus similaires
candidates = search_similar_tickets(
    query,
    top_k=20
).copy()

print("===== 20 TICKETS LES PLUS SIMILAIRES =====\n")

print(
    candidates[
        [
            "Number",
            "Short Description",
            "Solution",
            "source",
            "solution_type",
            "Similarity"
        ]
    ].to_string(index=False)
)

print("\n\n===== REPARTITION DES CANDIDATS =====\n")

print("Par source :")
print(
    candidates["source"].value_counts()
)

print("\nPar type de solution :")
print(
    candidates["solution_type"].value_counts()
)

===== 20 TICKETS LES PLUS SIMILAIRES =====

     Number                                                                           Short Description                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                Solution    source  solution_type  Similarity
INC66310792                          Issue printing Delivery Sheet from GCA - (GCA Printer :  maagapr1)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      Printer has been fixed.\nResolved. ESCALATED     ACTIONABLE    0.780634
INC65363499                                       Issue printing from GCA after printer model changed !                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    Printer setup has been updated and it is working now.\n\nResolved.\n ESCALATED     ACTIONABLE    0.663335

In [61]:
# ==========================================
# ANALYSE DES SOLUTIONS ACTIONABLE
# ==========================================

actionable_candidates = candidates[
    candidates["solution_type"] == "ACTIONABLE"
].copy()

actionable_candidates = actionable_candidates.sort_values(
    "Similarity",
    ascending=False
)

print("===== SOLUTIONS ACTIONABLE DES TICKETS SIMILAIRES =====\n")

for i, (_, row) in enumerate(
    actionable_candidates.iterrows(),
    start=1
):

    print("=" * 80)

    print(f"RANG : {i}")
    print(f"TICKET : {row['Number']}")
    print(f"SIMILARITE : {row['Similarity']:.4f}")
    print(f"SOURCE : {row['source']}")

    print("\nPROBLEME :")
    print(row["Short Description"])

    print("\nSOLUTION :")
    print(row["Solution"])

    print()

===== SOLUTIONS ACTIONABLE DES TICKETS SIMILAIRES =====

================================================================================
RANG : 1
TICKET : INC66310792
SIMILARITE : 0.7806
SOURCE : ESCALATED

PROBLEME :
Issue printing Delivery Sheet from GCA - (GCA Printer :  maagapr1)

SOLUTION :
Printer has been fixed.
Resolved.

================================================================================
RANG : 2
TICKET : INC65363499
SIMILARITE : 0.6633
SOURCE : ESCALATED

PROBLEME :
Issue printing from GCA after printer model changed !

SOLUTION :
Printer setup has been updated and it is working now.

Resolved.


================================================================================
RANG : 3
TICKET : INC66441487
SIMILARITE : 0.6457
SOURCE : RESOLVED

PROBLEME :
Print issue in GCA7 app

SOLUTION :
TN Provider is working on it

================================================================================
RANG : 4
TICKET : INC64341450
SIMILARITE : 0.6269
SOURCE : ESCALATED

PROBLEME :
GCA 7 (Delivery sheet) printing delay issue

SOLUTION :
Printer drivers were updated and issue resolved.

================================================================================
RANG : 5
TICKET : INC65033159
SIMILARITE : 0.6235
SOURCE : ESCALATED

PROBLEME :
GCA 7 (Delivery sheet) printing delay issue

SOLUTION :
Mentioned printers were recreated on both servers as requested.

device for matngpr3: beh:/1/0/60/socket://23.82.14.5:9100
device for matngpr4: beh:/1/0/60/socket://23.82.14.6:9100
matngpr3 accepting requests since Mon 04 Aug 2025 02:03:25 PM GMT
matngpr4 accepting requests since Mon 04 Aug 2025 02:03:32 PM GMT
printer matngpr3 is idle.  enabled since Mon 04 Aug 2025 02:03:25 PM GMT
printer matngpr4 is idle.  enabled since Mon 04 Aug 2025 02:03:32 PM GMT

================================================================================
RANG : 6
TICKET : INC64304524
SIMILARITE : 0.5853
SOURCE : ESCALATED

PROBLEME :
RW printer not print from DCVS

SOLUTION :
Dear colleague, because the required information needed to resolve your INC ticket was not provided by you, this ticket was set to status 'Resolved' by the Rule of 3 Automation in accordance with the Incident Management Process. However, if your issue persists, please contact your home Service Desk. Thank you.

================================================================================
RANG : 7
TICKET : INC65410555
SIMILARITE : 0.5836
SOURCE : ESCALATED

PROBLEME :
Request to change printer model for GCA printers (marbapr1, MAKENPR1, marakpr1, mafezpr1  )

SOLUTION :
As per the request printer driver updated

[root@mykullspc000484 ~]# lpoptions -p marbapr1
copies=1 device-uri=beh:/1/0/60/socket://23.82.70.235:9100 Duplex=none Duplex/Duplex=none finishings=3 job-cancel-after=10800 job-hold-until=no-hold job-priority=50 job-sheets=none,none marker-change-time=0 media=na_letter_8.5x11in number-up=1 printer-commands=AutoConfigure,Clean,PrintSelfTestPage printer-info=marbapr1 printer-is-accepting-jobs=true printer-is-shared=true printer-is-temporary=false printer-location printer-make-and-model='Generic PCL 6/PCL XL Printer Foomatic/ljet4' printer-state=3 printer-state-change-time=1756899319 printer-state-reasons=none printer-type=8433684 printer-uri-supported=ipp://localhost/printers/marbapr1
[root@mykullspc000484 ~]# lpoptions -p makenpr1
copies=1 device-uri=beh:/1/0/60/socket://23.82.61.235:9100 finishings=3 job-cancel-after=10800 job-hold-until=no-hold job-priority=50 job-sheets=none,none marker-change-time=0 media=na_letter_8.5x11in number-up=1 printer-commands=AutoConfigure,Clean,PrintSelfTestPage printer-info=makenpr1 printer-is-accepting-jobs=true printer-is-shared=true printer-is-temporary=false printer-location printer-make-and-model='Generic PCL 6/PCL XL Printer Foomatic/ljet4' printer-state=3 printer-state-change-time=1756899324 printer-state-reasons=none printer-type=8433684 printer-uri-supported=ipp://localhost/printers/makenpr1
[root@mykullspc000484 ~]# lpoptions -p marakpr1
copies=1 device-uri=beh:/1/0/60/socket://23.82.50.235:9100 finishings=3 job-cancel-after=10800 job-hold-until=no-hold job-priority=50 job-sheets=none,none marker-change-time=0 media=na_letter_8.5x11in number-up=1 printer-commands=AutoConfigure,Clean,PrintSelfTestPage printer-info=marakpr1 printer-is-accepting-jobs=true printer-is-shared=true printer-is-temporary=false printer-location printer-make-and-model='Generic PCL 6/PCL XL Printer Foomatic/ljet4' printer-state=3 printer-state-change-time=1756899330 printer-state-reasons=none printer-type=8433684 printer-uri-supported=ipp://localhost/printers/marakpr1
[root@mykullspc000484 ~]# lpoptions -p mafezpr1
copies=1 device-uri=beh:/1/0/60/socket://23.82.246.234:9100 finishings=3 job-cancel-after=10800 job-hold-until=no-hold job-priority=50 job-sheets=none,none marker-change-time=0 media=na_letter_8.5x11in number-up=1 printer-commands=AutoConfigure,Clean,PrintSelfTestPage printer-info=mafezpr1 printer-is-accepting-jobs=true printer-is-shared=true printer-is-temporary=false printer-location printer-make-and-model='Generic PCL 6/PCL XL Printer Foomatic/ljet4' printer-state=3 printer-state-change-time=1756899335 printer-state-reasons=none printer-type=8433684 printer-uri-supported=ipp://localhost/printers/mafezpr1
[root@mykullspc000484 ~]#

[root@mykullspc000483 model]# lpoptions -p marbapr1
copies=1 device-uri=beh:/1/0/60/socket://23.82.70.235:9100 Duplex=none Duplex/Duplex=none finishings=3 job-cancel-after=10800 job-hold-until=no-hold job-priority=50 job-sheets=none,none marker-change-time=0 media=na_letter_8.5x11in number-up=1 printer-commands=AutoConfigure,Clean,PrintSelfTestPage printer-info=marbapr1 printer-is-accepting-jobs=true printer-is-shared=true printer-is-temporary=false printer-location printer-make-and-model='Generic PCL 6/PCL XL Printer Foomatic/ljet4' printer-state=3 printer-state-change-time=1756899058 printer-state-reasons=none printer-type=8433684 printer-uri-supported=ipp://localhost/printers/marbapr1
[root@mykullspc000483 model]# lpoptions -p makenpr1
copies=1 device-uri=beh:/1/0/60/socket://23.82.61.235:9100 finishings=3 job-cancel-after=10800 job-hold-until=no-hold job-priority=50 job-sheets=none,none marker-change-time=0 media=na_letter_8.5x11in number-up=1 printer-commands=AutoConfigure,Clean,PrintSelfTestPage printer-info=makenpr1 printer-is-accepting-jobs=true printer-is-shared=true printer-is-temporary=false printer-location printer-make-and-model='Generic PCL 6/PCL XL Printer Foomatic/ljet4' printer-state=3 printer-state-change-time=1756899091 printer-state-reasons=none printer-type=8433684 printer-uri-supported=ipp://localhost/printers/makenpr1
[root@mykullspc000483 model]# lpoptions -p marakpr1
copies=1 device-uri=beh:/1/0/60/socket://23.82.50.235:9100 finishings=3 job-cancel-after=10800 job-hold-until=no-hold job-priority=50 job-sheets=none,none marker-change-time=0 media=na_letter_8.5x11in number-up=1 printer-commands=AutoConfigure,Clean,PrintSelfTestPage printer-info=marakpr1 printer-is-accepting-jobs=true printer-is-shared=true printer-is-temporary=false printer-location printer-make-and-model='Generic PCL 6/PCL XL Printer Foomatic/ljet4' printer-state=3 printer-state-change-time=1756899138 printer-state-reasons=none printer-type=8433684 printer-uri-supported=ipp://localhost/printers/marakpr1
[root@mykullspc000483 model]# lpoptions -p mafezpr1
copies=1 device-uri=beh:/1/0/60/socket://23.82.246.234:9100 finishings=3 job-cancel-after=10800 job-hold-until=no-hold job-priority=50 job-sheets=none,none marker-change-time=0 media=na_letter_8.5x11in number-up=1 printer-commands=AutoConfigure,Clean,PrintSelfTestPage printer-info=mafezpr1 printer-is-accepting-jobs=true printer-is-shared=true printer-is-temporary=false printer-location printer-make-and-model='Generic PCL 6/PCL XL Printer Foomatic/ljet4' printer-state=3 printer-state-change-time=1756899190 printer-state-reasons=none printer-type=8433684 printer-uri-supported=ipp://localhost/printers/mafezpr1
[root@mykullspc000483 model]#


If you have been satisfied and happy with fast solution, please award us with 5*. Thank you very much.


================================================================================
RANG : 8
TICKET : INC61302569
SIMILARITE : 0.5833
SOURCE : ESCALATED

PROBLEME :
Add printers on GCA7 app

SOLUTION :
Completed, printers installed on demanded servers:
MAKENPR4
----------
device for MAKENPR4: beh:/1/0/60/socket://23.82.61.234:9100
MAKENPR4 accepting requests since Wed 16 Oct 2024 10:33:21 PM GMT
printer MAKENPR4 is idle.  enabled since Wed 16 Oct 2024 10:33:21 PM GMT
MAKENPR3
----------
device for MAKENPR3: beh:/1/0/60/socket://23.82.61.235:9100
MAKENPR3 accepting requests since Wed 16 Oct 2024 10:33:21 PM GMT
printer MAKENPR3 is idle.  enabled since Wed 16 Oct 2024 10:33:21 PM GMT
MARAKPR4
----------
device for MARAKPR4: beh:/1/0/60/socket://23.82.50.234:9100
MARAKPR4 accepting requests since Wed 16 Oct 2024 10:33:21 PM GMT
printer MARAKPR4 is idle.  enabled since Wed 16 Oct 2024 10:33:21 PM GMT
MARAKPR3
----------
device for MARAKPR3: beh:/1/0/60/socket://23.82.50.235:9100
MARAKPR3 accepting requests since Wed 16 Oct 2024 10:33:21 PM GMT
printer MARAKPR3 is idle.  enabled since Wed 16 Oct 2024 10:33:21 PM GMT
MAAGAPR4
----------
device for MAAGAPR4: beh:/1/0/60/socket://23.82.240.234:9100
MAAGAPR4 accepting requests since Wed 16 Oct 2024 10:33:21 PM GMT
printer MAAGAPR4 is idle.  enabled since Wed 16 Oct 2024 10:33:21 PM GMT
MAAGAPR3
----------
device for MAAGAPR3: beh:/1/0/60/socket://23.82.240.235:9100
MAAGAPR3 accepting requests since Wed 16 Oct 2024 10:33:22 PM GMT
printer MAAGAPR3 is idle.  enabled since Wed 16 Oct 2024 10:33:22 PM GMT


================================================================================
RANG : 9
TICKET : INC61933011
SIMILARITE : 0.5750
SOURCE : ESCALATED

PROBLEME :
Printer not responding

SOLUTION :
Hello,
We found that source IPs are not added in the ELR.
That's the reason why the connection is not working properly.
SAEAS team help to add the addresses to ELR and user was informed about the RFC process during change freeze.

================================================================================
RANG : 10
TICKET : INC65461130
SIMILARITE : 0.5658
SOURCE : ESCALATED

PROBLEME :
Request to change printer model for GCA printers (magtwpr1, magtwpr2, magtwpr3, macaspr2 )

SOLUTION :
Get sys admin to update the driver based on the new printers (different model than the previous).

In [62]:
# ==========================================
# MOTEUR DE RECOMMANDATION V2
# ==========================================

def recommend_solutions_v2(
    query,
    top_k_tickets=50,
    top_k_solutions=5,
    ticket_weight=0.70,
    solution_weight=0.30
):
    """
    Recherche les tickets historiques similaires,
    puis classe les solutions ACTIONABLE selon
    un score combinant :

        70% : similarité du ticket
        30% : similarité de la solution
    """

    # --------------------------------------
    # 1. Embedding du nouveau ticket
    # --------------------------------------

    query_embedding = model.encode(
        [query],
        normalize_embeddings=True
    )[0]

    # --------------------------------------
    # 2. Normalisation des embeddings tickets
    # --------------------------------------

    ticket_embeddings_norm = (
        embeddings /
        np.linalg.norm(
            embeddings,
            axis=1,
            keepdims=True
        )
    )

    # --------------------------------------
    # 3. Similarité nouveau ticket /
    #    tickets historiques
    # --------------------------------------

    ticket_similarities = (
        ticket_embeddings_norm @ query_embedding
    )

    # --------------------------------------
    # 4. Récupération des tickets similaires
    # --------------------------------------

    top_indices = np.argsort(
        ticket_similarities
    )[::-1][:top_k_tickets]

    candidates = knowledge_base.iloc[
        top_indices
    ].copy()

    candidates["Ticket_Similarity"] = (
        ticket_similarities[top_indices]
    )

    # --------------------------------------
    # 5. Garder uniquement ACTIONABLE
    # --------------------------------------

    actionable = candidates[
        candidates["solution_type"] == "ACTIONABLE"
    ].copy()

    # --------------------------------------
    # 6. Similarité entre la solution
    #    historique et le nouveau ticket
    # --------------------------------------

    solution_similarities = []

    for idx in actionable.index:

        solution_embedding = solution_embeddings[idx]

        similarity = np.dot(
            solution_embedding,
            query_embedding
        )

        solution_similarities.append(
            similarity
        )

    actionable["Solution_Similarity"] = (
        solution_similarities
    )

    # --------------------------------------
    # 7. SCORE FINAL
    # --------------------------------------

    actionable["Final_Score"] = (
        ticket_weight *
        actionable["Ticket_Similarity"]
        +
        solution_weight *
        actionable["Solution_Similarity"]
    )

    # --------------------------------------
    # 8. Trier par score final
    # --------------------------------------

    actionable = actionable.sort_values(
        "Final_Score",
        ascending=False
    )

    # --------------------------------------
    # 9. Retourner les meilleures solutions
    # --------------------------------------

    return actionable[
        [
            "Number",
            "Short Description",
            "Solution",
            "Ticket_Similarity",
            "Solution_Similarity",
            "Final_Score",
            "source",
            "solution_type"
        ]
    ].head(top_k_solutions)

In [63]:
query = """
GCA printer is not working and delivery sheets cannot be printed.
"""

recommendations = recommend_solutions_v2(
    query,
    top_k_tickets=50,
    top_k_solutions=5
)

print(
    recommendations.to_string(index=False)
)

     Number                                                  Short Description                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               Solution  Ticket_Similarity  Solution_Similarity  Final_Score    source solution_type
INC66310792 Issue printing Delivery Sheet from GCA - (GCA Printer :  maagapr1)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     Printer has been fixed.\nResolved.           0.780634             0.380906     0.660716 ESCALATED    ACTIONABLE
INC65363499              Issue printing from GCA after printer model changed !                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   Printer setup has been updated and it is working now.\n\nResolved.\n           0.663335             0.486837     0.610386 ESCALATED    ACTIONABLE
INC65033159                        GCA 7 (Delivery sheet) printing delay issue                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      Mentioned printers were recreated on both servers as requested.\n\ndevice for matngpr3: beh:/1/0/60/socket://23.82.14.5:9100\ndevice for matngpr4: beh:/1/0/60/socket://23.82.14.6:9100\nmatngpr3 accepting requests since Mon 04 Aug 2025 02:03:25 PM GMT\nmatngpr4 accepting requests since Mon 04 Aug 2025 02:03:32 PM GMT\nprinter matngpr3 is idle.  enabled since Mon 04 Aug 2025 02:03:25 PM GMT\nprinter matngpr4 is idle.  enabled since Mon 04 Aug 2025 02:03:32 PM GMT           0.623463             0.417884     0.561789 ESCALATED    ACTIONABLE
INC64341450                        GCA 7 (Delivery sheet) printing delay issue                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       Printer drivers were updated and issue resolved.           0.626882             0.404076     0.560041 ESCALATED    ACTIONABLE
INC61302569                                           Add printers on GCA7 app Completed, printers installed on demanded servers:\nMAKENPR4\n----------\ndevice for MAKENPR4: beh:/1/0/60/socket://23.82.61.234:9100\nMAKENPR4 accepting requests since Wed 16 Oct 2024 10:33:21 PM GMT\nprinter MAKENPR4 is idle.  enabled since Wed 16 Oct 2024 10:33:21 PM GMT\nMAKENPR3\n----------\ndevice for MAKENPR3: beh:/1/0/60/socket://23.82.61.235:9100\nMAKENPR3 accepting requests since Wed 16 Oct 2024 10:33:21 PM GMT\nprinter MAKENPR3 is idle.  enabled since Wed 16 Oct 2024 10:33:21 PM GMT\nMARAKPR4\n----------\ndevice for MARAKPR4: beh:/1/0/60/socket://23.82.50.234:9100\nMARAKPR4 accepting requests since Wed 16 Oct 2024 10:33:21 PM GMT\nprinter MARAKPR4 is idle.  enabled since Wed 16 Oct 2024 10:33:21 PM GMT\nMARAKPR3\n----------\ndevice for MARAKPR3: beh:/1/0/60/socket://23.82.50.235:9100\nMARAKPR3 accepting requests since Wed 16 Oct 2024 10:33:21 PM GMT\nprinter MARAKPR3 is idle.  enabled since Wed 16 Oct 2024 10:33:21 PM GMT\nMAAGAPR4\n----------\ndevice for MAAGAPR4: beh:/1/0/60/socket://23.82.240.234:9100\nMAAGAPR4 accepting requests since Wed 16 Oct 2024 10:33:21 PM GMT\nprinter MAAGAPR4 is idle.  enabled since Wed 16 Oct 2024 10:33:21 PM GMT\nMAAGAPR3\n----------\ndevice for MAAGAPR3: beh:/1/0/60/socket://23.82.240.235:9100\nMAAGAPR3 accepting requests since Wed 16 Oct 2024 10:33:22 PM GMT\nprinter MAAGAPR3 is idle.  enabled since Wed 16 Oct 2024 10:33:22 PM GMT\n           0.583277             0.429939     0.537275 ESCALATED    ACTIONABLE

In [64]:
# ==========================================
# COMPARAISON DES SOLUTIONS HISTORIQUES
# ==========================================

from sklearn.metrics.pairwise import cosine_similarity
import numpy as np


def compare_historical_solutions(
    query,
    top_k_tickets=20,
    min_ticket_similarity=0.50
):
    """
    1. Recherche les tickets historiques similaires au nouveau ticket.
    2. Garde uniquement les solutions ACTIONABLE.
    3. Compare les solutions ACTIONABLE entre elles.
    """

    # --------------------------------------
    # 1. Embedding du nouveau ticket
    # --------------------------------------

    query_embedding = model.encode(
        [query],
        normalize_embeddings=True
    )[0]

    # --------------------------------------
    # 2. Normalisation des embeddings tickets
    # --------------------------------------

    ticket_embeddings_norm = (
        embeddings /
        np.linalg.norm(
            embeddings,
            axis=1,
            keepdims=True
        )
    )

    # --------------------------------------
    # 3. Similarité nouveau ticket /
    #    historique
    # --------------------------------------

    ticket_similarities = (
        ticket_embeddings_norm @ query_embedding
    )

    # --------------------------------------
    # 4. Récupérer les tickets similaires
    # --------------------------------------

    top_indices = np.argsort(
        ticket_similarities
    )[::-1][:top_k_tickets]

    candidates = knowledge_base.iloc[
        top_indices
    ].copy()

    candidates["Ticket_Similarity"] = (
        ticket_similarities[top_indices]
    )

    # --------------------------------------
    # 5. Seuil de similarité ticket
    # --------------------------------------

    candidates = candidates[
        candidates["Ticket_Similarity"]
        >= min_ticket_similarity
    ].copy()

    # --------------------------------------
    # 6. Garder ACTIONABLE
    # --------------------------------------

    actionable = candidates[
        candidates["solution_type"] == "ACTIONABLE"
    ].copy()

    # --------------------------------------
    # 7. Similarité entre solutions
    # --------------------------------------

    solution_indices = actionable.index.tolist()

    if len(solution_indices) == 0:
        print("Aucune solution ACTIONABLE trouvée.")
        return None, None

    historical_solution_embeddings = (
        solution_embeddings[solution_indices]
    )

    solution_matrix = cosine_similarity(
        historical_solution_embeddings
    )

    # --------------------------------------
    # 8. Matrice de similarité
    # --------------------------------------

    solution_numbers = actionable["Number"].tolist()

    solution_similarity_df = pd.DataFrame(
        solution_matrix,
        index=solution_numbers,
        columns=solution_numbers
    )

    return actionable, solution_similarity_df

In [65]:
query = """
GCA printer is not working and delivery sheets cannot be printed.
"""

actionable, solution_similarity_matrix = (
    compare_historical_solutions(
        query,
        top_k_tickets=20,
        min_ticket_similarity=0.50
    )
)

print("===== SOLUTIONS HISTORIQUES =====")

print(
    actionable[
        [
            "Number",
            "Short Description",
            "Solution",
            "Ticket_Similarity"
        ]
    ].to_string(index=False)
)

===== SOLUTIONS HISTORIQUES =====
     Number                                                                           Short Description                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                Solution  Ticket_Similarity
INC66310792                          Issue printing Delivery Sheet from GCA - (GCA Printer :  maagapr1)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      Printer has been fixed.\nResolved.           0.780634
INC65363499                                       Issue printing from GCA after printer model changed !                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    Printer setup has been updated and it is working now.\n\nResolved.\n           0.663335

In [66]:
print("\n===== MATRICE DE SIMILARITÉ DES SOLUTIONS =====")

print(
    solution_similarity_matrix.round(3)
)

===== MATRICE DE SIMILARITÉ DES SOLUTIONS =====
             INC66310792  INC65363499  INC66441487  INC64341450  INC65033159  \
INC66310792        1.000        0.833        0.199        0.823        0.489
INC65363499        0.833        1.000        0.277        0.824        0.603
INC66441487        0.199        0.277        1.000        0.209        0.207
INC64341450        0.823        0.824        0.209        1.000        0.509
INC65033159        0.489        0.603        0.207        0.509        1.000
INC64304524        0.459        0.307        0.268        0.418        0.192
INC65410555        0.407        0.406        0.123        0.389        0.570
INC61302569        0.468        0.609        0.216        0.490        0.807
INC61933011        0.167        0.220        0.297        0.217        0.189
INC65461130        0.327        0.467        0.231        0.602        0.423

             INC64304524  INC65410555  INC61302569  INC61933011  INC65461130
INC66310792        0.459        0.407        0.468        0.167        0.327
INC65363499        0.307        0.406        0.609        0.220        0.467
INC66441487        0.268        0.123        0.216        0.297        0.231
INC64341450        0.418        0.389        0.490        0.217        0.602
INC65033159        0.192        0.570        0.807        0.189        0.423
INC64304524        1.000        0.270        0.212        0.277        0.184
INC65410555        0.270        1.000        0.597        0.157        0.308
INC61302569        0.212        0.597        1.000        0.190        0.366
INC61933011        0.277        0.157        0.190        1.000        0.150
INC65461130        0.184        0.308        0.366        0.150        1.000

In [67]:
# ==========================================
# REGROUPEMENT DES SOLUTIONS SIMILAIRES
# ==========================================

from sklearn.cluster import AgglomerativeClustering


def cluster_similar_solutions(
    solution_similarity_matrix,
    threshold=0.75
):
    """
    Regroupe les solutions historiques selon leur
    similarité sémantique.

    threshold = similarité minimale pour considérer
                deux solutions comme proches.
    """

    # Transformer similarité -> distance
    distance_matrix = (
        1 - solution_similarity_matrix.values
    )

    clustering = AgglomerativeClustering(
        n_clusters=None,
        metric="precomputed",
        linkage="average",
        distance_threshold=1 - threshold
    )

    labels = clustering.fit_predict(
        distance_matrix
    )

    clustered = solution_similarity_matrix.copy()

    clustered["Cluster"] = labels

    return clustered

In [68]:
clusters = cluster_similar_solutions(
    solution_similarity_matrix,
    threshold=0.75
)

print("===== GROUPES DE SOLUTIONS =====")

for cluster_id in sorted(clusters["Cluster"].unique()):

    tickets = clusters[
        clusters["Cluster"] == cluster_id
    ].index.tolist()

    print(f"\nCLUSTER {cluster_id}")
    print("-" * 40)

    for ticket in tickets:
        print(ticket)

===== GROUPES DE SOLUTIONS =====

CLUSTER 0
----------------------------------------
INC65033159
INC61302569

CLUSTER 1
----------------------------------------
INC65461130

CLUSTER 2
----------------------------------------
INC66310792
INC65363499
INC64341450

CLUSTER 3
----------------------------------------
INC66441487

CLUSTER 4
----------------------------------------
INC61933011

CLUSTER 5
----------------------------------------
INC64304524

CLUSTER 6
----------------------------------------
INC65410555

In [2]:
# ==========================================
# SCORE DES CLUSTERS DE SOLUTIONS
# ==========================================

def score_solution_clusters(
    actionable,
    clusters
):
    """
    Calcule les caractéristiques de chaque cluster
    de solutions.

    Le rattachement des tickets se fait via la colonne
    'Number' et non via l'index pandas.
    """

    cluster_results = []

    for cluster_id in sorted(
        clusters["Cluster"].unique()
    ):

        # --------------------------------------
        # 1. Tickets du cluster
        # --------------------------------------

        cluster_tickets = clusters[
            clusters["Cluster"] == cluster_id
        ].index.tolist()

        # --------------------------------------
        # 2. Récupérer les tickets dans actionable
        #    grâce à leur numéro
        # --------------------------------------

        cluster_data = actionable[
            actionable["Number"].isin(cluster_tickets)
        ].copy()

        # Si aucun ticket correspondant
        if cluster_data.empty:
            continue

        # --------------------------------------
        # 3. Pertinence des tickets
        # --------------------------------------

        ticket_similarity_mean = (
            cluster_data["Ticket_Similarity"].mean()
        )

        ticket_similarity_max = (
            cluster_data["Ticket_Similarity"].max()
        )

        # --------------------------------------
        # 4. Cohérence des solutions
        # --------------------------------------

        valid_tickets = cluster_data["Number"].tolist()

        if len(valid_tickets) > 1:

            matrix = solution_similarity_matrix.loc[
                valid_tickets,
                valid_tickets
            ].values

            upper_values = matrix[
                np.triu_indices(
                    len(matrix),
                    k=1
                )
            ]

            solution_coherence = upper_values.mean()

        else:

            solution_coherence = 1.0

        # --------------------------------------
        # 5. Nombre de tickets
        # --------------------------------------

        number_of_tickets = len(cluster_data)

        # --------------------------------------
        # 6. Résultat
        # --------------------------------------

        cluster_results.append({

            "Cluster": cluster_id,

            "Number_of_Tickets":
                number_of_tickets,

            "Ticket_Similarity_Mean":
                ticket_similarity_mean,

            "Ticket_Similarity_Max":
                ticket_similarity_max,

            "Solution_Coherence":
                solution_coherence
        })

    return pd.DataFrame(cluster_results)

In [3]:
cluster_scores = score_solution_clusters(
    actionable,
    clusters
)

print(
    cluster_scores.sort_values(
        "Ticket_Similarity_Mean",
        ascending=False
    ).to_string(index=False)
)

NameError: name 'actionable' is not defined

In [5]:
# ==========================================
# RESTAURATION DE L'ENVIRONNEMENT
# ==========================================

import pandas as pd
import numpy as np

from sentence_transformers import SentenceTransformer

print("Pandas :", pd.__version__)
print("NumPy :", np.__version__)

model = SentenceTransformer(
    "paraphrase-multilingual-MiniLM-L12-v2"
)

print("Modèle chargé !")

C:\Users\LENOVO\PycharmProjects\DHL_AI_Incident_Assistant\.venv311\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

Pandas : 3.0.5
NumPy : 2.4.6

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
Loading weights: 100%|██████████| 199/199 [00:00<00:00, 2705.03it/s]

Modèle chargé !

In [6]:
# ==========================================
# RECHARGEMENT DES DONNÉES
# ==========================================

resolved_df = pd.read_excel(
    "../data/Inc_resolved by MAIT.xlsx"
)

escalated_df = pd.read_excel(
    "../data/Inc_registred by MAIT.xlsx"
)

print("Tickets resolved :", len(resolved_df))
print("Tickets escalated :", len(escalated_df))

C:\Users\LENOVO\PycharmProjects\DHL_AI_Incident_Assistant\.venv311\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

Tickets resolved : 1813
Tickets escalated : 430

In [7]:
# ==========================================
# CLASSIFICATION DES SOLUTIONS
# ==========================================

def classify_solution(solution):
    solution = str(solution).strip().lower()

    # Solutions administratives
    administrative_keywords = [
        "duplicate",
        "duplicated",
        "close the ticket",
        "ticket to avoid",
        "no response from user",
        "regional ticket opened",
        "new ticket has been raised",
        "a new ticket has been raised",
        "data provided",
        "cancelled",
        "cancelled by"
    ]

    for keyword in administrative_keywords:
        if keyword in solution:
            return "ADMINISTRATIVE"

    # Solutions génériques
    generic_solutions = {
        "resolved",
        "resolved.",
        "resolved,",
        "solved",
        "solved.",
        "done",
        "done.",
        "fixed",
        "fixed.",
        "closed",
        "closed.",
        "granted",
        "access granted",
        "access granted.",
        "necessary done",
        "necessary done.",
        "necessaey done.",
        "issue fixed",
        "issue solved",
        "problem solved"
    }

    if solution in generic_solutions:
        return "GENERIC"

    if solution.startswith("resolved inc"):
        return "GENERIC"

    if solution.startswith("fixed inc"):
        return "GENERIC"

    return "ACTIONABLE"

In [8]:
resolved_df["solution_type"] = (
    resolved_df["Solution"]
    .apply(classify_solution)
)

escalated_df["solution_type"] = (
    escalated_df["Solution"]
    .apply(classify_solution)
)

resolved_df["source"] = "RESOLVED"
escalated_df["source"] = "ESCALATED"

knowledge_base = pd.concat(
    [
        resolved_df,
        escalated_df
    ],
    ignore_index=True
)

knowledge_base["text_for_embedding"] = (
    knowledge_base["Short Description"]
    .fillna("")
    .astype(str)
    + " "
    + knowledge_base["Description"]
    .fillna("")
    .astype(str)
)

print("Knowledge base :", knowledge_base.shape)
print("\nSource :")
print(knowledge_base["source"].value_counts())

print("\nSolution type :")
print(knowledge_base["solution_type"].value_counts())

Knowledge base : (2243, 14)

Source :
source
RESOLVED     1813
ESCALATED     430
Name: count, dtype: int64

Solution type :
solution_type
GENERIC           1393
ACTIONABLE         814
ADMINISTRATIVE      36
Name: count, dtype: int64

In [9]:
# ==========================================
# RECHARGEMENT DES EMBEDDINGS
# ==========================================

embeddings = np.load(
    "../data/ticket_embeddings.npy"
)

solution_embeddings = np.load(
    "../data/solution_embeddings.npy"
)

print("Ticket embeddings :", embeddings.shape)
print("Solution embeddings :", solution_embeddings.shape)

Ticket embeddings : (2243, 384)
Solution embeddings : (2243, 384)

In [11]:
# ==========================================
# REQUÊTE DE TEST
# ==========================================

query = """
GCA printer is not working and delivery sheets cannot be printed.
"""

print(query)

GCA printer is not working and delivery sheets cannot be printed.

In [12]:
# ==========================================
# PRÉPARATION DES CANDIDATS
# ==========================================

from sklearn.metrics.pairwise import cosine_similarity

query_embedding = model.encode(
    [query],
    normalize_embeddings=True
)[0]

# Normaliser les embeddings des tickets
ticket_embeddings_norm = (
    embeddings /
    np.linalg.norm(
        embeddings,
        axis=1,
        keepdims=True
    )
)

# Similarité nouveau ticket ↔ historique
ticket_similarities = (
    ticket_embeddings_norm @ query_embedding
)

# Top 20
top_indices = np.argsort(
    ticket_similarities
)[::-1][:20]

candidates = knowledge_base.iloc[
    top_indices
].copy()

candidates["Ticket_Similarity"] = (
    ticket_similarities[top_indices]
)

# Seulement les solutions ACTIONABLE
actionable = candidates[
    candidates["solution_type"] == "ACTIONABLE"
].copy()

print("Nombre de candidats ACTIONABLE :", len(actionable))

print(
    actionable[
        [
            "Number",
            "Short Description",
            "Solution",
            "source",
            "Ticket_Similarity"
        ]
    ].to_string(index=False)
)

Nombre de candidats ACTIONABLE : 10
     Number                                                                           Short Description                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                Solution    source  Ticket_Similarity
INC66310792                          Issue printing Delivery Sheet from GCA - (GCA Printer :  maagapr1)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      Printer has been fixed.\nResolved. ESCALATED           0.780634
INC65363499                                       Issue printing from GCA after printer model changed !                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    Printer setup has been updated and it is working now.\n\nResolved.\n ESCALATED           0.663335

In [13]:
# ==========================================
# RECONSTRUIRE LES CANDIDATS ACTIONABLE
# ==========================================

query = """
GCA printer is not working and delivery sheets cannot be printed.
"""

query_embedding = model.encode(
    [query],
    normalize_embeddings=True
)[0]

# Normaliser les embeddings tickets
ticket_embeddings_norm = (
    embeddings /
    np.linalg.norm(
        embeddings,
        axis=1,
        keepdims=True
    )
)

# Similarité nouveau ticket / historique
ticket_similarities = (
    ticket_embeddings_norm @ query_embedding
)

# Prendre les 20 tickets les plus proches
top_k_tickets = 20

top_indices = np.argsort(
    ticket_similarities
)[::-1][:top_k_tickets]

candidates = knowledge_base.iloc[
    top_indices
].copy()

candidates["Ticket_Similarity"] = (
    ticket_similarities[top_indices]
)

# Garder uniquement ACTIONABLE
actionable = candidates[
    candidates["solution_type"] == "ACTIONABLE"
].copy()

actionable = actionable.sort_values(
    "Ticket_Similarity",
    ascending=False
)

print("Nombre de candidats ACTIONABLE :", len(actionable))

print(
    actionable[
        [
            "Number",
            "Short Description",
            "Solution",
            "Ticket_Similarity",
            "source",
            "solution_type"
        ]
    ].to_string(index=False)
)

Nombre de candidats ACTIONABLE : 10
     Number                                                                           Short Description                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                Solution  Ticket_Similarity    source solution_type
INC66310792                          Issue printing Delivery Sheet from GCA - (GCA Printer :  maagapr1)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      Printer has been fixed.\nResolved.           0.780634 ESCALATED    ACTIONABLE
INC65363499                                       Issue printing from GCA after printer model changed !                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    Printer setup has been updated and it is working now.\n\nResolved.\n           0.663335 ESCALATED    ACTIONABLE

In [14]:
# ==========================================
# RECONSTRUIRE LES CLUSTERS
# ==========================================

from sklearn.cluster import AgglomerativeClustering

def cluster_similar_solutions(
    solution_similarity_matrix,
    threshold=0.75
):

    distance_matrix = (
        1 - solution_similarity_matrix.values
    )

    clustering = AgglomerativeClustering(
        n_clusters=None,
        metric="precomputed",
        linkage="average",
        distance_threshold=1 - threshold
    )

    labels = clustering.fit_predict(
        distance_matrix
    )

    clustered = pd.DataFrame({
        "Number": solution_similarity_matrix.index,
        "Cluster": labels
    })

    return clustered

In [15]:
clusters = cluster_similar_solutions(
    solution_similarity_matrix,
    threshold=0.75
)

print("===== GROUPES DE SOLUTIONS =====")

for cluster_id in sorted(
    clusters["Cluster"].unique()
):

    tickets = clusters[
        clusters["Cluster"] == cluster_id
    ]["Number"].tolist()

    print(f"\nCLUSTER {cluster_id}")
    print("-" * 40)

    for ticket in tickets:
        print(ticket)

NameError: name 'solution_similarity_matrix' is not defined

In [18]:
print("Shape :", solution_similarity_matrix.shape)

Shape : (2243, 2243)

In [21]:
# ==========================================
# MATRICE DE SIMILARITÉ DES SOLUTIONS
# DES CANDIDATS ACTIONABLE
# ==========================================

from sklearn.metrics.pairwise import cosine_similarity
import numpy as np
import pandas as pd

# Index des tickets ACTIONABLE
actionable_indices = actionable.index.tolist()

# Embeddings des solutions des candidats uniquement
actionable_solution_embeddings = solution_embeddings[
    actionable_indices
]

# Similarité entre les solutions candidates
solution_similarity_values = cosine_similarity(
    actionable_solution_embeddings
)

# DataFrame avec les numéros des tickets
solution_similarity_matrix = pd.DataFrame(
    solution_similarity_values,
    index=actionable["Number"],
    columns=actionable["Number"]
)

print("===== MATRICE DES SOLUTIONS CANDIDATES =====")

print(
    "Shape :",
    solution_similarity_matrix.shape
)

print("\nTickets :")
print(
    solution_similarity_matrix.index.tolist()
)

print("\nMatrice :")
print(
    solution_similarity_matrix.round(3)
)

===== MATRICE DES SOLUTIONS CANDIDATES =====
Shape : (10, 10)

Tickets :
['INC66310792', 'INC65363499', 'INC66441487', 'INC64341450', 'INC65033159', 'INC64304524', 'INC65410555', 'INC61302569', 'INC61933011', 'INC65461130']

Matrice :
Number       INC66310792  INC65363499  INC66441487  INC64341450  INC65033159  \
Number
INC66310792        1.000        0.833        0.199        0.823        0.489
INC65363499        0.833        1.000        0.277        0.824        0.603
INC66441487        0.199        0.277        1.000        0.209        0.207
INC64341450        0.823        0.824        0.209        1.000        0.509
INC65033159        0.489        0.603        0.207        0.509        1.000
INC64304524        0.459        0.307        0.268        0.418        0.192
INC65410555        0.407        0.406        0.123        0.389        0.570
INC61302569        0.468        0.609        0.216        0.490        0.807
INC61933011        0.167        0.220        0.297        0.217        0.189
INC65461130        0.327        0.467        0.231        0.602        0.423

Number       INC64304524  INC65410555  INC61302569  INC61933011  INC65461130
Number
INC66310792        0.459        0.407        0.468        0.167        0.327
INC65363499        0.307        0.406        0.609        0.220        0.467
INC66441487        0.268        0.123        0.216        0.297        0.231
INC64341450        0.418        0.389        0.490        0.217        0.602
INC65033159        0.192        0.570        0.807        0.189        0.423
INC64304524        1.000        0.270        0.212        0.277        0.184
INC65410555        0.270        1.000        0.597        0.157        0.308
INC61302569        0.212        0.597        1.000        0.190        0.366
INC61933011        0.277        0.157        0.190        1.000        0.150
INC65461130        0.184        0.308        0.366        0.150        1.000

In [19]:
print("Nombre de solutions :", len(solution_similarity_matrix))

Nombre de solutions : 2243

In [20]:
print("Nombre de lignes :", solution_similarity_matrix.shape[0])
print("Nombre de colonnes :", solution_similarity_matrix.shape[1])

print(
    "\nPremiers tickets :"
)

print(
    solution_similarity_matrix.index[:10].tolist()
)

Nombre de lignes : 2243
Nombre de colonnes : 2243

Premiers tickets :
['INC61070901', 'INC62031525', 'INC67542407', 'INC63115290', 'INC61393750', 'INC66441487', 'INC64928937', 'INC64305092', 'INC61219128', 'INC64864098']

In [22]:
print(actionable[["Number", "Ticket_Similarity"]])

           Number  Ticket_Similarity
1841  INC66310792           0.780634
1838  INC65363499           0.663335
5     INC66441487           0.645664
2021  INC64341450           0.626882
1972  INC65033159           0.623463
1946  INC64304524           0.585298
1827  INC65410555           0.583644
1981  INC61302569           0.583277
2003  INC61933011           0.574992
1837  INC65461130           0.565794

In [23]:
print(solution_similarity_matrix.round(3))

Number       INC66310792  INC65363499  INC66441487  INC64341450  INC65033159  \
Number
INC66310792        1.000        0.833        0.199        0.823        0.489
INC65363499        0.833        1.000        0.277        0.824        0.603
INC66441487        0.199        0.277        1.000        0.209        0.207
INC64341450        0.823        0.824        0.209        1.000        0.509
INC65033159        0.489        0.603        0.207        0.509        1.000
INC64304524        0.459        0.307        0.268        0.418        0.192
INC65410555        0.407        0.406        0.123        0.389        0.570
INC61302569        0.468        0.609        0.216        0.490        0.807
INC61933011        0.167        0.220        0.297        0.217        0.189
INC65461130        0.327        0.467        0.231        0.602        0.423

Number       INC64304524  INC65410555  INC61302569  INC61933011  INC65461130
Number
INC66310792        0.459        0.407        0.468        0.167        0.327
INC65363499        0.307        0.406        0.609        0.220        0.467
INC66441487        0.268        0.123        0.216        0.297        0.231
INC64341450        0.418        0.389        0.490        0.217        0.602
INC65033159        0.192        0.570        0.807        0.189        0.423
INC64304524        1.000        0.270        0.212        0.277        0.184
INC65410555        0.270        1.000        0.597        0.157        0.308
INC61302569        0.212        0.597        1.000        0.190        0.366
INC61933011        0.277        0.157        0.190        1.000        0.150
INC65461130        0.184        0.308        0.366        0.150        1.000

In [24]:
# ==========================================
# CLUSTERING DES SOLUTIONS
# ==========================================

clusters = cluster_similar_solutions(
    solution_similarity_matrix,
    threshold=0.75
)

print("===== GROUPES DE SOLUTIONS =====")

for cluster_id in sorted(
    clusters["Cluster"].unique()
):

    tickets = clusters[
        clusters["Cluster"] == cluster_id
    ]["Number"].tolist()

    print(f"\nCLUSTER {cluster_id}")
    print("-" * 40)

    for ticket in tickets:
        print(ticket)

===== GROUPES DE SOLUTIONS =====

CLUSTER 0
----------------------------------------
INC65033159
INC61302569

CLUSTER 1
----------------------------------------
INC65461130

CLUSTER 2
----------------------------------------
INC66310792
INC65363499
INC64341450

CLUSTER 3
----------------------------------------
INC66441487

CLUSTER 4
----------------------------------------
INC61933011

CLUSTER 5
----------------------------------------
INC64304524

CLUSTER 6
----------------------------------------
INC65410555

In [25]:
# ==========================================
# STATISTIQUES DES CLUSTERS
# ==========================================

cluster_stats = []

for cluster_id in sorted(clusters["Cluster"].unique()):

    # Tickets du cluster
    cluster_numbers = clusters.loc[
        clusters["Cluster"] == cluster_id,
        "Number"
    ].tolist()

    # Récupérer les candidats correspondants
    cluster_data = actionable[
        actionable["Number"].isin(cluster_numbers)
    ].copy()

    # -------------------------------
    # Similarité avec le nouveau ticket
    # -------------------------------

    ticket_mean = cluster_data[
        "Ticket_Similarity"
    ].mean()

    ticket_max = cluster_data[
        "Ticket_Similarity"
    ].max()

    # -------------------------------
    # Cohérence des solutions
    # -------------------------------

    if len(cluster_numbers) > 1:

        matrix = solution_similarity_matrix.loc[
            cluster_numbers,
            cluster_numbers
        ].values

        upper_values = matrix[
            np.triu_indices(
                len(matrix),
                k=1
            )
        ]

        solution_coherence = upper_values.mean()

    else:

        # Pour un cluster singleton,
        # aucune comparaison interne n'est possible.
        solution_coherence = np.nan

    # -------------------------------
    # Nombre de preuves
    # -------------------------------

    number_of_tickets = len(cluster_data)

    cluster_stats.append({

        "Cluster": cluster_id,

        "Number_of_Tickets":
            number_of_tickets,

        "Ticket_Similarity_Mean":
            ticket_mean,

        "Ticket_Similarity_Max":
            ticket_max,

        "Solution_Coherence":
            solution_coherence
    })


cluster_stats = pd.DataFrame(
    cluster_stats
)

print(
    "===== STATISTIQUES DES CLUSTERS ====="
)

print(
    cluster_stats
    .sort_values(
        "Ticket_Similarity_Mean",
        ascending=False
    )
    .round(4)
    .to_string(index=False)
)

===== STATISTIQUES DES CLUSTERS =====
 Cluster  Number_of_Tickets  Ticket_Similarity_Mean  Ticket_Similarity_Max  Solution_Coherence
       2                  3                  0.6903                 0.7806              0.8266
       3                  1                  0.6457                 0.6457                 NaN
       0                  2                  0.6034                 0.6235              0.8072
       5                  1                  0.5853                 0.5853                 NaN
       6                  1                  0.5836                 0.5836                 NaN
       4                  1                  0.5750                 0.5750                 NaN
       1                  1                  0.5658                 0.5658                 NaN

In [26]:
z# ==========================================
# SOLUTION REPRESENTATIVE DE CHAQUE CLUSTER
# ==========================================

representative_solutions = []

for cluster_id in sorted(
    clusters["Cluster"].unique()
):

    cluster_numbers = clusters.loc[
        clusters["Cluster"] == cluster_id,
        "Number"
    ].tolist()

    cluster_data = actionable[
        actionable["Number"].isin(cluster_numbers)
    ].copy()

    # Cluster singleton
    if len(cluster_numbers) == 1:

        ticket_number = cluster_numbers[0]

        row = cluster_data[
            cluster_data["Number"] == ticket_number
        ].iloc[0]

        representative_solutions.append({
            "Cluster": cluster_id,
            "Number": ticket_number,
            "Solution": row["Solution"],
            "Ticket_Similarity":
                row["Ticket_Similarity"],
            "Internal_Similarity": 1.0
        })

        continue

    # Matrice du cluster
    matrix = solution_similarity_matrix.loc[
        cluster_numbers,
        cluster_numbers
    ]

    # Similarité moyenne avec les autres solutions
    mean_similarities = {}

    for ticket_number in cluster_numbers:

        other_tickets = [
            t for t in cluster_numbers
            if t != ticket_number
        ]

        mean_similarity = matrix.loc[
            ticket_number,
            other_tickets
        ].mean()

        mean_similarities[
            ticket_number
        ] = mean_similarity

    # Solution la plus centrale
    representative_ticket = max(
        mean_similarities,
        key=mean_similarities.get
    )

    row = cluster_data[
        cluster_data["Number"] ==
        representative_ticket
    ].iloc[0]

    representative_solutions.append({

        "Cluster": cluster_id,

        "Number":
            representative_ticket,

        "Solution":
            row["Solution"],

        "Ticket_Similarity":
            row["Ticket_Similarity"],

        "Internal_Similarity":
            mean_similarities[
                representative_ticket
            ]
    })


representative_solutions = pd.DataFrame(
    representative_solutions
)

print(
    "===== SOLUTIONS REPRESENTATIVES ====="
)

print(
    representative_solutions[
        [
            "Cluster",
            "Number",
            "Ticket_Similarity",
            "Internal_Similarity",
            "Solution"
        ]
    ].to_string(index=False)
)

===== SOLUTIONS REPRESENTATIVES =====
 Cluster      Number  Ticket_Similarity  Internal_Similarity                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                Solution
       0 INC65033159           0.623463             0.807221                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       Mentioned printers were recreated on both servers as requested.\n\ndevice for matngpr3: beh:/1/0/60/socket://23.82.14.5:9100\ndevice for matngpr4: beh:/1/0/60/socket://23.82.14.6:9100\nmatngpr3 accepting requests since Mon 04 Aug 2025 02:03:25 PM GMT\nmatngpr4 accepting requests since Mon 04 Aug 2025 02:03:32 PM GMT\nprinter matngpr3 is idle.  enabled since Mon 04 Aug 2025 02:03:25 PM GMT\nprinter matngpr4 is idle.  enabled since Mon 04 Aug 2025 02:03:32 PM GMT
       1 INC65461130           0.565794             1.000000                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       Get sys admin to update the driver based on the new printers (different model than the previous).

In [27]:
def rank_solution_clusters(
    cluster_scores,
    weight_relevance=0.5,
    weight_coherence=0.3,
    weight_support=0.2
):
    scores = cluster_scores.copy()

    # Cohérence NaN pour les clusters d'un seul ticket
    scores["Solution_Coherence"] = (
        scores["Solution_Coherence"]
        .fillna(0)
    )

    # Normalisation du nombre de tickets
    max_tickets = scores["Number_of_Tickets"].max()

    if max_tickets > 0:
        scores["Support"] = (
            scores["Number_of_Tickets"]
            / max_tickets
        )
    else:
        scores["Support"] = 0

    # Score final
    scores["Cluster_Final_Score"] = (
        weight_relevance
        * scores["Ticket_Similarity_Mean"]
        +
        weight_coherence
        * scores["Solution_Coherence"]
        +
        weight_support
        * scores["Support"]
    )

    return scores.sort_values(
        "Cluster_Final_Score",
        ascending=False
    )

In [28]:
ranked_clusters = rank_solution_clusters(
    cluster_scores
)

print("===== CLASSEMENT FINAL DES CLUSTERS =====")

print(
    ranked_clusters[
        [
            "Cluster",
            "Number_of_Tickets",
            "Ticket_Similarity_Mean",
            "Ticket_Similarity_Max",
            "Solution_Coherence",
            "Support",
            "Cluster_Final_Score"
        ]
    ].to_string(index=False)
)

NameError: name 'cluster_scores' is not defined

In [30]:
cluster_scores = score_solution_clusters(
    actionable,
    clusters
)

print("===== STATISTIQUES DES CLUSTERS =====")

print(
    cluster_scores.sort_values(
        "Ticket_Similarity_Mean",
        ascending=False
    ).to_string(index=False)
)

KeyError: 'None of [RangeIndex(start=4, stop=10, step=3)] are in the [index]'

In [31]:
# ==========================================
# SCORE DES CLUSTERS
# ==========================================

def score_solution_clusters(
    actionable,
    clusters,
    solution_similarity_matrix
):
    """
    Calcule un score pour chaque cluster.

    Le score repose sur :
    - la similarité moyenne des tickets avec le nouveau ticket
    - la meilleure similarité ticket
    - la cohérence interne des solutions
    - le nombre de tickets du cluster
    """

    cluster_results = []

    for cluster_id in sorted(
        clusters["Cluster"].unique()
    ):

        # --------------------------------------
        # 1. Tickets du cluster
        # --------------------------------------

        cluster_numbers = clusters.loc[
            clusters["Cluster"] == cluster_id,
            "Number"
        ].tolist()

        # --------------------------------------
        # 2. Récupérer les lignes correspondantes
        #    dans actionable
        # --------------------------------------

        cluster_data = actionable[
            actionable["Number"].isin(
                cluster_numbers
            )
        ].copy()

        # --------------------------------------
        # 3. Similarité avec le nouveau ticket
        # --------------------------------------

        ticket_similarity_mean = (
            cluster_data[
                "Ticket_Similarity"
            ].mean()
        )

        ticket_similarity_max = (
            cluster_data[
                "Ticket_Similarity"
            ].max()
        )

        # --------------------------------------
        # 4. Cohérence des solutions
        # --------------------------------------

        if len(cluster_numbers) > 1:

            matrix = solution_similarity_matrix.loc[
                cluster_numbers,
                cluster_numbers
            ].values

            upper_values = matrix[
                np.triu_indices(
                    len(matrix),
                    k=1
                )
            ]

            solution_coherence = (
                upper_values.mean()
            )

        else:

            solution_coherence = np.nan

        # --------------------------------------
        # 5. Nombre de tickets
        # --------------------------------------

        number_of_tickets = len(
            cluster_data
        )

        # --------------------------------------
        # 6. Résultat
        # --------------------------------------

        cluster_results.append({

            "Cluster":
                cluster_id,

            "Number_of_Tickets":
                number_of_tickets,

            "Ticket_Similarity_Mean":
                ticket_similarity_mean,

            "Ticket_Similarity_Max":
                ticket_similarity_max,

            "Solution_Coherence":
                solution_coherence
        })

    return pd.DataFrame(
        cluster_results
    )

In [32]:
cluster_scores = score_solution_clusters(
    actionable,
    clusters,
    solution_similarity_matrix
)

print("===== STATISTIQUES DES CLUSTERS =====")

print(
    cluster_scores.sort_values(
        "Ticket_Similarity_Mean",
        ascending=False
    ).to_string(index=False)
)

===== STATISTIQUES DES CLUSTERS =====
 Cluster  Number_of_Tickets  Ticket_Similarity_Mean  Ticket_Similarity_Max  Solution_Coherence
       2                  3                0.690284               0.780634            0.826594
       3                  1                0.645664               0.645664                 NaN
       0                  2                0.603370               0.623463            0.807221
       5                  1                0.585298               0.585298                 NaN
       6                  1                0.583644               0.583644                 NaN
       4                  1                0.574992               0.574992                 NaN
       1                  1                0.565794               0.565794                 NaN

In [33]:
# ==========================================
# CLASSEMENT DES CLUSTERS
# ==========================================

def rank_solution_clusters(
    cluster_scores,
    weight_relevance=0.5,
    weight_coherence=0.3,
    weight_support=0.2
):

    scores = cluster_scores.copy()

    # --------------------------------------
    # Cohérence
    # --------------------------------------
    # Pour un singleton, il n'y a pas de comparaison
    # avec une autre solution.
    # On considère donc la cohérence comme parfaite.
    scores["Solution_Coherence"] = (
        scores["Solution_Coherence"]
        .fillna(1.0)
    )

    # --------------------------------------
    # Support du cluster
    # --------------------------------------

    max_tickets = scores["Number_of_Tickets"].max()

    if max_tickets > 0:
        scores["Support"] = (
            scores["Number_of_Tickets"]
            / max_tickets
        )
    else:
        scores["Support"] = 0.0

    # --------------------------------------
    # Score final du cluster
    # --------------------------------------

    scores["Cluster_Final_Score"] = (

        weight_relevance
        * scores["Ticket_Similarity_Mean"]

        +

        weight_coherence
        * scores["Solution_Coherence"]

        +

        weight_support
        * scores["Support"]
    )

    # --------------------------------------
    # Classement
    # --------------------------------------

    scores = scores.sort_values(
        "Cluster_Final_Score",
        ascending=False
    ).reset_index(drop=True)

    return scores

In [34]:
ranked_clusters = rank_solution_clusters(
    cluster_scores
)

print("===== CLASSEMENT FINAL DES CLUSTERS =====")

print(
    ranked_clusters[
        [
            "Cluster",
            "Number_of_Tickets",
            "Ticket_Similarity_Mean",
            "Ticket_Similarity_Max",
            "Solution_Coherence",
            "Support",
            "Cluster_Final_Score"
        ]
    ].to_string(index=False)
)

===== CLASSEMENT FINAL DES CLUSTERS =====
 Cluster  Number_of_Tickets  Ticket_Similarity_Mean  Ticket_Similarity_Max  Solution_Coherence  Support  Cluster_Final_Score
       2                  3                0.690284               0.780634            0.826594 1.000000             0.793120
       3                  1                0.645664               0.645664            1.000000 0.333333             0.689499
       0                  2                0.603370               0.623463            0.807221 0.666667             0.677184
       5                  1                0.585298               0.585298            1.000000 0.333333             0.659316
       6                  1                0.583644               0.583644            1.000000 0.333333             0.658489
       4                  1                0.574992               0.574992            1.000000 0.333333             0.654163
       1                  1                0.565794               0.565794            1.000000 0.333333             0.649564

In [35]:
# ==========================================
# SOLUTION RECOMMANDÉE
# ==========================================

# Meilleur cluster
best_cluster = ranked_clusters.iloc[0]["Cluster"]

# Solution représentative de ce cluster
best_solution = representative_solutions[
    representative_solutions["Cluster"] == best_cluster
].iloc[0]

print("===== SOLUTION RECOMMANDÉE =====")

print(f"Cluster : {int(best_cluster)}")
print(f"Ticket historique : {best_solution['Number']}")
print(
    f"Ticket Similarity : "
    f"{best_solution['Ticket_Similarity']:.4f}"
)
print(
    f"Internal Similarity : "
    f"{best_solution['Internal_Similarity']:.4f}"
)

print("\nSolution :")
print(best_solution["Solution"])

===== SOLUTION RECOMMANDÉE =====
Cluster : 2
Ticket historique : INC65363499
Ticket Similarity : 0.6633
Internal Similarity : 0.8285

Solution :
Printer setup has been updated and it is working now.

Resolved.

In [36]:
# ==========================================
# SOLUTIONS DU MEILLEUR CLUSTER
# ==========================================

best_cluster = int(ranked_clusters.iloc[0]["Cluster"])

best_cluster_tickets = clusters[
    clusters["Cluster"] == best_cluster
]["Number"].tolist()

best_cluster_solutions = actionable[
    actionable["Number"].isin(best_cluster_tickets)
][
    [
        "Number",
        "Short Description",
        "Ticket_Similarity",
        "Solution"
    ]
].copy()

best_cluster_solutions = best_cluster_solutions.sort_values(
    "Ticket_Similarity",
    ascending=False
)

print("===== SOLUTIONS DU CLUSTER GAGNANT =====")

print(
    best_cluster_solutions.to_string(index=False)
)

===== SOLUTIONS DU CLUSTER GAGNANT =====
     Number                                                  Short Description  Ticket_Similarity                                                             Solution
INC66310792 Issue printing Delivery Sheet from GCA - (GCA Printer :  maagapr1)           0.780634                                   Printer has been fixed.\nResolved.
INC65363499              Issue printing from GCA after printer model changed !           0.663335 Printer setup has been updated and it is working now.\n\nResolved.\n
INC64341450                        GCA 7 (Delivery sheet) printing delay issue           0.626882                     Printer drivers were updated and issue resolved.

In [37]:
# ==========================================
# CONSOLIDATION DE LA SOLUTION
# ==========================================

best_cluster = int(
    ranked_clusters.iloc[0]["Cluster"]
)

cluster_solutions = actionable[
    actionable["Number"].isin(
        best_cluster_tickets
    )
].copy()

# Trier par pertinence avec le nouveau ticket
cluster_solutions = cluster_solutions.sort_values(
    "Ticket_Similarity",
    ascending=False
)

print("===== EVIDENCE POUR LA RECOMMANDATION =====")

for _, row in cluster_solutions.iterrows():

    print(
        f"\nTicket : {row['Number']}"
    )

    print(
        f"Similarity : "
        f"{row['Ticket_Similarity']:.4f}"
    )

    print(
        f"Solution : "
        f"{row['Solution']}"
    )

===== EVIDENCE POUR LA RECOMMANDATION =====

Ticket : INC66310792
Similarity : 0.7806
Solution : Printer has been fixed.
Resolved.

Ticket : INC65363499
Similarity : 0.6633
Solution : Printer setup has been updated and it is working now.

Resolved.


Ticket : INC64341450
Similarity : 0.6269
Solution : Printer drivers were updated and issue resolved.

In [38]:
# ==========================================
# RECOMMANDATION FINALE
# ==========================================

best_cluster_row = ranked_clusters.iloc[0]

recommendation = {
    "Cluster": best_cluster,

    "Cluster_Score":
        best_cluster_row["Cluster_Final_Score"],

    "Supporting_Tickets":
        best_cluster_tickets,

    "Number_of_Supporting_Tickets":
        len(best_cluster_tickets),

    "Ticket_Similarity_Mean":
        best_cluster_row["Ticket_Similarity_Mean"],

    "Solution_Coherence":
        best_cluster_row["Solution_Coherence"],

    "Recommended_Action":
        "Review and update the printer setup and/or printer drivers."
}

print("===== RECOMMANDATION FINALE =====")

for key, value in recommendation.items():
    print(f"{key}: {value}")

===== RECOMMANDATION FINALE =====
Cluster: 2
Cluster_Score: 0.7931201219558717
Supporting_Tickets: ['INC66310792', 'INC65363499', 'INC64341450']
Number_of_Supporting_Tickets: 3
Ticket_Similarity_Mean: 0.6902837753295898
Solution_Coherence: 0.8265941143035889
Recommended_Action: Review and update the printer setup and/or printer drivers.

In [39]:
print("actionable :", type(actionable))
print("model :", type(model))
print("solution_similarity_matrix :", type(solution_similarity_matrix))
print("clusters :", type(clusters))
print("cluster_scores :", type(cluster_scores))
print("representative_solutions :", type(representative_solutions))

actionable : <class 'pandas.DataFrame'>
model : <class 'sentence_transformers.sentence_transformer.model.SentenceTransformer'>
solution_similarity_matrix : <class 'pandas.DataFrame'>
clusters : <class 'pandas.DataFrame'>
cluster_scores : <class 'pandas.DataFrame'>
representative_solutions : <class 'pandas.DataFrame'>

In [40]:
print("\nColonnes actionable :")
print(actionable.columns.tolist())

print("\nNombre de tickets :", len(actionable))

Colonnes actionable :
['Number', 'Opened', 'Target Resolution Time (GMT)', 'Informed at', 'Incident Status', 'Caller', 'Assigned Group', 'Assignee', 'Short Description', 'Description', 'Solution', 'solution_type', 'source', 'text_for_embedding', 'Ticket_Similarity']

Nombre de tickets : 10

In [41]:
# ==========================================
# PREPARATION DU BACKTEST
# ==========================================

import numpy as np
import pandas as pd

# Copie propre
evaluation_data = actionable.copy()

# Reset index pour éviter les problèmes d'index
evaluation_data = evaluation_data.reset_index(drop=True)

# Embeddings des solutions historiques
solution_embeddings = model.encode(
    evaluation_data["Solution"].fillna("").tolist(),
    normalize_embeddings=True,
    show_progress_bar=True
)

print("===== PREPARATION BACKTEST =====")
print("Nombre de tickets :", len(evaluation_data))
print("Dimension embeddings :", solution_embeddings.shape)

Batches: 100%|██████████| 1/1 [00:00<00:00,  1.22it/s]

===== PREPARATION BACKTEST =====
Nombre de tickets : 10
Dimension embeddings : (10, 384)

In [42]:
# ==========================================
# BACKTEST — TEST D'UN PREMIER TICKET
# ==========================================

from sklearn.metrics.pairwise import cosine_similarity

# Ticket de test
test_idx = 0

test_ticket = evaluation_data.iloc[test_idx]

test_number = test_ticket["Number"]
test_solution = test_ticket["Solution"]

print("===== TICKET DE TEST =====")
print("Ticket :", test_number)
print("Description :", test_ticket["Short Description"])
print("\nVraie solution :")
print(test_solution)


# ------------------------------------------
# Embedding du ticket de test
# ------------------------------------------

query_embedding = model.encode(
    [test_ticket["text_for_embedding"]],
    normalize_embeddings=True
)[0]


# ------------------------------------------
# Similarité ticket ↔ tickets historiques
# ------------------------------------------

ticket_embeddings = model.encode(
    evaluation_data["text_for_embedding"].fillna("").tolist(),
    normalize_embeddings=True,
    show_progress_bar=False
)

ticket_similarities = cosine_similarity(
    [query_embedding],
    ticket_embeddings
)[0]


# ------------------------------------------
# Exclure le ticket lui-même
# ------------------------------------------

candidate_data = evaluation_data.copy()

candidate_data["Backtest_Ticket_Similarity"] = (
    ticket_similarities
)

candidate_data = candidate_data[
    candidate_data["Number"] != test_number
].copy()


# ------------------------------------------
# Top candidats
# ------------------------------------------

top_candidates = candidate_data.sort_values(
    "Backtest_Ticket_Similarity",
    ascending=False
).head(5)


print("\n===== TOP CANDIDATS =====")

print(
    top_candidates[
        [
            "Number",
            "Short Description",
            "Backtest_Ticket_Similarity",
            "Solution"
        ]
    ].to_string(index=False)
)

===== TICKET DE TEST =====
Ticket : INC66310792
Description : Issue printing Delivery Sheet from GCA - (GCA Printer :  maagapr1)

Vraie solution :
Printer has been fixed.
Resolved.

===== TOP CANDIDATS =====
     Number                                                                           Short Description  Backtest_Ticket_Similarity                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                Solution
INC65363499                                       Issue printing from GCA after printer model changed !                    0.813430                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    Printer setup has been updated and it is working now.\n\nResolved.\n
INC64341450                                                 GCA 7 (Delivery sheet) printing delay issue                    0.745577                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        Printer drivers were updated and issue resolved.

In [43]:
# ==========================================
# BACKTEST GLOBAL - TOP K TICKETS SIMILAIRES
# ==========================================

import numpy as np
import pandas as pd
from sklearn.metrics.pairwise import cosine_similarity


def run_backtest_top_k(
    actionable,
    model,
    k=3
):
    """
    Teste la recherche de tickets similaires
    sur chaque ticket historique.

    Pour chaque ticket :
    - le ticket lui-même est exclu
    - les autres tickets sont classés par similarité
    - on récupère les Top-K solutions
    """

    results = []

    # --------------------------------------
    # Embeddings de tous les tickets
    # --------------------------------------

    texts = actionable["text_for_embedding"].fillna("").tolist()

    embeddings = model.encode(
        texts,
        normalize_embeddings=True,
        show_progress_bar=True
    )

    # --------------------------------------
    # Matrice de similarité
    # --------------------------------------

    similarity_matrix = cosine_similarity(
        embeddings
    )

    numbers = actionable["Number"].tolist()

    # --------------------------------------
    # Backtest ticket par ticket
    # --------------------------------------

    for i, ticket_number in enumerate(numbers):

        true_solution = actionable.iloc[i]["Solution"]
        short_description = actionable.iloc[i]["Short Description"]

        similarities = similarity_matrix[i].copy()

        # Exclure le ticket lui-même
        similarities[i] = -1

        # Top K
        top_indices = np.argsort(
            similarities
        )[::-1][:k]

        for rank, idx in enumerate(top_indices, start=1):

            results.append({
                "Test_Ticket": ticket_number,
                "Short_Description": short_description,
                "True_Solution": true_solution,
                "Rank": rank,
                "Candidate_Ticket": numbers[idx],
                "Similarity": similarities[idx],
                "Candidate_Solution":
                    actionable.iloc[idx]["Solution"]
            })

    return pd.DataFrame(results)


backtest_results = run_backtest_top_k(
    actionable,
    model,
    k=3
)

print("===== BACKTEST TOP 3 =====")

print(
    backtest_results[
        [
            "Test_Ticket",
            "Rank",
            "Candidate_Ticket",
            "Similarity"
        ]
    ].to_string(index=False)
)

Batches: 100%|██████████| 1/1 [00:01<00:00,  1.08s/it]

===== BACKTEST TOP 3 =====
Test_Ticket  Rank Candidate_Ticket  Similarity
INC66310792     1      INC65363499    0.813430
INC66310792     2      INC64341450    0.745576
INC66310792     3      INC65033159    0.732573
INC65363499     1      INC65410555    0.863554
INC65363499     2      INC65461130    0.848982
INC65363499     3      INC66310792    0.813430
INC66441487     1      INC61302569    0.776851
INC66441487     2      INC61933011    0.770502
INC66441487     3      INC65363499    0.746227
INC64341450     1      INC65033159    0.964550
INC64341450     2      INC66310792    0.745576
INC64341450     3      INC65363499    0.719338
INC65033159     1      INC64341450    0.964550
INC65033159     2      INC66310792    0.732573
INC65033159     3      INC65363499    0.700671
INC64304524     1      INC61933011    0.773670
INC64304524     2      INC66441487    0.713477
INC64304524     3      INC64341450    0.591921
INC65410555     1      INC65461130    0.943819
INC65410555     2      INC65363499    0.863554
INC65410555     3      INC61302569    0.742068
INC61302569     1      INC66441487    0.776851
INC61302569     2      INC65410555    0.742068
INC61302569     3      INC65461130    0.714805
INC61933011     1      INC64304524    0.773670
INC61933011     2      INC66441487    0.770502
INC61933011     3      INC61302569    0.686761
INC65461130     1      INC65410555    0.943819
INC65461130     2      INC65363499    0.848982
INC65461130     3      INC61302569    0.714805

In [45]:
# ==========================================
# EVALUATION : SIMILARITE TICKET vs SOLUTION
# ==========================================

def evaluate_solution_similarity(
    backtest_results,
    actionable,
    solution_similarity_matrix
):
    results = []

    for _, row in backtest_results.iterrows():

        test_ticket = row["Test_Ticket"]
        candidate_ticket = row["Candidate_Ticket"]

        # Vérifier que les deux tickets existent
        if (
            test_ticket not in solution_similarity_matrix.index
            or
            candidate_ticket not in solution_similarity_matrix.columns
        ):
            continue

        solution_similarity = (
            solution_similarity_matrix.loc[
                test_ticket,
                candidate_ticket
            ]
        )

        results.append({
            "Test_Ticket": test_ticket,
            "Rank": row["Rank"],
            "Candidate_Ticket": candidate_ticket,
            "Ticket_Similarity": row["Similarity"],
            "Solution_Similarity": solution_similarity
        })

    return pd.DataFrame(results)


solution_backtest = evaluate_solution_similarity(
    backtest_results,
    actionable,
    solution_similarity_matrix
)

print("===== BACKTEST TICKET + SOLUTION =====")

print(
    solution_backtest.to_string(
        index=False
    )
)

===== BACKTEST TICKET + SOLUTION =====
Test_Ticket  Rank Candidate_Ticket  Ticket_Similarity  Solution_Similarity
INC66310792     1      INC65363499           0.813430             0.833449
INC66310792     2      INC64341450           0.745576             0.822696
INC66310792     3      INC65033159           0.732573             0.488680
INC65363499     1      INC65410555           0.863554             0.405881
INC65363499     2      INC65461130           0.848982             0.467044
INC65363499     3      INC66310792           0.813430             0.833449
INC66441487     1      INC61302569           0.776851             0.215570
INC66441487     2      INC61933011           0.770502             0.296535
INC66441487     3      INC65363499           0.746227             0.277345
INC64341450     1      INC65033159           0.964550             0.509221
INC64341450     2      INC66310792           0.745576             0.822696
INC64341450     3      INC65363499           0.719338             0.823637
INC65033159     1      INC64341450           0.964550             0.509221
INC65033159     2      INC66310792           0.732573             0.488680
INC65033159     3      INC65363499           0.700671             0.603371
INC64304524     1      INC61933011           0.773670             0.276895
INC64304524     2      INC66441487           0.713477             0.267780
INC64304524     3      INC64341450           0.591921             0.417888
INC65410555     1      INC65461130           0.943819             0.308039
INC65410555     2      INC65363499           0.863554             0.405881
INC65410555     3      INC61302569           0.742068             0.596611
INC61302569     1      INC66441487           0.776851             0.215570
INC61302569     2      INC65410555           0.742068             0.596611
INC61302569     3      INC65461130           0.714805             0.365655
INC61933011     1      INC64304524           0.773670             0.276895
INC61933011     2      INC66441487           0.770502             0.296535
INC61933011     3      INC61302569           0.686761             0.189993
INC65461130     1      INC65410555           0.943819             0.308039
INC65461130     2      INC65363499           0.848982             0.467044
INC65461130     3      INC61302569           0.714805             0.365655

In [46]:
# ==========================================
# STATISTIQUES DU BACKTEST
# ==========================================

print("===== STATISTIQUES =====")

for rank in [1, 2, 3]:

    data = solution_backtest[
        solution_backtest["Rank"] == rank
    ]

    print(
        f"\nTOP {rank}"
    )

    print(
        "Ticket Similarity moyenne :",
        round(
            data["Ticket_Similarity"].mean(),
            4
        )
    )

    print(
        "Solution Similarity moyenne :",
        round(
            data["Solution_Similarity"].mean(),
            4
        )
    )

    print(
        "Solution Similarity >= 0.75 :",
        round(
            (
                data["Solution_Similarity"] >= 0.75
            ).mean() * 100,
            2
        ),
        "%"
    )

===== STATISTIQUES =====

TOP 1
Ticket Similarity moyenne : 0.8595
Solution Similarity moyenne : 0.3859
Solution Similarity >= 0.75 : 10.0 %

TOP 2
Ticket Similarity moyenne : 0.7782
Solution Similarity moyenne : 0.4932
Solution Similarity >= 0.75 : 20.0 %

TOP 3
Ticket Similarity moyenne : 0.7163
Solution Similarity moyenne : 0.4962
Solution Similarity >= 0.75 : 20.0 %

In [48]:
print(backtest_results.columns.tolist())
print(backtest_results.head())

['Test_Ticket', 'Short_Description', 'True_Solution', 'Rank', 'Candidate_Ticket', 'Similarity', 'Candidate_Solution']
   Test_Ticket                                  Short_Description  \
0  INC66310792  Issue printing Delivery Sheet from GCA - (GCA ...
1  INC66310792  Issue printing Delivery Sheet from GCA - (GCA ...
2  INC66310792  Issue printing Delivery Sheet from GCA - (GCA ...
3  INC65363499  Issue printing from GCA after printer model ch...
4  INC65363499  Issue printing from GCA after printer model ch...

                                       True_Solution  Rank Candidate_Ticket  \
0                 Printer has been fixed.\nResolved.     1      INC65363499
1                 Printer has been fixed.\nResolved.     2      INC64341450
2                 Printer has been fixed.\nResolved.     3      INC65033159
3  Printer setup has been updated and it is worki...     1      INC65410555
4  Printer setup has been updated and it is worki...     2      INC65461130

   Similarity                                 Candidate_Solution
0    0.813430  Printer setup has been updated and it is worki...
1    0.745576   Printer drivers were updated and issue resolved.
2    0.732573  Mentioned printers were recreated on both serv...
3    0.863554  As per the request printer driver updated \n\n...
4    0.848982  Get sys admin to update the driver based on th...

In [49]:
# ==========================================
# SCORE COMBINÉ TICKET + SOLUTION
# ==========================================

def compute_combined_score(
    backtest_results,
    alpha=0.6,
    beta=0.4
):
    results = backtest_results.copy()

    # Vérification des colonnes nécessaires
    required_columns = [
        "Ticket_Similarity",
        "Solution_Similarity"
    ]

    missing_columns = [
        col for col in required_columns
        if col not in results.columns
    ]

    if missing_columns:
        raise ValueError(
            f"Colonnes manquantes : {missing_columns}\n"
            f"Colonnes disponibles : "
            f"{results.columns.tolist()}"
        )

    # Score combiné
    results["Combined_Score"] = (
        alpha * results["Ticket_Similarity"]
        +
        beta * results["Solution_Similarity"]
    )

    return results.sort_values(
        ["Test_Ticket", "Combined_Score"],
        ascending=[True, False]
    )

In [50]:
combined_results = compute_combined_score(
    backtest_results,
    alpha=0.6,
    beta=0.4
)

print("===== BACKTEST SCORE COMBINÉ =====")

print(
    combined_results[
        [
            "Test_Ticket",
            "Rank",
            "Candidate_Ticket",
            "Ticket_Similarity",
            "Solution_Similarity",
            "Combined_Score"
        ]
    ].to_string(index=False)
)

ValueError: Colonnes manquantes : ['Ticket_Similarity', 'Solution_Similarity']
Colonnes disponibles : ['Test_Ticket', 'Short_Description', 'True_Solution', 'Rank', 'Candidate_Ticket', 'Similarity', 'Candidate_Solution']

In [51]:
# ==========================================
# PRÉPARATION DU BACKTEST POUR LE SCORE COMBINÉ
# ==========================================

backtest_scored = backtest_results.copy()

# Renommer la similarité ticket
backtest_scored = backtest_scored.rename(
    columns={
        "Similarity": "Ticket_Similarity"
    }
)

print("===== COLONNES =====")
print(backtest_scored.columns.tolist())

print("\n===== APERÇU =====")
print(
    backtest_scored[
        [
            "Test_Ticket",
            "Rank",
            "Candidate_Ticket",
            "Ticket_Similarity",
            "Solution_Similarity"
        ]
    ].head(10).to_string(index=False)
)

===== COLONNES =====
['Test_Ticket', 'Short_Description', 'True_Solution', 'Rank', 'Candidate_Ticket', 'Ticket_Similarity', 'Candidate_Solution']

===== APERÇU =====

KeyError: "['Solution_Similarity'] not in index"

In [52]:
print("===== VARIABLES DISPONIBLES =====")

print("backtest_results :", backtest_results.shape)
print(backtest_results.columns.tolist())

print("\n===== MATRICE DE SIMILARITE DES SOLUTIONS =====")
print("shape :", solution_similarity_matrix.shape)

print("\nIndex :")
print(solution_similarity_matrix.index.tolist())

print("\nColonnes :")
print(solution_similarity_matrix.columns.tolist())

===== VARIABLES DISPONIBLES =====
backtest_results : (30, 7)
['Test_Ticket', 'Short_Description', 'True_Solution', 'Rank', 'Candidate_Ticket', 'Similarity', 'Candidate_Solution']

===== MATRICE DE SIMILARITE DES SOLUTIONS =====
shape : (10, 10)

Index :
['INC66310792', 'INC65363499', 'INC66441487', 'INC64341450', 'INC65033159', 'INC64304524', 'INC65410555', 'INC61302569', 'INC61933011', 'INC65461130']

Colonnes :
['INC66310792', 'INC65363499', 'INC66441487', 'INC64341450', 'INC65033159', 'INC64304524', 'INC65410555', 'INC61302569', 'INC61933011', 'INC65461130']

In [53]:
# ==========================================
# AJOUT DE LA SIMILARITÉ DES SOLUTIONS
# ==========================================

backtest_scored = backtest_results.copy()

# Renommer la similarité des tickets
backtest_scored = backtest_scored.rename(
    columns={
        "Similarity": "Ticket_Similarity"
    }
)

# Calculer la similarité entre :
# solution du ticket de test
# et solution du ticket candidat

backtest_scored["Solution_Similarity"] = (
    backtest_scored.apply(
        lambda row: solution_similarity_matrix.loc[
            row["Test_Ticket"],
            row["Candidate_Ticket"]
        ],
        axis=1
    )
)

print("===== BACKTEST AVEC SIMILARITÉ DES SOLUTIONS =====")

print(
    backtest_scored[
        [
            "Test_Ticket",
            "Rank",
            "Candidate_Ticket",
            "Ticket_Similarity",
            "Solution_Similarity"
        ]
    ].to_string(index=False)
)

===== BACKTEST AVEC SIMILARITÉ DES SOLUTIONS =====
Test_Ticket  Rank Candidate_Ticket  Ticket_Similarity  Solution_Similarity
INC66310792     1      INC65363499           0.813430             0.833449
INC66310792     2      INC64341450           0.745576             0.822696
INC66310792     3      INC65033159           0.732573             0.488680
INC65363499     1      INC65410555           0.863554             0.405881
INC65363499     2      INC65461130           0.848982             0.467044
INC65363499     3      INC66310792           0.813430             0.833449
INC66441487     1      INC61302569           0.776851             0.215570
INC66441487     2      INC61933011           0.770502             0.296535
INC66441487     3      INC65363499           0.746227             0.277345
INC64341450     1      INC65033159           0.964550             0.509221
INC64341450     2      INC66310792           0.745576             0.822696
INC64341450     3      INC65363499           0.719338             0.823637
INC65033159     1      INC64341450           0.964550             0.509221
INC65033159     2      INC66310792           0.732573             0.488680
INC65033159     3      INC65363499           0.700671             0.603371
INC64304524     1      INC61933011           0.773670             0.276895
INC64304524     2      INC66441487           0.713477             0.267780
INC64304524     3      INC64341450           0.591921             0.417888
INC65410555     1      INC65461130           0.943819             0.308039
INC65410555     2      INC65363499           0.863554             0.405881
INC65410555     3      INC61302569           0.742068             0.596611
INC61302569     1      INC66441487           0.776851             0.215570
INC61302569     2      INC65410555           0.742068             0.596611
INC61302569     3      INC65461130           0.714805             0.365655
INC61933011     1      INC64304524           0.773670             0.276895
INC61933011     2      INC66441487           0.770502             0.296535
INC61933011     3      INC61302569           0.686761             0.189993
INC65461130     1      INC65410555           0.943819             0.308039
INC65461130     2      INC65363499           0.848982             0.467044
INC65461130     3      INC61302569           0.714805             0.365655

In [54]:
# ==========================================
# SCORE COMBINÉ TICKET + SOLUTION
# ==========================================

def compute_combined_score(
    backtest_results,
    alpha=0.6,
    beta=0.4
):
    results = backtest_results.copy()

    results["Combined_Score"] = (
        alpha * results["Ticket_Similarity"]
        +
        beta * results["Solution_Similarity"]
    )

    # Recalcul du rang selon le score combiné
    results["Combined_Rank"] = (
        results
        .groupby("Test_Ticket")["Combined_Score"]
        .rank(
            ascending=False,
            method="first"
        )
        .astype(int)
    )

    return results


combined_results = compute_combined_score(
    backtest_scored,
    alpha=0.6,
    beta=0.4
)

print("===== CLASSEMENT AVEC SCORE COMBINÉ =====")

print(
    combined_results[
        [
            "Test_Ticket",
            "Candidate_Ticket",
            "Ticket_Similarity",
            "Solution_Similarity",
            "Combined_Score",
            "Combined_Rank"
        ]
    ]
    .sort_values(
        ["Test_Ticket", "Combined_Rank"]
    )
    .to_string(index=False)
)

===== CLASSEMENT AVEC SCORE COMBINÉ =====
Test_Ticket Candidate_Ticket  Ticket_Similarity  Solution_Similarity  Combined_Score  Combined_Rank
INC61302569      INC65410555           0.742068             0.596611        0.683885              1
INC61302569      INC65461130           0.714805             0.365655        0.575145              2
INC61302569      INC66441487           0.776851             0.215570        0.552339              3
INC61933011      INC66441487           0.770502             0.296535        0.580915              1
INC61933011      INC64304524           0.773670             0.276895        0.574960              2
INC61933011      INC61302569           0.686761             0.189993        0.488054              3
INC64304524      INC61933011           0.773670             0.276895        0.574960              1
INC64304524      INC66441487           0.713477             0.267780        0.535198              2
INC64304524      INC64341450           0.591921             0.417888        0.522308              3
INC64341450      INC65033159           0.964550             0.509221        0.782419              1
INC64341450      INC66310792           0.745576             0.822696        0.776424              2
INC64341450      INC65363499           0.719338             0.823637        0.761058              3
INC65033159      INC64341450           0.964550             0.509221        0.782419              1
INC65033159      INC65363499           0.700671             0.603371        0.661751              2
INC65033159      INC66310792           0.732573             0.488680        0.635016              3
INC65363499      INC66310792           0.813430             0.833449        0.821438              1
INC65363499      INC65461130           0.848982             0.467044        0.696207              2
INC65363499      INC65410555           0.863554             0.405881        0.680485              3
INC65410555      INC65461130           0.943819             0.308039        0.689507              1
INC65410555      INC61302569           0.742068             0.596611        0.683885              2
INC65410555      INC65363499           0.863554             0.405881        0.680485              3
INC65461130      INC65363499           0.848982             0.467044        0.696207              1
INC65461130      INC65410555           0.943819             0.308039        0.689507              2
INC65461130      INC61302569           0.714805             0.365655        0.575145              3
INC66310792      INC65363499           0.813430             0.833449        0.821438              1
INC66310792      INC64341450           0.745576             0.822696        0.776424              2
INC66310792      INC65033159           0.732573             0.488680        0.635016              3
INC66441487      INC61933011           0.770502             0.296535        0.580915              1
INC66441487      INC65363499           0.746227             0.277345        0.558674              2
INC66441487      INC61302569           0.776851             0.215570        0.552339              3

In [57]:
# ==========================================
# BACKTEST END-TO-END — PRÉPARATION
# ==========================================

def normalize_solution(text):
    """
    Normalise légèrement une solution pour faciliter
    la comparaison textuelle finale.
    """
    return (
        str(text)
        .strip()
        .lower()
        .replace("\n", " ")
        .replace("\r", " ")
    )


# On utilise uniquement les tickets ACTIONABLE
backtest_data = actionable.copy().reset_index(drop=True)

print("===== DONNÉES DE BACKTEST =====")
print("Nombre de tickets :", len(backtest_data))

print("\nColonnes disponibles :")
print(backtest_data.columns.tolist())

print("\nExemple :")
print(
    backtest_data[
        [
            "Number",
            "Short Description",
            "Solution",
            "Ticket_Similarity"
        ]
    ].head()
)

===== DONNÉES DE BACKTEST =====
Nombre de tickets : 10

Colonnes disponibles :
['Number', 'Opened', 'Target Resolution Time (GMT)', 'Informed at', 'Incident Status', 'Caller', 'Assigned Group', 'Assignee', 'Short Description', 'Description', 'Solution', 'solution_type', 'source', 'text_for_embedding', 'Ticket_Similarity']

Exemple :
        Number                                  Short Description  \
0  INC66310792  Issue printing Delivery Sheet from GCA - (GCA ...
1  INC65363499  Issue printing from GCA after printer model ch...
2  INC66441487                            Print issue in GCA7 app
3  INC64341450        GCA 7 (Delivery sheet) printing delay issue
4  INC65033159        GCA 7 (Delivery sheet) printing delay issue

                                            Solution  Ticket_Similarity
0                 Printer has been fixed.\nResolved.           0.780634
1  Printer setup has been updated and it is worki...           0.663335
2                       TN Provider is working on it           0.645664
3   Printer drivers were updated and issue resolved.           0.626882
4  Mentioned printers were recreated on both serv...           0.623463

In [56]:
# ==========================================
# BACKTEST END-TO-END — UN SEUL TICKET
# ==========================================

from sklearn.metrics.pairwise import cosine_similarity
from sklearn.cluster import AgglomerativeClustering
import numpy as np
import pandas as pd


def backtest_one_ticket(
    test_idx,
    data,
    model,
    top_k=5,
    cluster_threshold=0.75
):

    # ======================================
    # 1. TICKET DE TEST
    # ======================================

    test_ticket = data.iloc[test_idx]

    test_number = test_ticket["Number"]
    true_solution = test_ticket["Solution"]

    print("=" * 60)
    print("TICKET DE TEST")
    print("=" * 60)

    print("Number :", test_number)
    print("Description :", test_ticket["Short Description"])

    print("\nVRAIE SOLUTION (cachée au système) :")
    print(true_solution)


    # ======================================
    # 2. EMBEDDING DU TICKET DE TEST
    # ======================================

    query_embedding = model.encode(
        [test_ticket["text_for_embedding"]],
        normalize_embeddings=True
    )[0]


    # ======================================
    # 3. EMBEDDINGS DES AUTRES TICKETS
    # ======================================

    candidate_data = data[
        data["Number"] != test_number
    ].copy()

    candidate_texts = (
        candidate_data["text_for_embedding"]
        .fillna("")
        .tolist()
    )

    candidate_embeddings = model.encode(
        candidate_texts,
        normalize_embeddings=True
    )


    # ======================================
    # 4. SIMILARITÉ TICKET ↔ TICKET
    # ======================================

    ticket_similarities = cosine_similarity(
        [query_embedding],
        candidate_embeddings
    )[0]

    candidate_data["Ticket_Similarity"] = (
        ticket_similarities
    )


    # ======================================
    # 5. TOP-K TICKETS
    # ======================================

    candidate_data = candidate_data.sort_values(
        "Ticket_Similarity",
        ascending=False
    ).head(top_k).copy()


    print("\n" + "=" * 60)
    print("TOP TICKETS SIMILAIRES")
    print("=" * 60)

    print(
        candidate_data[
            [
                "Number",
                "Ticket_Similarity",
                "Short Description",
                "Solution"
            ]
        ].to_string(index=False)
    )


    # ======================================
    # 6. EMBEDDINGS DES SOLUTIONS
    # ======================================

    solution_texts = (
        candidate_data["Solution"]
        .fillna("")
        .tolist()
    )

    candidate_solution_embeddings = model.encode(
        solution_texts,
        normalize_embeddings=True
    )


    # ======================================
    # 7. MATRICE DE SIMILARITÉ DES SOLUTIONS
    # ======================================

    solution_matrix = cosine_similarity(
        candidate_solution_embeddings
    )


    solution_similarity_matrix_test = pd.DataFrame(
        solution_matrix,
        index=candidate_data["Number"],
        columns=candidate_data["Number"]
    )


    # ======================================
    # 8. CLUSTERING DES SOLUTIONS
    # ======================================

    distance_matrix = 1 - solution_matrix

    clustering = AgglomerativeClustering(
        n_clusters=None,
        metric="precomputed",
        linkage="average",
        distance_threshold=1 - cluster_threshold
    )

    labels = clustering.fit_predict(
        distance_matrix
    )

    candidate_data["Cluster"] = labels


    print("\n" + "=" * 60)
    print("CLUSTERS")
    print("=" * 60)

    for cluster_id in sorted(
        candidate_data["Cluster"].unique()
    ):

        cluster_rows = candidate_data[
            candidate_data["Cluster"] == cluster_id
        ]

        print(f"\nCluster {cluster_id}")

        for _, row in cluster_rows.iterrows():

            print(
                f"  {row['Number']} | "
                f"Ticket similarity = "
                f"{row['Ticket_Similarity']:.4f}"
            )


    # ======================================
    # 9. SCORE DES CLUSTERS
    # ======================================

    cluster_results = []

    for cluster_id in sorted(
        candidate_data["Cluster"].unique()
    ):

        cluster_data = candidate_data[
            candidate_data["Cluster"] == cluster_id
        ]

        numbers = cluster_data[
            "Number"
        ].tolist()


        # Pertinence moyenne
        ticket_mean = cluster_data[
            "Ticket_Similarity"
        ].mean()


        # Pertinence maximale
        ticket_max = cluster_data[
            "Ticket_Similarity"
        ].max()


        # Cohérence des solutions
        if len(numbers) > 1:

            matrix = solution_similarity_matrix_test.loc[
                numbers,
                numbers
            ].values

            upper_values = matrix[
                np.triu_indices(
                    len(numbers),
                    k=1
                )
            ]

            coherence = upper_values.mean()

        else:

            coherence = 1.0


        # Nombre de preuves
        support = len(cluster_data)


        cluster_results.append({

            "Cluster": cluster_id,

            "Number_of_Tickets":
                support,

            "Ticket_Similarity_Mean":
                ticket_mean,

            "Ticket_Similarity_Max":
                ticket_max,

            "Solution_Coherence":
                coherence
        })


    cluster_scores_test = pd.DataFrame(
        cluster_results
    )


    # ======================================
    # 10. SUPPORT NORMALISÉ
    # ======================================

    max_support = (
        cluster_scores_test[
            "Number_of_Tickets"
        ].max()
    )

    cluster_scores_test["Support"] = (
        cluster_scores_test[
            "Number_of_Tickets"
        ] / max_support
    )


    # ======================================
    # 11. SCORE FINAL DU CLUSTER
    # ======================================

    cluster_scores_test[
        "Cluster_Final_Score"
    ] = (

        0.5 *
        cluster_scores_test[
            "Ticket_Similarity_Mean"
        ]

        +

        0.3 *
        cluster_scores_test[
            "Solution_Coherence"
        ]

        +

        0.2 *
        cluster_scores_test[
            "Support"
        ]
    )


    cluster_scores_test = (
        cluster_scores_test
        .sort_values(
            "Cluster_Final_Score",
            ascending=False
        )
        .reset_index(drop=True)
    )


    print("\n" + "=" * 60)
    print("CLASSEMENT DES CLUSTERS")
    print("=" * 60)

    print(
        cluster_scores_test.to_string(
            index=False
        )
    )


    # ======================================
    # 12. CLUSTER GAGNANT
    # ======================================

    best_cluster = int(
        cluster_scores_test.iloc[0]["Cluster"]
    )

    winning_cluster_data = candidate_data[
        candidate_data["Cluster"] == best_cluster
    ].copy()


    # ======================================
    # 13. SOLUTION REPRESENTATIVE
    # ======================================

    winning_numbers = (
        winning_cluster_data["Number"]
        .tolist()
    )

    if len(winning_numbers) == 1:

        representative_number = (
            winning_numbers[0]
        )

        internal_similarity = 1.0

    else:

        matrix = solution_similarity_matrix_test.loc[
            winning_numbers,
            winning_numbers
        ]

        mean_similarities = {}

        for number in winning_numbers:

            others = [
                n for n in winning_numbers
                if n != number
            ]

            mean_similarities[number] = (
                matrix.loc[
                    number,
                    others
                ].mean()
            )

        representative_number = max(
            mean_similarities,
            key=mean_similarities.get
        )

        internal_similarity = (
            mean_similarities[
                representative_number
            ]
        )


    representative_row = winning_cluster_data[
        winning_cluster_data["Number"]
        == representative_number
    ].iloc[0]


    recommended_solution = (
        representative_row["Solution"]
    )


    # ======================================
    # 14. RÉSULTAT FINAL
    # ======================================

    print("\n" + "=" * 60)
    print("RÉSULTAT DU BACKTEST")
    print("=" * 60)

    print("\nTicket de test :")
    print(test_number)

    print("\nCluster gagnant :")
    print(best_cluster)

    print("\nTicket représentant :")
    print(representative_number)

    print("\nSimilarité ticket du représentant :")
    print(
        round(
            representative_row[
                "Ticket_Similarity"
            ],
            4
        )
    )

    print("\nCohérence interne :")
    print(
        round(
            internal_similarity,
            4
        )
    )

    print("\nSOLUTION RECOMMANDÉE :")
    print(recommended_solution)

    print("\nVRAIE SOLUTION :")
    print(true_solution)


    return {
        "Test_Ticket": test_number,
        "True_Solution": true_solution,
        "Best_Cluster": best_cluster,
        "Representative_Ticket": representative_number,
        "Recommended_Solution": recommended_solution,
        "Cluster_Score":
            cluster_scores_test.iloc[0][
                "Cluster_Final_Score"
            ],
        "Cluster_Scores":
            cluster_scores_test,
        "Candidates":
            candidate_data,
        "Solution_Matrix":
            solution_similarity_matrix_test
    }

In [58]:
result_test = backtest_one_ticket(
    test_idx=0,
    data=backtest_data,
    model=model,
    top_k=5,
    cluster_threshold=0.75
)

============================================================
TICKET DE TEST
============================================================
Number : INC66310792
Description : Issue printing Delivery Sheet from GCA - (GCA Printer :  maagapr1)

VRAIE SOLUTION (cachée au système) :
Printer has been fixed.
Resolved.

============================================================
TOP TICKETS SIMILAIRES
============================================================
     Number  Ticket_Similarity                                                                           Short Description                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                Solution
INC65363499           0.813430                                       Issue printing from GCA after printer model changed !                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    Printer setup has been updated and it is working now.\n\nResolved.\n
INC64341450           0.745577                                                 GCA 7 (Delivery sheet) printing delay issue                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        Printer drivers were updated and issue resolved.

In [59]:
# ==========================================
# BACKTEST END-TO-END GLOBAL
# ==========================================

def run_end_to_end_backtest(
    evaluation_data,
    model,
    top_k=5,
    cluster_threshold=0.75
):
    """
    Backtest complet du pipeline.

    Pour chaque ticket :
    - le ticket est considéré comme nouveau
    - sa vraie solution est cachée
    - les autres tickets servent de base historique
    - recherche des tickets similaires
    - filtrage ACTIONABLE
    - clustering des solutions
    - scoring des clusters
    - sélection d'une solution représentative
    - comparaison avec la vraie solution
    """

    results = []

    # Embeddings des tickets
    ticket_texts = (
        evaluation_data["text_for_embedding"]
        .fillna("")
        .tolist()
    )

    ticket_embeddings = model.encode(
        ticket_texts,
        normalize_embeddings=True,
        show_progress_bar=False
    )

    # Embeddings des solutions
    solution_texts = (
        evaluation_data["Solution"]
        .fillna("")
        .tolist()
    )

    solution_embeddings_all = model.encode(
        solution_texts,
        normalize_embeddings=True,
        show_progress_bar=False
    )

    numbers = evaluation_data["Number"].tolist()

    # ======================================
    # TICKET PAR TICKET
    # ======================================

    for test_idx, test_number in enumerate(numbers):

        print(
            f"Backtest {test_idx + 1}/{len(numbers)} : "
            f"{test_number}"
        )

        test_row = evaluation_data.iloc[test_idx]

        true_solution = test_row["Solution"]

        # ----------------------------------
        # 1. Embedding du ticket de test
        # ----------------------------------

        query_embedding = ticket_embeddings[test_idx]

        # ----------------------------------
        # 2. Similarité avec tous les tickets
        # ----------------------------------

        ticket_similarities = (
            ticket_embeddings @ query_embedding
        )

        # ----------------------------------
        # 3. Exclure le ticket lui-même
        # ----------------------------------

        ticket_similarities[test_idx] = -1

        # ----------------------------------
        # 4. Top K
        # ----------------------------------

        top_indices = np.argsort(
            ticket_similarities
        )[::-1][:top_k]

        candidates = evaluation_data.iloc[
            top_indices
        ].copy()

        candidates["Ticket_Similarity"] = (
            ticket_similarities[top_indices]
        )

        # ----------------------------------
        # 5. ACTIONABLE uniquement
        # ----------------------------


        actionable_test = candidates[
            candidates["solution_type"] == "ACTIONABLE"
        ].copy()

        if actionable_test.empty:
            continue

        # ----------------------------------
        # 6. Embeddings des solutions
        # ----------------------------------

        actionable_indices = actionable_test.index.tolist()

        actionable_solution_embeddings = (
            solution_embeddings_all[
                actionable_indices
            ]
        )

        # ----------------------------------
        # 7. Similarité entre solutions
        # ----------------------------------

        solution_similarity_values = cosine_similarity(
            actionable_solution_embeddings
        )

        solution_similarity_matrix_test = pd.DataFrame(
            solution_similarity_values,
            index=actionable_test["Number"],
            columns=actionable_test["Number"]
        )

        # ----------------------------------
        # 8. Clustering
        # ----------------------------------

        clusters_test = cluster_similar_solutions(
            solution_similarity_matrix_test,
            threshold=cluster_threshold
        )

        # ----------------------------------
        # 9. Score des clusters
        # ----------------------------------

        cluster_scores_test = score_solution_clusters(
            actionable_test,
            clusters_test,
            solution_similarity_matrix_test
        )

        # ----------------------------------
        # 10. Classement des clusters
        # ----------------------------------

        ranked_clusters_test = rank_solution_clusters(
            cluster_scores_test
        )

        if ranked_clusters_test.empty:
            continue

        # ----------------------------------
        # 11. Cluster gagnant
        # ----------------------------------

        best_cluster = int(
            ranked_clusters_test.iloc[0]["Cluster"]
        )

        best_cluster_numbers = clusters_test[
            clusters_test["Cluster"] == best_cluster
        ]["Number"].tolist()

        # ----------------------------------
        # 12. Trouver la solution représentative
        # ----------------------------------

        cluster_data = actionable_test[
            actionable_test["Number"].isin(
                best_cluster_numbers
            )
        ].copy()

        if len(best_cluster_numbers) == 1:

            representative_row = (
                cluster_data.iloc[0]
            )

            internal_similarity = 1.0

        else:

            matrix = solution_similarity_matrix_test.loc[
                best_cluster_numbers,
                best_cluster_numbers
            ]

            mean_similarities = {}

            for ticket_number in best_cluster_numbers:

                others = [
                    t
                    for t in best_cluster_numbers
                    if t != ticket_number
                ]

                mean_similarities[ticket_number] = (
                    matrix.loc[
                        ticket_number,
                        others
                    ].mean()
                )

            representative_ticket = max(
                mean_similarities,
                key=mean_similarities.get
            )

            representative_row = cluster_data[
                cluster_data["Number"]
                == representative_ticket
            ].iloc[0]

            internal_similarity = (
                mean_similarities[
                    representative_ticket
                ]
            )

        # ----------------------------------
        # 13. Solution recommandée
        # ----------------------------------

        recommended_solution = (
            representative_row["Solution"]
        )

        representative_ticket = (
            representative_row["Number"]
        )

        ticket_similarity = (
            representative_row["Ticket_Similarity"]
        )

        # ----------------------------------
        # 14. Comparaison avec vraie solution
        # ----------------------------------

        true_solution_embedding = model.encode(
            [true_solution],
            normalize_embeddings=True
        )[0]

        recommended_solution_embedding = (
            model.encode(
                [recommended_solution],
                normalize_embeddings=True
            )[0]
        )

        solution_similarity_to_true = (
            true_solution_embedding
            @ recommended_solution_embedding
        )

        # ----------------------------------
        # 15. Résultat
        # ----------------------------------

        results.append({

            "Test_Ticket":
                test_number,

            "True_Solution":
                true_solution,

            "Best_Cluster":
                best_cluster,

            "Representative_Ticket":
                representative_ticket,

            "Ticket_Similarity":
                ticket_similarity,

            "Internal_Similarity":
                internal_similarity,

            "Cluster_Score":
                ranked_clusters_test.iloc[0][
                    "Cluster_Final_Score"
                ],

            "Recommended_Solution":
                recommended_solution,

            "Solution_Similarity":
                solution_similarity_to_true,

            "Number_of_Supporting_Tickets":
                len(best_cluster_numbers)
        })

    return pd.DataFrame(results)

In [60]:
end_to_end_results = run_end_to_end_backtest(
    evaluation_data,
    model,
    top_k=5,
    cluster_threshold=0.75
)

Backtest 1/10 : INC66310792
Backtest 2/10 : INC65363499
Backtest 3/10 : INC66441487
Backtest 4/10 : INC64341450
Backtest 5/10 : INC65033159
Backtest 6/10 : INC64304524
Backtest 7/10 : INC65410555
Backtest 8/10 : INC61302569
Backtest 9/10 : INC61933011
Backtest 10/10 : INC65461130

In [61]:
print("===== BACKTEST END-TO-END =====")

print(
    end_to_end_results[
        [
            "Test_Ticket",
            "Best_Cluster",
            "Representative_Ticket",
            "Ticket_Similarity",
            "Internal_Similarity",
            "Cluster_Score",
            "Solution_Similarity"
        ]
    ]
    .round(4)
    .to_string(index=False)
)

===== BACKTEST END-TO-END =====
Test_Ticket  Best_Cluster Representative_Ticket  Ticket_Similarity  Internal_Similarity  Cluster_Score  Solution_Similarity
INC66310792             0           INC65363499             0.8134               0.8236         0.8368               0.8334
INC65363499             2           INC65410555             0.8636               1.0000         0.8318               0.4059
INC66441487             0           INC65363499             0.7462               0.8334         0.8135               0.2773
INC64341450             0           INC65033159             0.9646               0.8072         0.8450               0.5092
INC65033159             0           INC65363499             0.7007               0.8285         0.8476               0.6034
INC64304524             2           INC61933011             0.7737               1.0000         0.7868               0.2769
INC65410555             2           INC65461130             0.9438               1.0000         0.8719               0.3080
INC61302569             2           INC66441487             0.7769               1.0000         0.8884               0.2156
INC61933011             2           INC64304524             0.7737               1.0000         0.7868               0.2769
INC65461130             3           INC65410555             0.9438               1.0000         0.8719               0.3080

In [62]:
# ==========================================
# CONSOLIDATION DES ÉVIDENCES
# ==========================================

def build_recommendation_evidence(
    ranked_clusters,
    clusters,
    actionable,
    representative_solutions
):
    """
    Construit les preuves historiques utilisées
    pour générer la recommandation finale.

    Aucune nouvelle solution n'est générée ici.
    """

    # --------------------------------------
    # 1. Cluster gagnant
    # --------------------------------------

    best_cluster = int(
        ranked_clusters.iloc[0]["Cluster"]
    )

    best_cluster_row = ranked_clusters.iloc[0]

    # --------------------------------------
    # 2. Tickets appartenant au cluster
    # --------------------------------------

    cluster_numbers = clusters.loc[
        clusters["Cluster"] == best_cluster,
        "Number"
    ].tolist()

    # --------------------------------------
    # 3. Récupérer les données historiques
    # --------------------------------------

    cluster_data = actionable[
        actionable["Number"].isin(cluster_numbers)
    ].copy()

    # Trier par pertinence avec le nouveau ticket
    cluster_data = cluster_data.sort_values(
        "Ticket_Similarity",
        ascending=False
    )

    # --------------------------------------
    # 4. Construire les preuves
    # --------------------------------------

    supporting_tickets = []

    for _, row in cluster_data.iterrows():

        supporting_tickets.append({

            "Number":
                row["Number"],

            "Short_Description":
                row["Short Description"],

            "Ticket_Similarity":
                float(row["Ticket_Similarity"]),

            "Solution":
                row["Solution"]
        })

    # --------------------------------------
    # 5. Solution représentative
    # --------------------------------------

    representative = representative_solutions[
        representative_solutions["Cluster"]
        == best_cluster
    ]

    if not representative.empty:

        representative = representative.iloc[0]

        representative_ticket = (
            representative["Number"]
        )

        representative_solution = (
            representative["Solution"]
        )

    else:

        representative_ticket = None
        representative_solution = None

    # --------------------------------------
    # 6. Objet final d'évidence
    # --------------------------------------

    evidence = {

        "Best_Cluster":
            best_cluster,

        "Cluster_Score":
            float(
                best_cluster_row[
                    "Cluster_Final_Score"
                ]
            ),

        "Solution_Coherence":
            float(
                best_cluster_row[
                    "Solution_Coherence"
                ]
            ),

        "Number_of_Supporting_Tickets":
            len(supporting_tickets),

        "Supporting_Tickets":
            supporting_tickets,

        "Representative_Ticket":
            representative_ticket,

        "Representative_Solution":
            representative_solution
    }

    return evidence

In [63]:
# ==========================================
# CONSTRUCTION DES ÉVIDENCES
# ==========================================

recommendation_evidence = (
    build_recommendation_evidence(
        ranked_clusters,
        clusters,
        actionable,
        representative_solutions
    )
)

print("===== RECOMMENDATION EVIDENCE =====")

print(
    "Cluster gagnant :",
    recommendation_evidence["Best_Cluster"]
)

print(
    "Score du cluster :",
    round(
        recommendation_evidence["Cluster_Score"],
        4
    )
)

print(
    "Cohérence des solutions :",
    round(
        recommendation_evidence["Solution_Coherence"],
        4
    )
)

print(
    "Nombre de tickets support :",
    recommendation_evidence[
        "Number_of_Supporting_Tickets"
    ]
)

print("\n===== TICKETS SUPPORT =====")

for ticket in recommendation_evidence[
    "Supporting_Tickets"
]:

    print(
        f"\n{ticket['Number']}"
    )

    print(
        "Ticket similarity :",
        round(
            ticket["Ticket_Similarity"],
            4
        )
    )

    print(
        "Solution :",
        ticket["Solution"]
    )

print(
    "\n===== SOLUTION REPRESENTATIVE ====="
)

print(
    recommendation_evidence[
        "Representative_Ticket"
    ]
)

print(
    recommendation_evidence[
        "Representative_Solution"
    ]
)

===== RECOMMENDATION EVIDENCE =====
Cluster gagnant : 2
Score du cluster : 0.7931
Cohérence des solutions : 0.8266
Nombre de tickets support : 3

===== TICKETS SUPPORT =====

INC66310792
Ticket similarity : 0.7806
Solution : Printer has been fixed.
Resolved.

INC65363499
Ticket similarity : 0.6633
Solution : Printer setup has been updated and it is working now.

Resolved.


INC64341450
Ticket similarity : 0.6269
Solution : Printer drivers were updated and issue resolved.

===== SOLUTION REPRESENTATIVE =====
INC65363499
Printer setup has been updated and it is working now.

Resolved.

In [64]:
# ==========================================
# GÉNÉRATION DE LA RECOMMANDATION
# À PARTIR DES ÉVIDENCES HISTORIQUES
# ==========================================

def generate_recommendation_from_evidence(
    recommendation_evidence
):
    """
    Génère une recommandation naturelle à partir
    des solutions historiques du cluster gagnant.

    Important :
    aucune nouvelle solution n'est inventée.
    """

    supporting_tickets = (
        recommendation_evidence[
            "Supporting_Tickets"
        ]
    )

    if not supporting_tickets:
        return (
            "No reliable historical solution was "
            "found for this incident."
        )

    # --------------------------------------
    # Récupérer les solutions historiques
    # --------------------------------------

    solutions = [
        str(ticket["Solution"]).strip()
        for ticket in supporting_tickets
        if str(ticket["Solution"]).strip()
    ]

    # --------------------------------------
    # Détecter les actions présentes
    # dans les solutions historiques
    # --------------------------------------

    actions = []

    for solution in solutions:

        solution_lower = solution.lower()

        if (
            "printer setup" in solution_lower
            or "printer configuration" in solution_lower
        ):
            actions.append(
                "review and update the printer setup"
            )

        if "printer driver" in solution_lower:
            actions.append(
                "update the printer drivers"
            )

        if (
            "printer has been fixed" in solution_lower
            or "working now" in solution_lower
            or "issue resolved" in solution_lower
        ):
            actions.append(
                "verify that the printer is working correctly"
            )

    # Supprimer les doublons
    actions = list(dict.fromkeys(actions))

    # --------------------------------------
    # Construire la recommandation
    # --------------------------------------

    if not actions:

        return (
            "Based on similar historical incidents, "
            "review the solutions from the supporting "
            "historical tickets."
        )

    recommendation_parts = []

    if any(
        "printer setup" in action
        for action in actions
    ):
        recommendation_parts.append(
            "review and update the printer setup"
        )

    if any(
        "printer drivers" in action
        for action in actions
    ):
        recommendation_parts.append(
            "update the printer drivers"
        )

    # Première partie : actions
    if len(recommendation_parts) == 2:

        action_sentence = (
            f"Based on similar historical incidents, "
            f"review and update the printer setup "
            f"and update the printer drivers as required."
        )

    elif len(recommendation_parts) == 1:

        action_sentence = (
            "Based on similar historical incidents, "
            f"{recommendation_parts[0]} as required."
        )

    else:

        action_sentence = (
            "Based on similar historical incidents, "
            "review the applicable printer configuration."
        )

    # --------------------------------------
    # Vérification finale
    # --------------------------------------

    if any(
        "verify" in action
        for action in actions
    ):

        action_sentence += (
            " Then verify that the printer is "
            "working correctly."
        )

    return action_sentence

In [65]:
# ==========================================
# TEST DE LA RECOMMANDATION
# ==========================================

recommendation = (
    generate_recommendation_from_evidence(
        recommendation_evidence
    )
)

print("===== RECOMMANDATION FINALE =====")
print()
print(recommendation)

===== RECOMMANDATION FINALE =====

Based on similar historical incidents, review and update the printer setup and update the printer drivers as required. Then verify that the printer is working correctly.

In [66]:
# ==========================================
# BACKTEST END-TO-END DE LA RECOMMANDATION
# ==========================================

def run_end_to_end_backtest(
    evaluation_data,
    model,
    top_k=5,
    cluster_threshold=0.75
):
    """
    Évalue tout le pipeline sur chaque ticket historique.

    Pour chaque ticket :
        1. Le ticket est retiré de la recherche
        2. Recherche des tickets similaires
        3. Conservation des solutions ACTIONABLE
        4. Clustering des solutions
        5. Sélection du cluster gagnant
        6. Construction des évidences
        7. Génération de la recommandation
    """

    results = []

    numbers = evaluation_data["Number"].tolist()

    for test_idx, test_number in enumerate(numbers):

        print(
            f"Backtest {test_idx + 1}/{len(numbers)} : "
            f"{test_number}"
        )

        # ======================================
        # 1. Ticket de test
        # ======================================

        test_ticket = evaluation_data.iloc[test_idx]

        true_solution = test_ticket["Solution"]

        # ======================================
        # 2. Base historique
        # ======================================

        historical_data = evaluation_data[
            evaluation_data["Number"] != test_number
        ].copy()

        historical_data = historical_data.reset_index(
            drop=True
        )

        if len(historical_data) == 0:
            continue

        # ======================================
        # 3. Embeddings des tickets historiques
        # ======================================

        historical_embeddings = model.encode(
            historical_data[
                "text_for_embedding"
            ].fillna("").tolist(),
            normalize_embeddings=True,
            show_progress_bar=False
        )

        # ======================================
        # 4. Embedding du ticket de test
        # ======================================

        query_embedding = model.encode(
            [test_ticket["text_for_embedding"]],
            normalize_embeddings=True
        )[0]

        # ======================================
        # 5. Similarité ticket ↔ historique
        # ======================================

        similarities = cosine_similarity(
            [query_embedding],
            historical_embeddings
        )[0]

        historical_data[
            "Ticket_Similarity"
        ] = similarities

        # ======================================
        # 6. Top K
        # ======================================

        top_indices = np.argsort(
            similarities
        )[::-1][:top_k]

        candidates = historical_data.iloc[
            top_indices
        ].copy()

        # ======================================
        # 7. ACTIONABLE uniquement
        # ======================================

        candidates = candidates[
            candidates["solution_type"]
            == "ACTIONABLE"
        ].copy()

        if candidates.empty:
            continue

        candidates = candidates.sort_values(
            "Ticket_Similarity",
            ascending=False
        )

        candidates = candidates.reset_index(
            drop=True
        )

        # ======================================
        # 8. Embeddings des solutions
        # ======================================

        candidate_solution_embeddings = model.encode(
            candidates["Solution"]
            .fillna("")
            .tolist(),
            normalize_embeddings=True,
            show_progress_bar=False
        )

        # ======================================
        # 9. Matrice de similarité des solutions
        # ======================================

        solution_matrix = cosine_similarity(
            candidate_solution_embeddings
        )

        solution_similarity_matrix_local = pd.DataFrame(
            solution_matrix,
            index=candidates["Number"],
            columns=candidates["Number"]
        )

        # ======================================
        # 10. Clustering
        # ======================================

        local_clusters = cluster_similar_solutions(
            solution_similarity_matrix_local,
            threshold=cluster_threshold
        )

        # ======================================
        # 11. Statistiques des clusters
        # ======================================

        local_cluster_scores = score_solution_clusters(
            candidates,
            local_clusters,
            solution_similarity_matrix_local
        )

        # ======================================
        # 12. Classement des clusters
        # ======================================

        local_ranked_clusters = rank_solution_clusters(
            local_cluster_scores
        )

        # ======================================
        # 13. Solutions représentatives
        # ======================================

        local_representatives = []

        for cluster_id in sorted(
            local_clusters["Cluster"].unique()
        ):

            cluster_numbers = local_clusters.loc[
                local_clusters["Cluster"] == cluster_id,
                "Number"
            ].tolist()

            cluster_data = candidates[
                candidates["Number"].isin(
                    cluster_numbers
                )
            ]

            if len(cluster_numbers) == 1:

                row = cluster_data.iloc[0]

                local_representatives.append({

                    "Cluster": cluster_id,

                    "Number":
                        row["Number"],

                    "Solution":
                        row["Solution"],

                    "Ticket_Similarity":
                        row["Ticket_Similarity"],

                    "Internal_Similarity":
                        1.0
                })

            else:

                matrix = (
                    solution_similarity_matrix_local
                    .loc[
                        cluster_numbers,
                        cluster_numbers
                    ]
                )

                mean_similarities = {}

                for ticket_number in cluster_numbers:

                    others = [
                        t
                        for t in cluster_numbers
                        if t != ticket_number
                    ]

                    mean_similarities[
                        ticket_number
                    ] = matrix.loc[
                        ticket_number,
                        others
                    ].mean()

                representative_ticket = max(
                    mean_similarities,
                    key=mean_similarities.get
                )

                row = cluster_data[
                    cluster_data["Number"]
                    == representative_ticket
                ].iloc[0]

                local_representatives.append({

                    "Cluster":
                        cluster_id,

                    "Number":
                        representative_ticket,

                    "Solution":
                        row["Solution"],

                    "Ticket_Similarity":
                        row["Ticket_Similarity"],

                    "Internal_Similarity":
                        mean_similarities[
                            representative_ticket
                        ]
                })

        local_representatives = pd.DataFrame(
            local_representatives
        )

        # ======================================
        # 14. Cluster gagnant
        # ======================================

        best_cluster = int(
            local_ranked_clusters.iloc[0]["Cluster"]
        )

        # ======================================
        # 15. Construire les évidences
        # ======================================

        local_evidence = (
            build_recommendation_evidence(
                local_ranked_clusters,
                local_clusters,
                candidates,
                local_representatives
            )
        )

        # ======================================
        # 16. Générer recommandation
        # ======================================

        recommendation = (
            generate_recommendation_from_evidence(
                local_evidence
            )
        )

        # ======================================
        # 17. Représentant
        # ======================================

        representative = local_representatives[
            local_representatives["Cluster"]
            == best_cluster
        ].iloc[0]

        # ======================================
        # 18. Similarité solution
        # ======================================

        representative_ticket = (
            representative["Number"]
        )

        solution_similarity = (
            cosine_similarity(
                model.encode(
                    [true_solution],
                    normalize_embeddings=True
                ),
                model.encode(
                    [representative["Solution"]],
                    normalize_embeddings=True
                )
            )[0][0]
        )

        # ======================================
        # 19. Résultat
        # ======================================

        best_cluster_row = (
            local_ranked_clusters.iloc[0]
        )

        results.append({

            "Test_Ticket":
                test_number,

            "True_Solution":
                true_solution,

            "Best_Cluster":
                best_cluster,

            "Representative_Ticket":
                representative_ticket,

            "Ticket_Similarity":
                representative[
                    "Ticket_Similarity"
                ],

            "Internal_Similarity":
                representative[
                    "Internal_Similarity"
                ],

            "Cluster_Score":
                best_cluster_row[
                    "Cluster_Final_Score"
                ],

            "Solution_Similarity":
                solution_similarity,

            "Recommendation":
                recommendation
        })

    return pd.DataFrame(results)

In [67]:
# ==========================================
# LANCEMENT DU BACKTEST END-TO-END
# ==========================================

end_to_end_results = run_end_to_end_backtest(
    evaluation_data,
    model,
    top_k=5,
    cluster_threshold=0.75
)

print("\n===== BACKTEST END-TO-END =====")

print(
    end_to_end_results[
        [
            "Test_Ticket",
            "Representative_Ticket",
            "Ticket_Similarity",
            "Internal_Similarity",
            "Cluster_Score",
            "Solution_Similarity"
        ]
    ].to_string(index=False)
)

Backtest 1/10 : INC66310792
Backtest 2/10 : INC65363499
Backtest 3/10 : INC66441487
Backtest 4/10 : INC64341450
Backtest 5/10 : INC65033159
Backtest 6/10 : INC64304524
Backtest 7/10 : INC65410555
Backtest 8/10 : INC61302569
Backtest 9/10 : INC61933011
Backtest 10/10 : INC65461130

===== BACKTEST END-TO-END =====
Test_Ticket Representative_Ticket  Ticket_Similarity  Internal_Similarity  Cluster_Score  Solution_Similarity
INC66310792           INC65363499           0.813430             0.823637       0.836843             0.833449
INC65363499           INC65410555           0.863555             1.000000       0.831777             0.405881
INC66441487           INC65363499           0.746227             0.833449       0.813510             0.277345
INC64341450           INC65033159           0.964551             0.807221       0.845048             0.509221
INC65033159           INC65363499           0.700671             0.828543       0.847611             0.603371
INC64304524           INC61933011           0.773670             1.000000       0.786835             0.276895
INC65410555           INC65461130           0.943819             1.000000       0.871909             0.308039
INC61302569           INC66441487           0.776851             1.000000       0.888425             0.215570
INC61933011           INC64304524           0.773670             1.000000       0.786835             0.276895
INC65461130           INC65410555           0.943818             1.000000       0.871909             0.308039

In [68]:
# ==========================================
# EVALUATION GLOBALE DU BACKTEST END-TO-END
# ==========================================

results = end_to_end_results.copy()

print("=" * 60)
print("EVALUATION GLOBALE DU BACKTEST")
print("=" * 60)

# ------------------------------------------
# 1. Nombre de tickets testés
# ------------------------------------------

number_of_tests = len(results)

print("\nNombre de tickets testés :", number_of_tests)


# ------------------------------------------
# 2. Similarité ticket moyenne
# ------------------------------------------

print("\n===== TICKET SIMILARITY =====")

print(
    "Moyenne :",
    round(
        results["Ticket_Similarity"].mean(),
        4
    )
)

print(
    "Médiane :",
    round(
        results["Ticket_Similarity"].median(),
        4
    )
)

print(
    "Minimum :",
    round(
        results["Ticket_Similarity"].min(),
        4
    )
)

print(
    "Maximum :",
    round(
        results["Ticket_Similarity"].max(),
        4
    )
)


# ------------------------------------------
# 3. Similarité de solution
# ------------------------------------------

print("\n===== SOLUTION SIMILARITY =====")

solution_mean = results[
    "Solution_Similarity"
].mean()

solution_median = results[
    "Solution_Similarity"
].median()

print(
    "Moyenne :",
    round(solution_mean, 4)
)

print(
    "Médiane :",
    round(solution_median, 4)
)

print(
    "Minimum :",
    round(
        results["Solution_Similarity"].min(),
        4
    )
)

print(
    "Maximum :",
    round(
        results["Solution_Similarity"].max(),
        4
    )
)


# ------------------------------------------
# 4. Pourcentage de solutions suffisamment proches
# ------------------------------------------

print("\n===== SEUILS DE SIMILARITÉ =====")

for threshold in [0.50, 0.60, 0.70, 0.75, 0.80]:

    percentage = (
        results["Solution_Similarity"] >= threshold
    ).mean() * 100

    print(
        f"Solution Similarity >= {threshold:.2f} : "
        f"{percentage:.2f}%"
    )


# ------------------------------------------
# 5. Qualité des clusters gagnants
# ------------------------------------------

print("\n===== CLUSTERS =====")

print(
    "Score cluster moyen :",
    round(
        results["Cluster_Score"].mean(),
        4
    )
)

print(
    "Cohérence interne moyenne :",
    round(
        results["Internal_Similarity"].mean(),
        4
    )
)


# ------------------------------------------
# 6. Tableau récapitulatif
# ------------------------------------------

summary = pd.DataFrame({

    "Metric": [
        "Nombre de tickets testés",
        "Ticket Similarity moyenne",
        "Solution Similarity moyenne",
        "Solution Similarity médiane",
        "Solution Similarity >= 0.60",
        "Solution Similarity >= 0.70",
        "Solution Similarity >= 0.75",
        "Solution Similarity >= 0.80",
        "Cluster Score moyen",
        "Cohérence interne moyenne"
    ],

    "Value": [

        number_of_tests,

        round(
            results["Ticket_Similarity"].mean(),
            4
        ),

        round(
            results["Solution_Similarity"].mean(),
            4
        ),

        round(
            results["Solution_Similarity"].median(),
            4
        ),

        round(
            (
                results["Solution_Similarity"] >= 0.60
            ).mean() * 100,
            2
        ),

        round(
            (
                results["Solution_Similarity"] >= 0.70
            ).mean() * 100,
            2
        ),

        round(
            (
                results["Solution_Similarity"] >= 0.75
            ).mean() * 100,
            2
        ),

        round(
            (
                results["Solution_Similarity"] >= 0.80
            ).mean() * 100,
            2
        ),

        round(
            results["Cluster_Score"].mean(),
            4
        ),

        round(
            results["Internal_Similarity"].mean(),
            4
        )
    ]
})

print("\n===== TABLEAU RÉCAPITULATIF =====")

print(
    summary.to_string(index=False)
)

============================================================
EVALUATION GLOBALE DU BACKTEST
============================================================

Nombre de tickets testés : 10

===== TICKET SIMILARITY =====
Moyenne : 0.83
Médiane : 0.7951
Minimum : 0.7007
Maximum : 0.9646

===== SOLUTION SIMILARITY =====
Moyenne : 0.4015
Médiane : 0.308
Minimum : 0.2156
Maximum : 0.8334

===== SEUILS DE SIMILARITÉ =====
Solution Similarity >= 0.50 : 30.00%
Solution Similarity >= 0.60 : 20.00%
Solution Similarity >= 0.70 : 10.00%
Solution Similarity >= 0.75 : 10.00%
Solution Similarity >= 0.80 : 10.00%

===== CLUSTERS =====
Score cluster moyen : 0.8381
Cohérence interne moyenne : 0.9293

===== TABLEAU RÉCAPITULATIF =====
                     Metric   Value
   Nombre de tickets testés 10.0000
  Ticket Similarity moyenne  0.8300
Solution Similarity moyenne  0.4015
Solution Similarity médiane  0.3080
Solution Similarity >= 0.60 20.0000
Solution Similarity >= 0.70 10.0000
Solution Similarity >= 0.75 10.0000
Solution Similarity >= 0.80 10.0000
        Cluster Score moyen  0.8381
  Cohérence interne moyenne  0.9293

In [69]:
# ==========================================
# DIAGNOSTIC DU BACKTEST
# COMPARAISON PIPELINE vs MEILLEURE SOLUTION
# ==========================================

diagnostic_results = []

# Embeddings des solutions
solution_embeddings_eval = model.encode(
    evaluation_data["Solution"].fillna("").tolist(),
    normalize_embeddings=True,
    show_progress_bar=False
)

solution_matrix_eval = cosine_similarity(
    solution_embeddings_eval
)

numbers = evaluation_data["Number"].tolist()


for _, result in end_to_end_results.iterrows():

    test_ticket = result["Test_Ticket"]
    representative = result["Representative_Ticket"]

    # --------------------------------------
    # Position du ticket de test
    # --------------------------------------

    test_idx = numbers.index(test_ticket)

    # --------------------------------------
    # Similarités solution avec tous les
    # autres tickets
    # --------------------------------------

    solution_similarities = (
        solution_matrix_eval[test_idx].copy()
    )

    # Exclure le ticket lui-même
    solution_similarities[test_idx] = -1

    # Meilleure solution historique
    best_idx = np.argmax(
        solution_similarities
    )

    best_ticket = numbers[best_idx]
    best_solution_similarity = (
        solution_similarities[best_idx]
    )

    # --------------------------------------
    # Résultat du pipeline
    # --------------------------------------

    pipeline_solution_similarity = (
        result["Solution_Similarity"]
    )

    # --------------------------------------
    # Ecart avec la meilleure solution
    # --------------------------------------

    gap = (
        best_solution_similarity
        -
        pipeline_solution_similarity
    )

    diagnostic_results.append({

        "Test_Ticket":
            test_ticket,

        "Pipeline_Representative":
            representative,

        "Pipeline_Solution_Similarity":
            pipeline_solution_similarity,

        "Best_Historical_Ticket":
            best_ticket,

        "Best_Solution_Similarity":
            best_solution_similarity,

        "Gap":
            gap
    })


diagnostic_results = pd.DataFrame(
    diagnostic_results
)

print("=" * 70)
print("DIAGNOSTIC : PIPELINE VS MEILLEURE SOLUTION HISTORIQUE")
print("=" * 70)

print(
    diagnostic_results
    .sort_values(
        "Gap",
        ascending=False
    )
    .round(4)
    .to_string(index=False)
)

======================================================================
DIAGNOSTIC : PIPELINE VS MEILLEURE SOLUTION HISTORIQUE
======================================================================
Test_Ticket Pipeline_Representative  Pipeline_Solution_Similarity Best_Historical_Ticket  Best_Solution_Similarity    Gap
INC61302569             INC66441487                        0.2156            INC65033159                    0.8072 0.5917
INC65363499             INC65410555                        0.4059            INC66310792                    0.8334 0.4276
INC64341450             INC65033159                        0.5092            INC65363499                    0.8236 0.3144
INC65461130             INC65410555                        0.3080            INC64341450                    0.6022 0.2941
INC65410555             INC65461130                        0.3080            INC61302569                    0.5966 0.2886
INC65033159             INC65363499                        0.6034            INC61302569                    0.8072 0.2038
INC64304524             INC61933011                        0.2769            INC66310792                    0.4588 0.1819
INC61933011             INC64304524                        0.2769            INC66441487                    0.2965 0.0196
INC66441487             INC65363499                        0.2773            INC61933011                    0.2965 0.0192
INC66310792             INC65363499                        0.8334            INC65363499                    0.8334 0.0000

In [70]:
# ==========================================
# ANALYSE DES CLUSTERS CANDIDATS
# ==========================================

def analyze_backtest_clusters(
    evaluation_data,
    end_to_end_results,
    model,
    k=5
):

    diagnostic = []

    numbers = evaluation_data["Number"].tolist()

    # --------------------------------------
    # Embeddings des tickets
    # --------------------------------------

    ticket_embeddings = model.encode(
        evaluation_data["text_for_embedding"]
        .fillna("")
        .tolist(),
        normalize_embeddings=True,
        show_progress_bar=False
    )

    ticket_similarity_matrix = cosine_similarity(
        ticket_embeddings
    )

    # --------------------------------------
    # Embeddings des solutions
    # --------------------------------------

    solution_embeddings = model.encode(
        evaluation_data["Solution"]
        .fillna("")
        .tolist(),
        normalize_embeddings=True,
        show_progress_bar=False
    )

    solution_similarity_matrix_eval = cosine_similarity(
        solution_embeddings
    )

    # --------------------------------------
    # Analyse ticket par ticket
    # --------------------------------------

    for _, result in end_to_end_results.iterrows():

        test_ticket = result["Test_Ticket"]

        test_idx = numbers.index(test_ticket)

        # ----------------------------------
        # Top K tickets similaires
        # ----------------------------------

        similarities = (
            ticket_similarity_matrix[test_idx].copy()
        )

        # Exclure le ticket lui-même
        similarities[test_idx] = -1

        top_indices = np.argsort(
            similarities
        )[::-1][:k]

        # ----------------------------------
        # Construire les informations
        # ----------------------------------

        for idx in top_indices:

            candidate_ticket = numbers[idx]

            # Trouver le cluster du candidat
            cluster_row = clusters[
                clusters["Number"] == candidate_ticket
            ]

            if cluster_row.empty:
                continue

            cluster_id = int(
                cluster_row.iloc[0]["Cluster"]
            )

            # ----------------------------------
            # Statistiques du cluster
            # ----------------------------------

            cluster_numbers = clusters.loc[
                clusters["Cluster"] == cluster_id,
                "Number"
            ].tolist()

            cluster_data = evaluation_data[
                evaluation_data["Number"].isin(
                    cluster_numbers
                )
            ]

            # Similarité moyenne des tickets
            ticket_mean = cluster_data[
                "Ticket_Similarity"
            ].mean()

            # Similarité maximale
            ticket_max = cluster_data[
                "Ticket_Similarity"
            ].max()

            # ----------------------------------
            # Cohérence des solutions
            # ----------------------------------

            if len(cluster_numbers) > 1:

                indices_cluster = [
                    numbers.index(t)
                    for t in cluster_numbers
                ]

                matrix = solution_similarity_matrix_eval[
                    np.ix_(
                        indices_cluster,
                        indices_cluster
                    )
                ]

                upper_values = matrix[
                    np.triu_indices(
                        len(matrix),
                        k=1
                    )
                ]

                solution_coherence = (
                    upper_values.mean()
                )

            else:

                solution_coherence = 1.0

            # ----------------------------------
            # Support
            # ----------------------------------

            support = len(cluster_data)

            max_support = len(evaluation_data)

            support_normalized = (
                support / max_support
            )

            # ----------------------------------
            # Score du cluster
            # ----------------------------------

            cluster_score = (
                0.5 * ticket_mean
                +
                0.3 * solution_coherence
                +
                0.2 * support_normalized
            )

            # ----------------------------------
            # Similarité avec la vraie solution
            #
            # UNIQUEMENT pour le diagnostic
            # ----------------------------------

            true_solution_similarity = (
                solution_similarity_matrix_eval[
                    test_idx
                ]
            )

            cluster_solution_similarities = (
                true_solution_similarity[
                    [
                        numbers.index(t)
                        for t in cluster_numbers
                    ]
                ]
            )

            cluster_true_solution_mean = (
                cluster_solution_similarities.mean()
            )

            cluster_true_solution_max = (
                cluster_solution_similarities.max()
            )

            # ----------------------------------
            # Résultat
            # ----------------------------------

            diagnostic.append({

                "Test_Ticket":
                    test_ticket,

                "Cluster":
                    cluster_id,

                "Candidate_From_Cluster":
                    candidate_ticket,

                "Ticket_Similarity":
                    similarities[idx],

                "Ticket_Similarity_Mean":
                    ticket_mean,

                "Ticket_Similarity_Max":
                    ticket_max,

                "Solution_Coherence":
                    solution_coherence,

                "Support":
                    support,

                "Cluster_Score":
                    cluster_score,

                # Oracle / diagnostic seulement
                "True_Solution_Similarity_Mean":
                    cluster_true_solution_mean,

                "True_Solution_Similarity_Max":
                    cluster_true_solution_max
            })

    return pd.DataFrame(diagnostic)


cluster_diagnostic = analyze_backtest_clusters(
    evaluation_data,
    end_to_end_results,
    model,
    k=5
)

print("=" * 80)
print("ANALYSE DES CLUSTERS CANDIDATS")
print("=" * 80)

print(
    cluster_diagnostic
    .sort_values(
        ["Test_Ticket", "Cluster_Score"],
        ascending=[True, False]
    )
    .round(4)
    .to_string(index=False)
)

================================================================================
ANALYSE DES CLUSTERS CANDIDATS
================================================================================
Test_Ticket  Cluster Candidate_From_Cluster  Ticket_Similarity  Ticket_Similarity_Mean  Ticket_Similarity_Max  Solution_Coherence  Support  Cluster_Score  True_Solution_Similarity_Mean  True_Solution_Similarity_Max
INC61302569        2            INC65363499             0.7126                  0.6903                 0.7806              0.8266        3         0.6531                         0.5225                        0.6092
INC61302569        3            INC66441487             0.7769                  0.6457                 0.6457              1.0000        1         0.6428                         0.2156                        0.2156
INC61302569        6            INC65410555             0.7421                  0.5836                 0.5836              1.0000        1         0.6118                         0.5966                        0.5966
INC61302569        4            INC61933011             0.6868                  0.5750                 0.5750              1.0000        1         0.6075                         0.1900                        0.1900
INC61302569        1            INC65461130             0.7148                  0.5658                 0.5658              1.0000        1         0.6029                         0.3657                        0.3657
INC61933011        2            INC65363499             0.6453                  0.6903                 0.7806              0.8266        3         0.6531                         0.2013                        0.2199
INC61933011        2            INC66310792             0.6288                  0.6903                 0.7806              0.8266        3         0.6531                         0.2013                        0.2199
INC61933011        3            INC66441487             0.7705                  0.6457                 0.6457              1.0000        1         0.6428                         0.2965                        0.2965
INC61933011        5            INC64304524             0.7737                  0.5853                 0.5853              1.0000        1         0.6126                         0.2769                        0.2769
INC61933011        0            INC61302569             0.6868                  0.6034                 0.6235              0.8072        2         0.5839                         0.1896                        0.1900
INC64304524        2            INC64341450             0.5919                  0.6903                 0.7806              0.8266        3         0.6531                         0.3946                        0.4588
INC64304524        2            INC66310792             0.5808                  0.6903                 0.7806              0.8266        3         0.6531                         0.3946                        0.4588
INC64304524        3            INC66441487             0.7135                  0.6457                 0.6457              1.0000        1         0.6428                         0.2678                        0.2678
INC64304524        4            INC61933011             0.7737                  0.5750                 0.5750              1.0000        1         0.6075                         0.2769                        0.2769
INC64304524        0            INC65033159             0.5815                  0.6034                 0.6235              0.8072        2         0.5839                         0.2022                        0.2125
INC64341450        2            INC66310792             0.7456                  0.6903                 0.7806              0.8266        3         0.6531                         0.8821                        1.0000
INC64341450        2            INC65363499             0.7193                  0.6903                 0.7806              0.8266        3         0.6531                         0.8821                        1.0000
INC64341450        3            INC66441487             0.6959                  0.6457                 0.6457              1.0000        1         0.6428                         0.2093                        0.2093
INC64341450        0            INC65033159             0.9646                  0.6034                 0.6235              0.8072        2         0.5839                         0.4995                        0.5092
INC64341450        0            INC61302569             0.6470                  0.6034                 0.6235              0.8072        2         0.5839                         0.4995                        0.5092
INC65033159        2            INC64341450             0.9646                  0.6903                 0.7806              0.8266        3         0.6531                         0.5338                        0.6034
INC65033159        2            INC66310792             0.7326                  0.6903                 0.7806              0.8266        3         0.6531                         0.5338                        0.6034
INC65033159        2            INC65363499             0.7007                  0.6903                 0.7806              0.8266        3         0.6531                         0.5338                        0.6034
INC65033159        3            INC66441487             0.6998                  0.6457                 0.6457              1.0000        1         0.6428                         0.2075                        0.2075
INC65033159        0            INC61302569             0.6428                  0.6034                 0.6235              0.8072        2         0.5839                         0.9036                        1.0000
INC65363499        2            INC66310792             0.8134                  0.6903                 0.7806              0.8266        3         0.6531                         0.8857                        1.0000
INC65363499        2            INC64341450             0.7193                  0.6903                 0.7806              0.8266        3         0.6531                         0.8857                        1.0000
INC65363499        3            INC66441487             0.7462                  0.6457                 0.6457              1.0000        1         0.6428                         0.2773                        0.2773
INC65363499        6            INC65410555             0.8636                  0.5836                 0.5836              1.0000        1         0.6118                         0.4059                        0.4059
INC65363499        1            INC65461130             0.8490                  0.5658                 0.5658              1.0000        1         0.6029                         0.4670                        0.4670
INC65410555        2            INC65363499             0.8636                  0.6903                 0.7806              0.8266        3         0.6531                         0.4004                        0.4066
INC65410555        2            INC66310792             0.7082                  0.6903                 0.7806              0.8266        3         0.6531                         0.4004                        0.4066
INC65410555        3            INC66441487             0.6619                  0.6457                 0.6457              1.0000        1         0.6428                         0.1230                        0.1230
INC65410555        1            INC65461130             0.9438                  0.5658                 0.5658              1.0000        1         0.6029                         0.3080                        0.3080
INC65410555        0            INC61302569             0.7421                  0.6034                 0.6235              0.8072        2         0.5839                         0.5831                        0.5966
INC65461130        2            INC65363499             0.8490                  0.6903                 0.7806              0.8266        3         0.6531                         0.4653                        0.6022
INC65461130        2            INC66310792             0.6651                  0.6903                 0.7806              0.8266        3         0.6531                         0.4653                        0.6022
INC65461130        3            INC66441487             0.6668                  0.6457                 0.6457              1.0000        1         0.6428                         0.2312                        0.2312
INC65461130        6            INC65410555             0.9438                  0.5836                 0.5836              1.0000        1         0.6118                         0.3080                        0.3080
INC65461130        0            INC61302569             0.7148                  0.6034                 0.6235              0.8072        2         0.5839                         0.3943                        0.4230
INC66310792        2            INC65363499             0.8134                  0.6903                 0.7806              0.8266        3         0.6531                         0.8854                        1.0000
INC66310792        2            INC64341450             0.7456                  0.6903                 0.7806              0.8266        3         0.6531                         0.8854                        1.0000
INC66310792        3            INC66441487             0.7077                  0.6457                 0.6457              1.0000        1         0.6428                         0.1989                        0.1989
INC66310792        6            INC65410555             0.7082                  0.5836                 0.5836              1.0000        1         0.6118                         0.4066                        0.4066
INC66310792        0            INC65033159             0.7326                  0.6034                 0.6235              0.8072        2         0.5839                         0.4786                        0.4887
INC66441487        2            INC65363499             0.7462                  0.6903                 0.7806              0.8266        3         0.6531                         0.2285                        0.2773
INC66441487        2            INC66310792             0.7077                  0.6903                 0.7806              0.8266        3         0.6531                         0.2285                        0.2773
INC66441487        5            INC64304524             0.7135                  0.5853                 0.5853              1.0000        1         0.6126                         0.2678                        0.2678
INC66441487        4            INC61933011             0.7705                  0.5750                 0.5750              1.0000        1         0.6075                         0.2965                        0.2965
INC66441487        0            INC61302569             0.7769                  0.6034                 0.6235              0.8072        2         0.5839                         0.2115                        0.2156